### ISSUE TITLE
`token vs utxo` - update UI to match new design language

### ISSUE THREAD

**Issue by kyleleow** [DeFiCh/wallet#1019]
#### What UI/UX improvements would you like to be implemented: 
- Update UI of DFI Token vs UTXO screen found in Convert Screen

#### Why is this needed:
- To be consistent with overall app design

#### Which component/screens does this concern?:
- DFI Token vs UTXO screen

![image](https://user-images.githubusercontent.com/25013382/145535763-73023485-c04c-469c-a8c8-e1b9784a2a66.png)

**Comment by izzycsy** [comment]
Acceptance Criteria: Updated UI of DFI Token vs UTXO screen

Android: 
- [ ] Balances > `? Learn more about UTXO and Token` 
- [ ] Balances > Swap > `? UTXO and Token, what is the difference?` 

iOS: 
- [ ] Balances > `? Learn more about UTXO and Token` 
- [ ] Balances > Swap > `? UTXO and Token, what is the difference?`
