### ISSUE TITLE
`header UI` - `RECEIVE` in german in top right of balance screen is wrapped

### ISSUE THREAD

**Issue by kyleleow** [DeFiCh/wallet#1145]
#### What UI/UX improvements would you like to be implemented: 
- Revisit if `RECEIVE` in balance header can be avoided to be wrapped into new line in german translation

#### Why is this needed:
- To maintain a cleaner header

#### Which component/screens does this concern?:
- Balance screen

#### Anything else we need to know?:
- Not sure if it is related to moving settings icon to top left of header
- Happens in samsung galaxy a52, not on iphone 12
![image](https://user-images.githubusercontent.com/40191153/138428767-c63df6f0-c062-407b-b045-cfae9a806a40.png)

**Comment by jtlntno-cake** [comment]
Current iteration for balances page is to address this concern. Please see this [link](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=3570%3A65965)

**Comment by izzycsy** [comment]
Acceptance Criteria: UI should not break for `RECEIVE`, update on Balances screen

Android: 
- [ ]  Wallet Address card is now located at the top of screen
- [ ] `SEND`, `RECEIVE`, `VIEW ON DEFISCAN`
- [ ] Settings > Language > Switch language to DE, repeat steps above

iOS: 
- [ ]  Wallet Address card is now located at the top of screen
- [ ] `SEND`, `RECEIVE`, `VIEW ON DEFISCAN`
- [ ] Settings > Language > Switch language to DE, repeat steps above
