### ISSUE TITLE
`loans` - main page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1154]
#### What would you like to be added:
This ticket is just for the tabbing system. I've created a separate ticket for Browse Loans and Your Vaults.
- [ ] Browse Loans
- [ ] Your Vaults

![image](https://user-images.githubusercontent.com/25013382/138537323-182c1330-5d25-4e43-8442-a3d8f77e26d3.png)

**Comment by kyleleow** [comment]
This has been addressed in previous PR
