### ISSUE TITLE
`feature flag` - add platform

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1197]

**Comment by izzycsy** [comment]
Acceptance Criteria: Users can "opt-in" on Beta feature(s)

Switch Network: **Playground**
Android: 
- [ ] Beta feature for 0.15.0: Loans
- [ ] User to "opt-in" on Beta features via `Settings` > `About`
- [ ] _Beta feature_ visible only if Beta feature is available to "opt-in"
> • If there's no Beta feature, then user won't see this link
> • If there is Beta feature, user can click to opt-in


iOS: 
- [ ] Beta feature for 0.15.0: Loans
- [ ] User to "opt-in" on Beta features via `Settings` > `About`
- [ ] _Beta feature_ visible only if Beta feature is available to "opt-in"
> • If there's no Beta feature, then user won't see this link
> • If there is Beta feature, user can click to opt-in

**Comment by izzycsy** [comment]
Refer to test case here: https://github.com/DeFiCh/wallet/issues/725#issuecomment-970005136
