### ISSUE TITLE
`static` - vault details - vault details tab

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1201]
![image](https://user-images.githubusercontent.com/25013382/139564664-0b374cbe-7e8f-4924-bff9-b0a83eb84227.png)

**Comment by izzycsy** [comment]
Acceptance Criteria: Static UI to display details in vault `Details` screen

Android: 
- [ ] Loans > select a vault > select `Details` tab > click **Min. collateral ratio `i`**
- [ ] || > click **Vault interest `i`** 

iOS: 
- [ ] Loans > select a vault > select `Details` tab > click **Min. collateral ratio `i`**
- [ ] || > click **Vault interest `i`** 

Related issue: #1217
