### ISSUE TITLE
Swap with DFI displays incorrect pair

### ISSUE THREAD

**Issue by pierregee** [DeFiCh/wallet#1205]
#### What happened:
- The Pool Swap Screen displayed the incorrect pair (didn't updated from the previous screen)

#### What you expected to happen:
- The Pool Swap Screen should always display the correct pair 

#### How to reproduce it (as minimally and precisely as possible):
1. Navigate to `DEX` -> `dETH-DFI` -> `Swap Tokens`
2. Navigate to `Balances` -> `dBTC` -> `Swap with DFI`
Issue: The screen did not update the pair in Pool Swap Screen and still displays `dETH-DFI` instead of `dBTC-DFI`
![issueswap](https://user-images.githubusercontent.com/13292662/139625723-d45272d5-2deb-47df-84dd-1b95531bedee.gif)

**Comment by izzycsy** [comment]
Acceptance Criteria: Swap should be accordingly to selected pair 

Android: 
- [ ] Balances > `Swap` > DFI (UTXO) to DFI (Token) displayed > vice versa
- [ ] Balances > dETH > `Swap with DFI` > dETH to DFI displayed > vice versa
- [ ] Balances > dBTC > `Swap with DFI` > dBTC to DFI displayed > vice versa
- [ ] Balances > dUSDT > `Swap with DFI` > dUSDT to DFI displayed > vice versa

iOS:
- [ ] Balances > `Swap` > DFI (UTXO) to DFI (Token) displayed > vice versa
- [ ] Balances > dETH > `Swap with DFI` > dETH to DFI displayed > vice versa
- [ ] Balances > dBTC > `Swap with DFI` > dBTC to DFI displayed > vice versa
- [ ] Balances > dUSDT > `Swap with DFI` > dUSDT to DFI displayed > vice versa
