### ISSUE TITLE
FC Update - Composite Swap - tabs and cards

### ISSUE THREAD

**Issue by pierregee** [DeFiCh/wallet#1230]
#### What would you like to be added:
**Update design in DEX screen in preparation for composite swap**
- Instead of sections, tabs will be used
- Use cards instead of section items with updated skeleton loaders
- Add empty state for 

Related to https://github.com/DeFiCh/wallet/issues/909

#### Why is this needed:
- To be consistent with other pages and to be able to use composite swap

**Comment by izzycsy** [comment]
Acceptance Criteria: Update design for DEX

Android: 
- [ ] No more sections, new tabs to segregate `Browse pool pairs` / `Your pool pairs`
- [ ] In `Browse pool pairs`, `+ Add liquidity` & `> < Swap tokens` present
- [ ] In `Your pool pairs`, `+ Add more` & `- Remove` present


iOS:
- [ ] No more sections, new tabs to segregate `Browse pool pairs` / `Your pool pairs`
- [ ] In `Browse pool pairs`, `+ Add liquidity` & `> < Swap tokens` present
- [ ] In `Your pool pairs`, `+ Add more` & `- Remove` present
