### ISSUE TITLE
`local network` - no passcode prompt for transaction

### ISSUE THREAD

**Issue by kyleleow** [DeFiCh/wallet#1272]
#### What happened:
- When switching to `local` network through settings, performing any transaction does not prompt for passcode input

#### What you expected to happen:
- Able to trigger passcode prompt on transactions in local network

#### How to reproduce it (as minimally and precisely as possible):
- Replace URL for `LocalPlayground` environment in `WalletContext` and `PlaygroundContext` with machine's local IP
- `expo start`
- `npm run playground:start`
- Run expo go on iOS device, change network to `Local`
- Perform any transaction, e.g.: convert DFI
- Notice the transaction went through successfully without passcode prompt

#### Anything else we need to know?:
- Only happen in iPhone 12 iOS 15.1, does not happen in android or web

https://user-images.githubusercontent.com/40191153/141289081-1fe0369d-bc59-4b71-8b76-180e8475e003.MP4

**Comment by fuxingloh** [comment]
Internally you can setup your wallet without encryption, that might explain why

**Comment by fuxingloh** [comment]
![image](https://user-images.githubusercontent.com/4266087/141290550-f6771cb2-0a8d-4ba4-a7b8-c531686fa7c9.png)
