### ISSUE TITLE
TextField focus should be padded inside

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#1278]
#### What UI/UX improvements would you like to be implemented: 

![image](https://user-images.githubusercontent.com/4266087/141430082-46f2c295-bbb2-4c45-a04a-72a935ab8368.png)

Padding should be applied inside instead of outside for all TextField, especially for Web as the focus border should be where the pink border is.

#### Which component/screens does this concern?:

- TextField

**Comment by thedoublejay** [comment]
This is only an issue for Web, not for native.
