### ISSUE TITLE
`loan icons` - added loan token icons

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1299]

**Comment by izzycsy** [comment]
Acceptance Criteria: DUSD (currently dDUSD) and dTSLA are already in Mainnet.

Android: 
- [ ] Check loan token icons are updated
- [ ] Check `dDUSD` typo is now `DUSD`
- [ ] Swap DFI to DUSD 
- [ ] Swap DUSD to dTSLA
- [ ] Add liquidity; DUSD-DFI
- [ ] Add liquidity; dTSLA-DUSD

iOS:
- [ ] Check loan token icons are updated
- [ ] Check `dDUSD` typo is now `DUSD`
- [ ] Swap DFI to DUSD 
- [ ] Swap DUSD to dTSLA
- [ ] Add liquidity; DUSD-DFI
- [ ] Add liquidity; dTSLA-DUSD
