### ISSUE TITLE
`DEX` - disable Add Liquidity and Swap Tokens on DEX if pair is not trade enabled

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1303]
#### What would you like to be added:
If pair is not yet trade enabled, disable `add liquidity` and `swap tokens` buttons.

**Comment by izzycsy** [comment]
Acceptance Criteria: If pool pair trading is inactive, disable `ADD LIQUIDITY` & `SWAP TOKENS` buttons

Android: 
- [ ]
