### ISSUE TITLE
Add an indicator for insufficient DFI

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#1308]
![211116 v0 14 5 - Android - Balances - Unable to convert DFI1](https://user-images.githubusercontent.com/65014479/141955616-43ecedeb-c4d1-4dc2-a3b9-0c9fa47638bc.jpg)

![211116 v0 14 5 - Android - Balances - Unable to convert DFI2](https://user-images.githubusercontent.com/65014479/141955604-6b997b93-d660-4d81-91c3-028a954c1369.jpg)

https://user-images.githubusercontent.com/65014479/141961588-42a46ae6-3907-471a-9838-65f63d709368.mp4

#### What UI/UX improvements would you like to be implemented: 
• Add an indicator / prompt / `i` to notify user when DFI falls below 0.1

#### Why is this needed:
• Unable to convert DFI (UTXO) to DFI (Token) due to **insufficient DFI**
• When at screen to convert DFI (UTXO) to DFI (Token), DFI (UTXO) balance displays 0 even though user has DFI (UTXO) balance
• When at screen to convert DFI (Token) to DFI (UTXO), DFI (UTXO) balance displays correct balance

#### Which component/screens does this concern?:
• Balances

#### Anything else we need to know?:

![image](https://user-images.githubusercontent.com/65014479/141966165-717fc1d9-a3a8-4f91-9a77-a9e6e3b84420.png)

• At the moment, the above `i` describes the amount set aside for fees, not inform the user than he has insufficient funds

**Comment by dwivedinalin** [comment]
Acceptance Criteria:

Android:

- [ ]   Balances > Check info icon present when the total DFI amount is falls below 0.1 DFI

IOS:

- [ ]  Balances > Check info icon present when the total DFI amount is falls below 0.1 DFI

> If the total DFI balance is more than 0.1 DFI then the info `i`  need not to be present
