### ISSUE TITLE
To be able to send `all`

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#1317]
#### What would you like to be added:
• User to be able to send all 

#### Why is this needed:
• When users don’t have other tokens or vaults, they should be able to send all their UTXO to another address (including 0.1 UTXO that is reserved)

**Comment by thedoublejay** [comment]
Will be closing this. I think we can keep the behavior as is for now (reserved 0.1 DFI). Allowing this will bring in more problems. We can adjust it in the future if necessary
