### ISSUE TITLE
Vault FAQ

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1328]

**Comment by izzycsy** [comment]
Acceptance Criteria: User able to learn more about vaults via FAQ

Android: 
- [ ] Loans > `? Learn more about vaults` > Check FAQ content > Close
- [ ] Check alignment


iOS: 
- [ ] Loans > `? Learn more about vaults` > Check FAQ content > Close
- [ ] Check alignment

**Comment by izzycsy** [comment]
![211123 v0 15 6 - iOS : Android - Loans - FAQ - Learn more about vaults1](https://user-images.githubusercontent.com/65014479/142974090-4bad6534-9913-48ba-8a96-2039ba66d099.jpg)

![211123 v0 15 6 - iOS : Android - Loans - FAQ - Learn more about vaults2](https://user-images.githubusercontent.com/65014479/142974098-f83a6211-6d22-4d1c-a21a-6be979ff8397.jpg)

Android/iOS:

- [ ] Loans > ? Learn more about vaults > Check FAQ content > Close 

- [ ] Loans > Create Vault > ? Learn more about vaults and loan schemes > Check FAQ content > Close

> since the content in FAQ is the same, title for `? Learn more about vaults` button to FAQ to be the same for consistency
