### ISSUE TITLE
Vault Card - Health Bar

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1330]

**Comment by dwivedinalin** [comment]
**Acceptance criteria:** Health bar should be displayed for respective VaultID  progress bar should be highlighted as per collateralization ratio

**Android**:

- [ ]  Loans > Your vaults > collateralization ratio `greater than 150%` > progress bar should be till `Green bar`
- [ ]  Loans > Your vaults > collateralization ratio `between 0% and 150%` > progress bar should be till  `Orange bar`
- [ ]  Loans > Your vaults > collateralization ratio `less than minimum requirement` > progress bar should be till `Red bar`
- [ ]  Loans > Your vaults > price of one or more token `fluctuated more than 30% in past hour` > progress bar should be till `Grey bar`

**iOS**:

- [ ]  Loans > Your vaults > collateralization ratio `greater than 150%` > progress bar should be till `Green bar`
- [ ]  Loans > Your vaults > collateralization ratio `between 0% and 150%` > progress bar should be till  `Orange bar`
- [ ]  Loans > Your vaults > collateralization ratio `less than minimum requirement` > progress bar should be till `Red bar`
- [ ]  Loans > Your vaults > price of one or more token `fluctuated more than 30% in past hour` > progress bar should be till `Grey bar`
