### ISSUE TITLE
Vault Card - Vault ID redirect to Scan

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1333]

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:** On clicking the Vault ID user should get redirected to **https://defiscan.live/vaults**

**Android:**

- [ ]  Loans > Your Vaults > Click Vault ID > should redirect to **https://defiscan.live/vaults**

**iOS:**

- [ ]  Loans > Your Vaults > Click Vault ID > should redirect to **https://defiscan.live/vaults**
