### ISSUE TITLE
Edit Collaterals - Col Ratio - Health Style

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1335]

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:** User should be able to navigate to `Edit Collaterals` and `add/update` collateral amount

**Android:**

- [ ]  Loans > Vault ID Card > Vault Detail > Edit Collaterals > `+` > User should be able to add amount 
- [ ]  Loans > Vault ID Card > Vault Detail > Edit Collaterals > `-` > User should be able to remove amount 

**iOS:**

- [ ]  Loans > Vault ID Card > Vault Detail > Edit Collaterals > `+` > User should be able to add amount 
- [ ]  Loans > Vault ID Card > Vault Detail > Edit Collaterals > `-` > User should be able to remove amount

**Comment by izzycsy** [comment]
Android:
Loans > Vault ID Card > Vault Detail > Edit Collaterals > - > User should be able to remove amount
> [404 when REMOVE COLLATERAL](https://github.com/DeFiCh/wallet/issues/1392)
