### ISSUE TITLE
Edit Collateral - Token Input - 50% and 100% buttons

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1336]

**Comment by dwivedinalin** [comment]
**Accepting Criteria:**  Edit Collateral should have `50%` and `100%` tab

**Android:**

- [ ]  Loans > Your vaults > `Edit Collaterals` > `+`/`-` > `50%` ` 100%` tab should be present

**iOS:**

- [ ]  Loans > Your vaults > `Edit Collaterals` > `+`/`-` > `50%` ` 100%` tab should be present
