### ISSUE TITLE
Vault Detail - Collateral Tab

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1338]

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:** Verify-in Vault Detail tab  `EDIT COLLATERALS` tab is present clicking on which user is redirected to `Edit Collateral Page`

**Android:**

- [ ] Loans > Your vaults > `EDIT COLLATERALS` (check if present) > Click `EDIT COLLATERALS` > User should land on `Edit Collaterals Page`

**iOS:**

- [ ] Loans > Your vaults > `EDIT COLLATERALS` (check if present) > Click `EDIT COLLATERALS` > User should land on `Edit Collaterals Page`
