### ISSUE TITLE
Vault Detail - Loan Tab - Payback Loan

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1340]

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:** Verify `PAYBACK LOAN` button is present on the `Vault Detail` page in the `Loans` section

**Android:**

- [ ] Loans > `MANAGE LOANS` > Click `Loans` > Verify `PAYBACK LOAN` tab is present > Click `PAYBACK LOAN` > User should navigate to `PAYBACK LOAN`

**iOS:**

- [ ] Loans > `MANAGE LOANS` > Click `Loans` > Verify `PAYBACK LOAN` tab is present > Click `PAYBACK LOAN` > User should navigate to `PAYBACK LOAN`
