### ISSUE TITLE
Vault Detail - Details Tab

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1344]

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:** Verify user able to navigate till `Vault Details`

**Android:**

- [ ] Loans > Your vaults > Vault Details (Vault ID, Collaterization ratio, Total Collateral, Total Loans, Vault interest, Edit Collaterals)

**iOS:**
- [ ] Loans > Your vaults > Vault Details (Vault ID, Collaterization ratio, Total Collateral, Total Loans, Vault interest, Edit Collaterals)
