### ISSUE TITLE
Vault Detail - Redirect to Scan

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1345]

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:** On clicking `VaultID` user should redirect to [defiscan_live](https://defiscan.live/vaults)

**Android:**

- [ ] Loans > Your vaults > Click `VaultID` > User should redirect to [defiscan_live](https://defiscan.live/vaults)

**iOS:**

- [ ] Loans > Your vaults > Click `VaultID` > User should redirect to [defiscan_live](https://defiscan.live/vaults)
