### ISSUE TITLE
Take Loan - Collateralization ratio - Info (Need content @jtlntno-cake @ngyingzhong, same as Vault Card)

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1347]

**Comment by izzycsy** [comment]
Acceptance Criteria: At `Borrow Loan Loan`, app should display transaction details

**Android:** 
Selected vault for collateral, should display: 
- [ ] Total collateral (USD)
- [ ] Vault interest

Borrow Loan Token screen should display: 
- [ ] Collaterization ratio
- [ ] Min. collateral ratio 
- [ ] Interest (Vault + Token) 
- [ ] Total interest amount
- [ ] Total loan + interest
- [ ] Estimated fee `i`

**iOS:** 
Selected vault for collateral, should display: 
- [ ] Total collateral (USD)
- [ ] Vault interest

Borrow Loan Token screen should display: 
- [ ] Collaterization ratio
- [ ] Min. collateral ratio 
- [ ] Interest (Vault + Token) 
- [ ] Total interest amount
- [ ] Total loan + interest
- [ ] Estimated fee `i`
