### ISSUE TITLE
Payback Loan

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1351]

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:** Verify the user is able to pay back the loan.

**Android:**

- [ ]  Loans > Vault Details > Loans section > `PAYBACK LOAN` > Edit Amount to pay(should be less than total amount) > Confirm Loan Payment

**iOS:**

- [ ]  Loans > Vault Details > Loans section > `PAYBACK LOAN` > Edit Amount to pay(should be less than total amount) > Confirm Loan Payment
