### ISSUE TITLE
Auctions Static UI

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1357]
- [ ] Need to add Feature Gate

![image](https://user-images.githubusercontent.com/25013382/143525004-fdb1d67f-9c3c-4246-9b06-1a4913dd46a2.png)

**Comment by dwivedinalin** [comment]
Acceptance Criteria: User should be able to browser auction, place and manage bids

**Android:**

- [ ] Auctions > Browse auctions > Verify parameters in Auctions List
- [ ] Auctions > Browse auctions > `PLACE BID `
- [ ] Auctions > Manage bids > `BID List` should be displayed
- [ ] Auctions > Manage bids > `VIEW REWARDS` > Rewards for resp. bid should be listed
- [ ] Auctions > Manage bids > If BID lost then `Lost to another Bid` / `Lost` should be displayed on card 
- [ ]  Auctions > Manage bids > If BID won then `Auction Won` should be displayed on card  

**iOS:**

- [ ] Auctions > Browse auctions > Verify parameters in Auctions List
- [ ] Auctions > Browse auctions > `PLACE BID `
- [ ] Auctions > Manage bids > `BID List` should be displayed
- [ ] Auctions > Manage bids > `VIEW REWARDS` > Rewards for resp. bid should be listed
- [ ] Auctions > Manage bids > If BID lost then `Lost to another Bid` / `Lost` should be displayed on card 
- [ ]  Auctions > Manage bids > If BID won then `Auction Won` should be displayed on card
