### ISSUE TITLE
add warning for sending LP tokens 

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1375]
#### What would you like to be added:
Desktop example:

![send lp tokens warning](https://user-images.githubusercontent.com/25013382/144551514-b1851c21-32ab-476e-b754-19e2ed5481bd.png)

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:** Liquidity pools tokens warning is proactively triggered when a user sends to an external address, not within the DeFiChain network.

**Android:**

- [ ] Balances > Select token from LP > `Send to other wallet` > `Paste wallet address here` > `Continue`

**iOS:**

- [ ] Balances > Select token from LP > `Send to other wallet` > `Paste wallet address here` > `Continue`

> A warning message should be displayed sending to tokens to LP

**Comment by jtlntno-cake** [comment]
Sharing here a prototype to propose a flow for this scenario. 

Send without conversion [https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?page-id=3985%3A62946&node-id=6168%3A119195&viewport=241%2C48%2C0.3&scaling=scale-down&starting-point-node-id=6168%3A119195&show-proto-sidebar=1](url)

Send with conversion (https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?page-id=3985%3A62946&node-id=6174%3A125799&viewport=241%2C48%2C0.3&scaling=scale-down&starting-point-node-id=6174%3A125799&show-proto-sidebar=1)


Key notes:
• Add disclaimer message once detected that LP token is selected for sending
• Add toggle warning for sending out LP token in confirmation page
