### ISSUE TITLE
Unable to borrow loan

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1415]
#### What happened:

- User is unable to borrow a loan.
#### What you expected to happen:
Loans > Your vaults > (Collateral already added) `MANAGE LOANS` > `BROWSE LOAN TOKEN` > dTSLA > `Enter loan amount` > `Continue`

- User should be able to borrow a loan.

#### How to reproduce it (as minimally and precisely as possible):

Loans > Your vaults > (Collateral already added) `MANAGE LOANS` > `BROWSE LOAN TOKEN` > dTSLA > `Enter loan amount` > `Continue`

#### Anything else we need to know?
No

<img width="348" alt="Screenshot 2021-11-24 at 2 31 07 PM" src="https://user-images.githubusercontent.com/32018980/143206852-67af745a-5107-4d2f-a4eb-f923cac6653c.png">
>

:

**Comment by thedoublejay** [comment]
fixed on latest build
