### ISSUE TITLE
Broken UI of Health Badge - German

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1419]
#### What happened:
Broken UI of Health Badge

#### What you expected to happen:

UI should be as per designs

#### How to reproduce it (as minimally and precisely as possible):

For German . Loans > MANAGE LOANS > BROWSER LOAN TOKENS > dTSLA > Borrow Loan Token

#### Anything else we need to know?:

No

<img width="1010" alt="Screenshot 2021-11-24 at 2 42 52 PM" src="https://user-images.githubusercontent.com/32018980/143208908-c9ee9a2e-1852-46c4-b191-338cdca9b53a.png">

**Comment by thedoublejay** [comment]
fixed on latest build
