### ISSUE TITLE
Calculation for AT RISK is 1.25x - 1.5x

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1421]
#### What happened:
The calculation for `AT RISK` is now is displayed as `1x-1.5x `

#### What you expected to happen:

The calculation for `AT RISK` should be displayed as `1.25x - 1.5x`

#### How to reproduce it (as minimally and precisely as possible):

Loans > click `Create Vault` (if no vault present) / `+ ` > Learn more about vaults

#### Anything else we need to know?:
No

<img width="338" alt="Screenshot 2021-11-24 at 2 48 58 PM" src="https://user-images.githubusercontent.com/32018980/143209962-e290f33f-0d4b-4a1d-b572-6edb66bd682c.png">

**Comment by thedoublejay** [comment]
invalid bug
