### ISSUE TITLE
Health badge seems wrong on resulting col. ratio 437.5. It should be yellow

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1429]
#### What happened:
For collateralization ratio `483.09` the Health Badge is not in Yellow colour

#### What you expected to happen:
For collateralization ratio `483.09` the Health Badge should be in `Yellow colour`

#### How to reproduce it (as minimally and precisely as possible):
Loans > Create Vault > Add Collateral > Vault details page > Loan section > Borrow Loan (Take care the collateral ratio is 483.09)

#### Anything else we need to know?:
No

<img width="336" alt="Screenshot 2021-11-24 at 3 23 18 PM" src="https://user-images.githubusercontent.com/32018980/143215573-a19288ea-1a93-4235-a051-2fb93f4e6733.png">

**Comment by thedoublejay** [comment]
Fixed on latest build
