### ISSUE TITLE
AT RISK should be displayed in Red background

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1431]
#### What happened:
`AT RISK` not in `Red` background

#### What you expected to happen:
`AT RISK` should be in `Red` background

#### How to reproduce it (as minimally and precisely as possible):
Loans > Create Vault > Vault Detail Page > Loans section > `BORROW LOAN TOKEN` > Enter very less amount w.r.t collateral

#### Anything else we need to know?:

<img width="164" alt="Screenshot 2021-11-24 at 3 35 08 PM" src="https://user-images.githubusercontent.com/32018980/143217543-a5e0ad90-93d6-44a5-8883-b35c3e25e95c.png">

**Comment by thedoublejay** [comment]
Fixed on latest build
