### ISSUE TITLE
APR hidden behind + ADD MORE (edited) - German

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1432]
#### What happened:
APR hidden behind + ADD MORE
Your pooled {{token}} translation error

#### What you expected to happen:
APR should be visible

#### How to reproduce it (as minimally and precisely as possible):
Add Liquidity — Your pool pairs screen

#### Anything else we need to know?:
No

<img width="340" alt="Screenshot 2021-11-24 at 3 47 07 PM" src="https://user-images.githubusercontent.com/32018980/143219482-ce8ff6f7-70f9-439f-b142-43ac9ee27c23.png">
<img width="334" alt="Screenshot 2021-11-24 at 3 47 23 PM" src="https://user-images.githubusercontent.com/32018980/143219525-825305fc-f913-44fe-8645-caf8d653e596.png">

**Comment by thedoublejay** [comment]
Will be fixed on next build
