### ISSUE TITLE
New vault, no collateral,  collateralization ratio should not be colour-coded

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1436]
#### What happened:
New vault, no collateral,  collateralization ratio is colour-coded

#### What you expected to happen:
New vault, no collateral,  collateralization ratio should not be colour-coded

#### How to reproduce it (as minimally and precisely as possible):
Loans > Create Vault > Edit Collateral

#### Anything else we need to know?:
No

<img width="172" alt="Screenshot 2021-11-24 at 4 02 23 PM" src="https://user-images.githubusercontent.com/32018980/143221986-e93952ce-b81d-4ced-bac2-3ece4ebb61f1.png">

**Comment by izzycsy** [comment]
Acceptance Criteria: New vault with no collateral, `Col ratio` should not be color-coded

Android: 
- [ ] Loans > `CREATE VAULT` > Check `Col ratio` colour

iOS: 
- [ ] Loans > `CREATE VAULT` > Check `Col ratio` colour
