### ISSUE TITLE
 No collaterals section and ADD COLLATERALS buttons missing translation  - German

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1446]
#### What happened:
` No collaterals` section and `ADD COLLATERALS` button missing translation on Vault Detail page

#### What you expected to happen:
` No collaterals` section and `ADD COLLATERALS` button missing translation on Vault Detail page

#### How to reproduce it (as minimally and precisely as possible):
Loan > Create Vault > Your Vaults > Vault Detail > Collateral section

#### Anything else we need to know?:
No

<img width="262" alt="Screenshot 2021-11-24 at 5 36 54 PM" src="https://user-images.githubusercontent.com/32018980/143235477-1780b6f1-8d29-4098-b893-d5094c616dc2.png">

**Comment by thedoublejay** [comment]
Fixed on latest build
