### ISSUE TITLE
GEFÄHRDET (AT RISK) label is cut off - German

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1449]
#### What happened:
GEFÄHRDET (AT RISK) label is cut off

#### What you expected to happen:
 Maybe align i icon with Resultierende & 0.80%, the current position bec of the long german translation makes it float in a awkward position

#### How to reproduce it (as minimally and precisely as possible):
Loans — Borrow Loan Token — Transaction Details

#### Anything else we need to know?:

<img width="343" alt="Screenshot 2021-11-24 at 5 57 32 PM" src="https://user-images.githubusercontent.com/32018980/143238316-358d2645-77e4-4aa2-a78d-ca67777d1942.png">

**Comment by thedoublejay** [comment]
fixed on latest build
