### ISSUE TITLE
Collateralization Ratio should be changed to Resulting Collateralization Ratio to provide feedback on the loan payment

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1451]
#### What would you like to be added:
The `Collateralization Ratio` should be changed to `Resulting Collateralization Ratio` to provide feedback on the loan payment.

#### Why is this needed:
For better user understanding.

#### Steps to reproduce:
Loans > Your Vault > Vault ID > Loan > Payback Loan 

<img width="184" alt="Screenshot 2021-11-24 at 6 13 58 PM" src="https://user-images.githubusercontent.com/32018980/143240768-9b8a4879-3870-4c5a-8d2e-1569252a0bd3.png">

**Comment by kyleleow** [comment]
I think we should keep this but add another `Transaction Results` section below with `Resulting collateralization` value just like in `Confirm Borrow Loan Token` screen

![image](https://user-images.githubusercontent.com/40191153/143422097-45895f46-1daf-4ca2-b739-6a11306967e6.png)

**Comment by kyleleow** [comment]
Should we add the resulting collateralization ratio in both `Payback Loan` screen and the `Confirm Loan Payment` screen?
So user is informed up front when they input their amount to payback?
cc: @jtlntno-cake

**Comment by jtlntno-cake** [comment]
@kyleleow There's an updated iteration for the flow of loan payments. Please see this [link](https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?page-id=3985%3A62946&node-id=6560%3A168816&viewport=241%2C48%2C0.76&scaling=scale-down&starting-point-node-id=6560%3A168816&show-proto-sidebar=1)

This is in line with what you mentioned with presenting the resulting collateralization at the forefront upon input

Take note that this will only affect loan payment for now - will revisit the borrow loan flow soon as well
