### ISSUE TITLE
`FAQ` - Ability to open a specific drawer topic

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1452]
#### What would you like to be added:
When redirecting to FAQ pages, we should be allowed to open a specific category by default.

**Comment by izzycsy** [comment]
Acceptance Criteria: User to be able to specify which category which topic they want to know more about

Android: 
- [ ] `Settings` > `About` > `Knowledge base` >

iOS: 
- [ ] `Settings` > `About` > `Knowledge base` >
