### ISSUE TITLE
`send` - updated design

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1465]
#### What would you like to be added:
Updated send flow that allows user to select tokens. It would use the same component as Composite Swap.

- [ ] Token Selection list
- [ ] Add Send button on BalanceControlList

![image](https://user-images.githubusercontent.com/25013382/143515684-f8dcd6ed-1f84-4957-9e87-769f7ef8f7c0.png)

![image](https://user-images.githubusercontent.com/25013382/143516074-75febff0-715b-49b0-9546-c366dd925ceb.png)

**Comment by dwivedinalin** [comment]
Acceptance Criteria: User should be able to select token and Send 

**Android:**

- [ ] Balances > Portfolio section `(Up arrow) `> `Select token`  > Enter address  > enter amount > continue 
- [ ] Balances > Portfolio section `(Up arrow) ` > `Select token` > Scan QR  > enter amount > continue

**iOS:** 

- [ ] Balances > Portfolio section `(Up arrow) `> `Select token`  > Enter address  > enter amount > continue
- [ ] Balances > Portfolio section `(Up arrow) ` > `Select token` > Scan QR  > enter amount > continue

> Verify at the recipient address the sent amount is received.
