### ISSUE TITLE
`dex skeleton loader` - improve UI

### ISSUE THREAD

**Issue by kyleleow** [DeFiCh/wallet#1474]
#### What UI/UX improvements would you like to be implemented: 
- To improve dex skeleton loader

#### Why is this needed:
- Currently looks cropped on the right on android

#### Which component/screens does this concern?:
- DEX screen

#### Anything else we need to know?:
![image](https://user-images.githubusercontent.com/40191153/143570213-df7c7a0f-57d0-4dc3-af17-77ee4758ff27.png)

**Comment by izzycsy** [comment]
Acceptance Criteria: Gutter space to be even for bottom navigation icon

Android: 
- [ ] Click `Balances`, `DEX`, `Loans`, `Auctions`, `Transactions` > check gutter spacing


iOS:
- [ ] Click `Balances`, `DEX`, `Loans`, `Auctions`, `Transactions` > check gutter spacing

**Comment by izzycsy** [comment]
![IMG_4055](https://user-images.githubusercontent.com/65014479/145035025-8e96f694-47b1-4c9e-a3ca-42f170693d96.jpeg)

@kyleleow all the pop up modals have the same uneven space.

**Comment by kyleleow** [comment]
@izzycsy yep saw it last time, that is tracked in a separate [ticket](https://github.com/DeFiCh/wallet/issues/1117)
