### ISSUE TITLE
`DEX` - favorite pair card

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1498]
#### What would you like to be added:
Currently, we already have a long list of pairs in the DEX page. It would be nice to have a favorite or pin system that moves the user's preferred pair on the top most part.

As a first iteration, let's add a `star` button on the upper right. Clicking on it will always pin the pair at the top most. The rest will be sorted as is.

**Comment by kyleleow** [comment]
@thedoublejay Favourite function will only applied to poolpairs under `Browse pool pairs` and not `Your pool pairs` correct?

**Comment by thedoublejay** [comment]
Yes @kyleleow

**Comment by jtlntno-cake** [comment]
Sharing links here for design and prototype for adding favorite pairs in DEX

[See here for prototype](https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?page-id=3985%3A62946&node-id=6496%3A133798&viewport=241%2C48%2C0.51&scaling=scale-down&starting-point-node-id=6496%3A133798)

[See here for the card designs](https://www.figma.com/file/CMoIqpPpzeJTLumlwZNyz8/DSGN---Light-Wallet---Design-System?node-id=1166%3A14215)

[See here for the related screens](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=6496%3A133796)
