### ISSUE TITLE
`balances` - display portfolio value and token breakdown

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1499]
#### What would you like to be added:
We want to display total portfolio value on the balances page, along with total dollar amount per token. 

Use DEX price. For liquidity tokens, we just breakdown and calculate from DEX price. 

Prices should update per block

**Comment by jtlntno-cake** [comment]
Here's an updated design to reflect the USD values and the total portfolio value
![image](https://user-images.githubusercontent.com/85162376/148216259-4444684c-bc28-4047-950c-e4c3482be271.png)

[Figma link](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=5942%3A88558)
