### ISSUE TITLE
`announcements` - clickable links

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1502]
#### What would you like to be added:
For our announcements banners, make it "clickable" when there's a URL present on the announcement item.  Add a caret when the banner is clickable
#### Why is this needed:
If we put a message that, "an update is needed", it should be able to redirect to app stores.

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:** Announcement  clickable links to be added on top Balances

**Android:**
- [ ]  Balances > Check clickable link on Top for new build release

**iOS:**
- [ ]  Balances > Check clickable link on Top for new build release
 

> Whenever a new build is published an announcement link should be displayed on the top of Balances
