### ISSUE TITLE
`Android`: If QR code is scanned iteratively it stops fetching wallet address

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1511]
#### What happened:
**Android:**
version: 0.15.1
• QR scan stops fetching wallet address from second scan onwards

#### What you expected to happen:
• QR scan should fetch wallet address regardless of attempts

#### How to reproduce it (as minimally and precisely as possible):
• Balance > Up arrow in Portfolio card > Click QR scan  

#### Anything else we need to know?:
No

**Comment by kyleleow** [comment]
only happens on android, works on ios
