### ISSUE TITLE
Iterating `Wallet` Onboarding UI/UX

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#152]
#### What would you like to be added:

The current `Mnemonic Wallet` https://github.com/DeFiCh/wallet/pull/124 was merged into `main` so that we do not block other implementation progress for better velocity. The implementation was iterated on by the engineers as there some technical differences that require a few changes. This is the only set of screens that were largely incompatible with what was designed, while for the rest it's unlikely that we will do such a drastic change.

However, as the implementation was more geared towards technical reconciliation reasons, we need to iterate on this heavily. 

Summary of changes, read #124 for more details.
Screen | Changes
---|---
Wallets Onboarding | You can only create one wallet in your app, labeling the wallet doesn't help now. We might enable multiple wallets in the future but not anytime soon.
Create Mnemonic Wallet | Zig zag layout to a more linear for better traversing of content/words.
Create Mnemonic Wallet Verification | Every single word must be verified, leaving any word unverified is not worth the risk.
Restore Mnemonic Wallet | There is no good reason why I changed this other than to reduce complexity on my end.

Lastly, we also need a new set of copy, new onboarding sequence/experience. A wallet creation onboarding screen (so that users know we are a noncustodial wallet, no one can help you if you lose your mnemonic phrase). 

/triage accepted
/assign @jtlntno-cake please coordinate this, you need to create and branch off issue discussing changes and creating the narrative for change.
/priority important-soon

**Comment by jtlntno-cake** [comment]
@fuxingloh I created this new onboarding flow on mid-fidelity with much considerations on the UX copy, page flows and the above comments. 

Please see this link for better view:
https://whimsical.com/light-wallet-onboarding-iteration-HHsUYWsDDwWnLiiSfHfZN7 
(no added password)

A few notes:
1. I maintained the same flow but tinkered heavily on how we display the critical information
2. I've added some modals as feedback for the users to contextually provide support.
3. Screens and flow are designed in mid-fidelity. Once we aligned on this iteration, I can proceed in providing any required assets/components as needed by the team.
