### ISSUE TITLE
Weird Collateral Quote of -700.000,00% when only small fraction of loan is open

### ISSUE THREAD

**Issue by muirglacier** [DeFiCh/wallet#1524]
See pic … 
Paid back loan, but in the mean time a little bit of interest accrued! With the minimal amount of DUSD remaining, the quote calculation went horribly wrong

![BFD660DA-2689-492E-9D08-EF277DE49C6A](https://user-images.githubusercontent.com/69924699/144435102-f05a10c0-893d-41c5-9884-05eb308c9bb2.png)

**Comment by thedoublejay** [comment]
Hi, this might be due to fluctuations on interest rates while the payment has not been made. This is solved on `0.21.0` where you are allowed to overpay a bit to make sure everything is covered. Excess payment will be returned to your wallet.
