### ISSUE TITLE
DUSD Liquidity pool extra letter d displayed

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1526]
#### What happened:
Wrong name displayed for `DUSD` Liquidity pool `dDUSD` displayed

#### What you expected to happen:
Should be `DUSD` 

#### How to reproduce it (as minimally and precisely as possible):
Balance > `DUSD` >  Add to liquidity pool > Add Liquidity

#### Anything else we need to know?:
No

<img width="337" alt="Screenshot 2021-12-03 at 10 58 10 AM" src="https://user-images.githubusercontent.com/32018980/144550393-5ec77d50-9b57-44a4-863d-28eff7e9fa1c.png">

**Comment by thedoublejay** [comment]
will be fixed with https://github.com/DeFiCh/whale/pull/639
