### ISSUE TITLE
`ZHS/ZHT` - missing translation

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#1533]
#### What translation improvements would you like to be implemented:
• Missing translation for ZHS/ZHT

#### Which component/screens does this concern?:
 **Balances > DFI > `Swap` > Convert DFI**
**ZHT:**
```
You will have = 你將會收到 
TRANSACTION DETAILS = 交易詳情 
```
**ZHS:**
```
You will have = 你将会收到 
TRANSACTION DETAILS = 交易详情 
```
![211203 v0 17 5 - iOS:Android - Balances - Convert DFI - Missing ZH1](https://user-images.githubusercontent.com/65014479/144559794-a8248966-2a52-4ff9-8abd-219f5d350165.jpg)

**Balances > Send**
• `dUSDT` icon incorrect

**ZHT:**
```
TRANSACTION DETAILS = 交易詳情
```

**ZHS:**
```
TRANSACTION DETAILS = 交易详情
```
![211203 v0 17 5 - iOS:Android - Balances - Send - Missing ZH1](https://user-images.githubusercontent.com/65014479/144560271-622c5f9c-0145-402c-90e4-b13e95fff3ab.jpeg)

**Balances > Send > `CONTINUE`**
**ZHT:**
```
Transaction type = 交易類型
Amount to send = 發送金額
```

**ZHS:**
```
Transaction type = 交易类型
Amount to send = 发送金额
```

![211203 v0 17 5 - iOS:Android - Balances - Send - Continue - Missing ZH1](https://user-images.githubusercontent.com/65014479/145352201-de9b917c-77d7-4f72-8f91-5edf016d22d3.jpeg)

**Transactions**
**ZHT:**
```
Received = 收到
Send = 發送
```

**ZHS:**
```
Received = 收到
Send = 发送
```
![211203 v0 17 5 - iOS:Android - Tx - Missing ZH1](https://user-images.githubusercontent.com/65014479/144562615-2db7750f-3660-4637-8546-d9bda02d030e.jpg)

**Loans > Your vaults**
**ZHT:**
```
Total collateral (USD) = 總抵押品 (美元）
MANAGE LOANS button = 管理借貸按鈕
EDIT COLLATERALS button = 編輯抵押品按鈕
```

**ZHS:**
```
Total collateral (USD) = 总抵押品 (美元)
MANAGE LOANS button = 管理借贷按钮
EDIT COLLATERALS button = 编辑抵押品按钮
```
![211203 v0 17 5 - iOS:Android - Loans - Your vaults - Missing ZH1](https://user-images.githubusercontent.com/65014479/144564265-0ade10bc-6abf-4027-8859-6994c19de0b1.PNG)

**Loans > Your vaults > Select active `Vault`**
**ZHT:**
```
Total collateral (USD) = 總抵押 (美元)
Total loans (USD) = 借貸總 (美元)
Vault interest (APR) = 金庫利息
EDIT COLLATERALS button = 更改 抵押 按鈕
EDIT LOAN SCHEME button = 更改借貸 計劃按鈕 
Collateral amount = 抵押金額
```

**ZHS:**
```
Total collateral (USD) = 总抵押 (美元)
Total loans (USD) = 借贷总额 (美元)
Vault interest (APR) = 金库利息
EDIT COLLATERALS button = 更改 抵押 按钮
EDIT LOAN SCHEME button = 更改借贷 计划按钮 
Collateral amount = 抵押金额
```
![211203 v0 17 5 - iOS:Android - Loans - Your vaults - Vault 1 - Missing ZH1](https://user-images.githubusercontent.com/65014479/144564454-42252bb8-8bfd-45cd-8adf-9db8f10ebd30.PNG)

**Loans > Your vaults > Select active `Vault` > EDIT COLLATERALS**

```
Edit Collaterals = 
Total loans (USD) = 
Collateralization ratio = 
Min. collateralization ratio = 
Vault interest (APR) = 
```
> For consistency, change English: Vault interest = Vault interest (APR)
![211203 v0 17 5 - iOS:Android - Loans - Your vaults - Vault 1 - EDIT COL -  Missing ZH1](https://user-images.githubusercontent.com/65014479/144570474-f539423c-2c4b-4234-8b25-46d36d10d8f2.PNG)

**Loans > Your vaults > Select active `Vault` > EDIT COLLATERALS > `+`**
**ZHT:**
```
The collateral factor determines the degree of contribution of each collateral token = 抵押系數決定了每個抵押代幣的貢獻程度。
```

**ZHS:**
```
The collateral factor determines the degree of contribution of each collateral token = 抵押系数决定了每个抵押代币的贡献程度。
```
![211203 v0 17 5 - iOS:Android - Loans - Your vaults - Vault 1 - EDIT COL - + - Missing ZH1](https://user-images.githubusercontent.com/65014479/144567012-6ad14ecb-1745-4628-87f5-235187909fe6.jpg)

**Loans > Your vaults > Select active `Vault` > EDIT COLLATERALS > `–`**
**ZHT:**
```
The collateral factor determines the degree of contribution of each collateral token = 抵押系數決定了每個抵押代幣的貢獻程度。
```

**ZHS:**
```
The collateral factor determines the degree of contribution of each collateral token = 抵押系数决定了每个抵押代币的贡献程度。
```
![211203 v0 17 5 - iOS:Android - Loans - Your vaults - Vault 1 - EDIT COL - – - Missing ZH1](https://user-images.githubusercontent.com/65014479/144566967-1a5a648b-ce39-45f9-984c-65b433415664.jpg)

**Loans > Your vaults > Select active `Vault` > EDIT LOAN SCHEME**
**ZHT:**
```
Edit Loan Scheme = 更改貸款計劃
Total loans (USD) = 貸款總額 (美元)
Collateralization ratio = 抵押率
Min. collateralization ratio = 最低抵押率
```
**ZHS:**
```
Edit Loan Scheme = 更改贷款计划
Total loans (USD) = 贷款总额 (美元)
Collateralization ratio = 抵押率
Min. collateralization ratio = 最低抵押率
```

![211203 v0 17 5 - iOS:Android - Loans - Your vaults - Vault 1 - EDIT LOAN SCHEME - Missing ZH1](https://user-images.githubusercontent.com/65014479/144567795-c547e24b-ea03-4fc9-bf69-bd4e52005b47.jpg)

**Loans > Your vaults > Select active `Vault` > `Details` tab**
**ZHT:**
```
Total collateral (USD) = 總抵押品 (美元)
```

**ZHS:**
```
Total collateral (USD) = 总抵押品 (美元)
```
![211203 v0 17 5 - iOS:Android - Loans - Your vaults - Vault 1 - Details - Missing ZH1](https://user-images.githubusercontent.com/65014479/144568541-a6d54e38-ced1-45b5-9b64-d4a6e38555f1.jpg)

**Loans > Your vaults > Select active `Vault` > `Loans` tab > `BROWSE LOAN TOKENS` button**
**ZHT:**
```
Choose Loan Token to Borrow = 選擇借貸代幣種類
```

**ZHS:**
```
Choose Loan Token to Borrow = 选择借贷代币种类
```
![211203 v0 17 5 - iOS:Android - Loans - Your vaults - Vault 1 - Loans - Browse loan tokens - Missing ZH1](https://user-images.githubusercontent.com/65014479/144570819-ad1c69fc-d71b-48a2-a197-15ce93c4579a.PNG)

#### Anything else we need to know?:

**Comment by thedoublejay** [comment]
@izzycsy you can also add the correct ZH translations here for reference
