### ISSUE TITLE
Close to Liquadation, although I gave back my dTokens

### ISSUE THREAD

**Issue by defichainislove** [DeFiCh/wallet#1542]
I write this for a guy from telegram.

He gave back his loan and nevertheless the vault showed a "Gefährdet" (=in danger close to liquidation).

Is this just a display error?
Or could have been it, that his collateral would have gone in liquidation even if he did pay back his loans?
You can see it in the picture.
 
![IMG_20211203_172117_023](https://user-images.githubusercontent.com/77920440/144637293-e10ed774-293f-4aa4-9d71-fbca255f0c86.jpg)

Wouldn't be that well if it's a bug 😅

Thanks

**Comment by SacWheeler** [comment]
I run into the same issue after paying back the loan almost entirely (0.00000374@AAPL left).
collateralization ratio is in the + 1'000'000%.

**Comment by SacWheeler** [comment]
got resolved after paying back the small fraction of the loan (0.00000374@AAP)

**Comment by thedoublejay** [comment]
Hi @defichainislove @SacWheeler, we will be checking on this issue. Our initial investigation is it might be linked to a very small amount of loans. For now, you can try to payback this very small amount, but we will check on our end also.

**Comment by thedoublejay** [comment]
Hi, this might be due to fluctuations on interest rates while the payment has not been made. This is solved on `0.21.0` where you are allowed to overpay a bit to make sure everything is covered. Excess payment will be returned to your wallet.
