### ISSUE TITLE
payback loan - Loan cannot be repaid in full

### ISSUE THREAD

**Issue by sandstumpen** [DeFiCh/wallet#1543]
#### What happened:
When repaying a GME loan, there is always a small amount outstanding.

#### What you expected to happen:
I have repaid the full loan amount and expect the position to disappear.

#### How to reproduce it (as minimally and precisely as possible):
1. i have created a loan
2. I minted several stock tokens and DUSD
3. I have repaid one stock token (GME) in full.
4. after that, the GME position is still there and the amount grows again. e.g. 0.00000025

#### Anything else we need to know?:
How can I close this position completely?

**Comment by sandstumpen** [comment]
/area/loans

**Comment by thedoublejay** [comment]
@sandstumpen Might be linked to this issue also - https://github.com/DeFiCh/wallet/issues/1542 We are currently investigating

**Comment by thedoublejay** [comment]
Hi, this might be due to fluctuations on interest rates while the payment has not been made. This is solved on 0.21.0 where you are allowed to overpay a bit to make sure everything is covered. Excess payment will be returned to your wallet.
