### ISSUE TITLE
`take loan` - conversion should be utxo to account

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1544]
#### What happened:
In the borrow loan page, it requires 0.1 UTXO to do conversion. The conversion must be from utxo to account.

**Comment by izzycsy** [comment]
Acceptance Criteria: pre-requisite to set balance to 0.1 DFI (UTXO), upon taking loan conversion should not be required

Android: Borrow with 0.1 DFI (UTXO) balance
- [ ] Loans > On vault card select `MANAGE LOANS` > `BORROW MORE` > Enter amount to borrow 
- [ ] Loans > `Browse loan tokens` > select `DUSD` > Select vault > Enter amount to borrow 

iOS: Borrow with 0.1 DFI (UTXO) balance
- [ ] Loans > On vault card select `MANAGE LOANS` > `BORROW MORE` > Enter amount to borrow 
- [ ] Loans > `Browse loan tokens` > select `DUSD` > Select vault > Enter amount to borrow
