### ISSUE TITLE
`edit collateral` - incorrect vault share on confirm collateral page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1546]
#### What happened:
Wrong info displayed for vault share in confirm collateral page. Doesn't take account existing tokens.

- [ ] Add Collateral from Add Token button
- [ ] Add additional from Collateral Card
- [ ] Remove collateral

**Comment by izzycsy** [comment]
Acceptance Criteria: Verify Vault (%) is correct

Android: 
- [ ] Loans > Select vault > `EDIT COLLATERALS` > under **COLLATERALS** select `+` > Enter an amount > `ADD TOKEN AS COLLATERAL` > Check Vault %


iOS: 
- [ ] Loans > Select vault > `EDIT COLLATERALS` > under **COLLATERALS** select `+` > Enter an amount > `ADD TOKEN AS COLLATERAL` > Check Vault %
