### ISSUE TITLE
`auctions` - count display on bottom tab navigator

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1547]
#### What would you like to be added:
![image](https://user-images.githubusercontent.com/25013382/144774538-ba2a088a-e1eb-4cf3-8c75-ff976c5b641d.png)

**Comment by izzycsy** [comment]
Acceptance Criteria: Auction count display 

Android: 
- [ ] Balances > Auction count should display
- [ ] DEX > Auction count should display
- [ ] Loans > Auction count should display
- [ ] Transactions > Auction count should display

iOS: 
- [ ] Balances > Auction count should display
- [ ] DEX > Auction count should display
- [ ] Loans > Auction count should display
- [ ] Transactions > Auction count should display

**Comment by izzycsy** [comment]
Auction
> When counter goes to 3 digits, it’s not in the center of red oval

Expected: 
• `Number count` displayed should be centralized

![211203 v0 17 5 - iOS:Android - Auctions - Not center of circle](https://user-images.githubusercontent.com/65014479/144824183-4a604c2d-0da9-44b2-abae-86997f9d966b.jpeg)

**Comment by izzycsy** [comment]
Issue created: https://github.com/DeFiCh/wallet/issues/1580
