### ISSUE TITLE
`vault health` - update status

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1551]
#### What would you like to be added:

Update vault health status.
1. Labels will be used to convey the status of the vault
-   Empty: No collateral, no loan taken
-   Ready for loan: Added collateral, no loan taken
-   Active: With collateral and loan
-   Only vaults in this state will have health bars
-   In Liquidation
-   Halted: Frozen vaults

2. Vault health bar will be used to convey relationship between collateralization and min col ratio
Follows current logic of green, yellow, red
Only Vaults with Active label will display a health bar on the wallet. Vaults with Active label will display an abbreviated health signal on Scan (see screenshot)

![image (3)](https://user-images.githubusercontent.com/25013382/144942425-85dde1ef-75d0-41d4-b73b-abaf469723bf.png)

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:** Verify whether vaults labels and health bar are as per Loan, collateral value

**Android:**

- [ ] Loans > Create Vault > Verify Empty label 
- [ ] Loans > Create Vault >  `EDIT COLLATERALS` > `ADD TOKEN AS COLLATERAL`
- [ ] Loans > Create Vault > `EDIT COLLATERALS` > `ADD TOKEN AS COLLATERAL` > `Loans` > `BORROW LOAN TOKENS`
- [ ] Loans > Check vault whose collaterization ratio  is less than min. collaterization ratio
- [ ] Loans > Your Vaults > Verify only `ACTIVE` labels are with health bar 

**iOS:**

- [ ] Loans > Create Vault > Verify Empty label 
- [ ] Loans > Create Vault >  `EDIT COLLATERALS` > `ADD TOKEN AS COLLATERAL`
- [ ] Loans > Create Vault > `EDIT COLLATERALS` > `ADD TOKEN AS COLLATERAL` > `Loans` > `BORROW LOAN TOKENS`
- [ ] Loans > Check vault whose collaterization ratio  is less than min. collaterization ratio
- [ ] Loans > Your Vaults > Verify only `ACTIVE` labels are with health bar 

> Verify the health badge and bar with above designs
