### ISSUE TITLE
Wrong swap with token name displayed in token details screen

### ISSUE THREAD

**Issue by fullstackninja864** [DeFiCh/wallet#1562]
#### What happened:
<img src="https://user-images.githubusercontent.com/53080940/144794596-aa1745d8-ca15-4c50-ad14-6293092fc6ee.jpg" width="50%"/>

**Comment by izzycsy** [comment]
Acceptance Criteria: dTokens swap should be DUSD not DFI

Android: 
- [ ] Balances > dTSLA > `Swap with DUSD` > From `dTSLA` to `DUSD`
- [ ] Balances > dGME > `Swap with DUSD` > From `dGME` to `DUSD`
- [ ] Balances > dGOOGL > `Swap with DUSD` > From `dGOOGL` to `DUSD`
- [ ] Balances > dBABA > `Swap with DUSD` > From `dBABA` to `DUSD`
- [ ] Balances > dPLTR > `Swap with DUSD` > From `dPLTR` to `DUSD`
- [ ] Balances > dAPPL > `Swap with DUSD` > From `dAPPL` to `DUSD`
- [ ] Balances > dSPY > `Swap with DUSD` > From `dSPY` to `DUSD`
- [ ] Balances > dQQQ > `Swap with DUSD` > From `dQQQ` to `DUSD`
- [ ] Balances > dPDBC > `Swap with DUSD` > From `dPDBC` to `DUSD`
- [ ] Balances > dVNQ > `Swap with DUSD` > From `dVNQ` to `DUSD`
- [ ] Balances > dARKK > `Swap with DUSD` > From `dARKK` to `DUSD`
- [ ] Balances > dGLD > `Swap with DUSD` > From `dGLD` to `DUSD`
- [ ] Balances > dURTH > `Swap with DUSD` > From `dURTH` to `DUSD`
- [ ] Balances > dTLT > `Swap with DUSD` > From `dTLT` to `DUSD`
- [ ] Balances > dSLV > `Swap with DUSD` > From `dSLV` to `DUSD`
