### ISSUE TITLE
Update Min. Next Bid Tooltip Content

### ISSUE THREAD

**Issue by ngyingzhong** [DeFiCh/wallet#1565]
#### What UI/UX improvements would you like to be implemented: 

Update content for Min. next bid tool tip to:

EN
```
The minimum bid a user must place in order to take part in the auction.
```

ZHT
```
用戶參與拍賣必須提交的最低標價。
```

ZHS
```
用户参与拍卖必须提交的最低标价。
```

DE:
```
Das Mindestgebot, das ein Nutzer abgeben muss, um an der Auktion teilnehmen zu können.
```

#### Why is this needed:

Edited for clarity

#### Which component/screens does this concern?:

![image](https://user-images.githubusercontent.com/66629826/144795782-a4a2d4ac-ca09-4ebe-ae5c-7912242d8d37.png)

**Comment by izzycsy** [comment]
![211206 v0 18 8 - iOS:Android - Auctions - Min  next bid content extra period](https://user-images.githubusercontent.com/65014479/144881130-5aba6398-f6cd-4c8c-b886-29fce863e7ac.jpg)

Android / iOS: 
> Actual: 
> Auctions > select a vault > QUICK BID > at Min. next bid, select i > check content > extra `.` present

Expected: 
• Only 1 `.` to end sentence 

Which component/screens does this concern?:
**EN, DE**
Auctions > select a vault > Auction details > `QUICK BID` >  Min. next bid, select `i`

**Comment by izzycsy** [comment]
![211207 v0 18 8 - iOS:Android - Auctions - Min  next bid content missing translatn](https://user-images.githubusercontent.com/65014479/144882964-4a69c688-8ded-4a32-9e75-43307baf5288.jpg)


Android / iOS:
Actual:
> Auctions > select a vault > QUICK BID > at Min. next bid, select `i` > check content > Min. next bid content not translated
> Auctions > select a vault > **Auction details** not translated 

Expected:
• To be in ZHS / ZHT respectively

Which component/screens does this concern?:
**ZHS, ZHT**
1. Auctions > select a vault > **Auction details**
2. Auctions > select a vault > Auction details > QUICK BID > Min. next bid, select `i`
