### ISSUE TITLE
`place bid` - add warning if the bid is more than the original value

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1567]
#### What would you like to be added:
The goal would be to have a security warning for users to prevent over bidding. Example, if a user accidentally clicks on a 1 DFI auction card and bid 200 DUSD, we don't have a warning message to inform them. This would show an info message when the bid amount is 120% more.

**Comment by jtlntno-cake** [comment]
![image](https://user-images.githubusercontent.com/85162376/144806734-c69ffa81-5a18-481a-a915-21be25e4b011.png)

Add a warning message whenever a user is placing a bid (USD Value) that is higher than the total auction value. 
cc: @thedoublejay @ngyingzhong 

Screen can be seen [here](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=5942%3A89371)

**Comment by thedoublejay** [comment]
@fullstackninja864 display this error message if bid is more than 120%

**Comment by izzycsy** [comment]
Acceptance Criteria: If bid is higher than original value, `i` should appear to inform user of over stated value

Android: 
- [ ] Auctions > directly on vault `PLACE BID` > enter amount higher than **Total auction value (USD)** > check warning
- [ ] Auctions > select vault > `PLACE BID` > enter amount higher than **Total auction value (USD)** > check warning

iOS: 
- [ ] Auctions > directly on vault `PLACE BID` > enter amount higher than **Total auction value (USD)** > check warning
- [ ] Auctions > select vault > `PLACE BID` > enter amount higher than **Total auction value (USD)** > check warning
