### ISSUE TITLE
Auctions - Add search bar filtering with loan token

### ISSUE THREAD

**Issue by pierregee** [DeFiCh/wallet#1568]
#### What would you like to be added:
- Add a search bar in Auctions page to filter by loan token
![image](https://user-images.githubusercontent.com/13292662/144811793-30fa9eba-b66b-4f43-a2c7-6c5e01f66272.png)

**Comment by izzycsy** [comment]
Acceptance Criteria: User able to filter via **search bar**

Android: 
- [ ] Auctions > `search icon` > enter any dToken to search
- [ ] Auctions > copy Vault ID `search icon` > paste Vault ID to search


iOS:
- [ ] Auctions > `search icon` > enter any dToken to search
- [ ] Auctions > copy Vault ID `search icon` > paste Vault ID to search
