### ISSUE TITLE
`transactions` - Filter page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#157]
#### What would you like to be added:
Filter tokens on the transaction page. 
#### Why is this needed:

- [ ] Filter Token
- [ ] Include rewards

![image](https://user-images.githubusercontent.com/25013382/122027337-a09d1080-cdfd-11eb-8b97-3daa84b77acc.png)

**Comment by fuxingloh** [comment]
We don't need a filter page, don't plan to support it either. We need to create another index to index this data, not worth the time.

**Comment by thedoublejay** [comment]
Ok so do we show rewards by default?

**Comment by fuxingloh** [comment]
not doing
