### ISSUE TITLE
`passcode change` - crashing after change of passcode

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1571]
#### What happened:

Thank you. Here a few details. We could fix the problem with a workaround.

He was able to reproduce this error on the Lightwallet and repair it in the same way.
Fixed by following:
The user has now completely deleted all data in the app de-installed and re-installed and entered again new seed to recover the wallet and set a new password.
Everything works now.

"What still needs to be mentioned, the error probably only comes when you have changed the password and then enter the wrong password for the first time during the next action where the password is requested. Then comes the error message that you only have 2 attempts But if you then enter the correct password, then the app smears. The whole thing happens on a HUAWEI P2 Android 9.1.0 "

**Comment by thedoublejay** [comment]
@izzycsy @dwivedinalin can you try to reproduce this?

**Comment by izzycsy** [comment]
Acceptance Criteria: Able to change passcode on 2nd attempt

Android: 
- [ ] Settings > change passcode > enter wrong passcode (1st attempt) > enter correct passcode (2nd attempt) > change passcode


iOS: 
- [ ] Settings > change passcode > enter wrong passcode (1st attempt) > enter correct passcode (2nd attempt) > change passcode
