### ISSUE TITLE
`auction card` - display if it's your vault and if there's no bid yet

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1576]
#### What would you like to be added:
1. If this auction batch is from your vault, display from your vault.
2. If this auction batch doesn't have a bid yet, display the waiting for first bid

![image (2)](https://user-images.githubusercontent.com/25013382/144827297-9232e7c9-6645-4a19-ab7b-fb8003076ff0.png)

**Comment by izzycsy** [comment]
Acceptance Criteria: Display either user's own vault and/or another vault that is waiting for first bid.

Android: 
- [ ] Auction > if auction batch is from your own vault > display `From your vault`
- [ ] Auctions > if auction batch doesn't have a bid yet, display `Waiting for first bid`


iOS:
- [ ] Auction > if auction batch is from your own vault > display `From your vault`
- [ ] Auctions > if auction batch doesn't have a bid yet, display `Waiting for first bid`
