### ISSUE TITLE
Removing Collateral gives "Error Code: 0. 400 - BadRequest(/v0/mainnet/rawtx/sen...

### ISSUE THREAD

**Issue by whatthegit** [DeFiCh/wallet#1577]

**Comment by whatthegit** [comment]
![Q](https://user-images.githubusercontent.com/6679233/144829124-58172eb7-3ab8-4a61-af1b-b58d7a25d335.jpg)

**Comment by thedoublejay** [comment]
@whatthegit do you have at least 50% DFI collateral when you had removed it?

**Comment by whatthegit** [comment]
> @whatthegit do you have at least 50% DFI collateral when you had removed it?

Yes. Tried different percentages, including 100%. I have no issue with USDT though.

**Comment by whatthegit** [comment]
Appreciate that this critical basic feature box fixed soon. I can't do anything without my DFI being available.

**Comment by thedoublejay** [comment]
@whatthegit When you remove a collateral/take a loan, it's a requirement to have at least 50% DFI.

**Comment by whatthegit** [comment]
You meant 50% in the main balance?

**Comment by thedoublejay** [comment]
@whatthegit 50% DFI on the Vault. If you go to Edit Collaterals page, there's a vault share displayed there at the bottom right. 

Regarding the error message, we will be updating it on the next releases

**Comment by am999999** [comment]
Hi,  have exactly the same issue: By mistake, I added too much dUSDC collateral (more than 50%). When trying to mint, I get the "error 4: Insufficient DFI collateral." When trying to remove some dUSDC collateral, I get "Error code:0 400 Bad request". I tried to remove some sUSDC to get to 50%. But regardless the removing dUSDC amount (1$, 10$, 100$,...) I always get "Error code:0 400 Bad request". You may contact me, if you need more information to reproduce the bug...

**Comment by Gilli1545** [comment]
Same issue when payback loand ($SLV)

**Comment by am999999** [comment]
For me, the issue is resolved. I was able to withdraw dUSDC collateral without any error message. I assume is was related to the "1 Satoshi bug"...
