### ISSUE TITLE
Light Wallet Rewards

### ISSUE THREAD

**Issue by Tom7510** [DeFiCh/wallet#1582]
#### Anything else we need to know?: my adress "df1q2yw2sehgexqxr2pqe0x83zgflmuxdr4q84n62d"

Thanks!

**Comment by Tom7510** [comment]
My Vault Adress: 7d45468c70910d25e017d660e1a9db94bf101b6a2a6e16642695af7398c2e1b8

**Comment by Tom7510** [comment]
Hi, I do not get any rewards since in the morning - I'm close to exit the whole staff!
I send to my own wallet adress LP tokens several time - nothing happens. 
I put liquditiy mining into the LP pools before the rewards started - I understood from DefiChain Telegram posts that there was a bux and it has been fixed.
Any idea what I still should try out??

**Comment by Darkman-Q-Tester** [comment]
@Tom7510 Do you have more than 50% DFI as Collaterals in your Loan?

**Comment by kyleleow** [comment]
@Tom7510 Hello Tom, thanks for reporting, as you mentioned, this issue has been resolved by the team yesterday. 

I also did a check on your wallet address on [DeFiScan](https://defiscan.live/address/df1q2yw2sehgexqxr2pqe0x83zgflmuxdr4q84n62d), and you are indeed already receiving rewards from what I have observed.

Closing this ticket but feel free to create any new issue if you face any in the future.

**Comment by Tom7510** [comment]
Thanks Keng !!!

 
 

Gesendet: Dienstag, 07. Dezember 2021 um 11:39 Uhr
Von: "Keng Ye" ***@***.***>
An: "DeFiCh/wallet" ***@***.***>
Cc: "Tom7510" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [DeFiCh/wallet] Light Wallet Rewards (Issue #1582)


 

@Tom7510 Hello Tom, thanks for reporting, as you mentioned, this issue has been resolved by the team yesterday.

I also did a check on your wallet address on DeFiScan, and you are indeed already receiving rewards from what I have observed.

Closing this ticket but feel free to create any new issue if you face any in the future.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tom7510** [comment]
OK, thanks for clarification!

**Comment by Tom7510** [comment]
Appreciate  the quick response!
