### ISSUE TITLE
Payback loan while vault is on "HOLD" due price/oracle volatility

### ISSUE THREAD

**Issue by defichainislove** [DeFiCh/wallet#1588]
#### What would you like to be added:

I like to be added, that you can pay back the loan or that you can deposit more collateral, WHILE the vault is on "HOLD". 
The developers said, that it's for users safety, that the vault is on hold and can not get liquidated while that. It is very bad that nothing can be done during this time to INCREASE the security of not being liquidated. You can see it just before you would be liquidated. Then it says, for example, "Next collateral <150%". In the event that the vault is not on "Hold", you could deposit more collateral or pay back part of the loan. Since the vault is on "Hold" because of the volatility or an error, this cannot be done, although the vault is only on "Hold" to ensure the safety of the user. It would be cool if, in the event that the vault changes to "Hold", you can still deposit collateral or pay back the loan. Just not the other way around. Otherwise, as far as I know, if the vault is reactivated, you would be liquidated, although you are actually just waiting for it to be possible again ... Thank you very much

#### Why is this needed:

For users safety

__________________

Ps: if it is already so, just ignore my issue.
But a few days ago my vault was on 240% and on "HOLD" because of the oracle price of SPY I think and there was nothing I could have done to pay back a part of my loan while that.

Thanks very much

**Comment by thedoublejay** [comment]
Hi, this one has been resolved with `v0.20.0`
