### ISSUE TITLE
LP-Tokens are lost after sending to own wallet-address

### ISSUE THREAD

**Issue by baerpunkt** [DeFiCh/wallet#1589]
#### What happened:
This issue is also reportet at https://github.com/DeFiCh/ain/issues/949 as it is not clear on which side exists the bug.
And because i need to put awareness onto a big problem, what could even result in an unwanted liquidation of my vault as seriously i have no control over two of my LP-Token's.

I transfered all my LP-Token's to my own android-wallet-address today in the morning.
Two of them (dSLV-dUSD and dTLT-dUSD) are not shown in my light-wallet anymore since this moment.
It is also not shown at defichain-income.com they, thats why i report my bug here and not at the wallet-repository.

I checked my transactions (everything since Block 1426883 .. as this seems to be my first transaction - and also the one of the LP-Token was is missing now - dSLV-dUSD). But the transactions show all my correct wallet-address (in the IN-transaction).

What is interisting: defiscan.live still shows the correct LP-Tokens balances, here everything looks correct, so the tokens are there but not shown anywhere else.

But serously i wonder if i get rewards for that Pools now, when the light-wallet and even defichain-income.com already don't "recongize" them as existing.

I also wonder if there is a way to see from where the rewards are coming that i get, in other words if the rewards from that pools are inlcuded or if they are sadly lost.

#### What you expected to happen:
The LP-Tokens schould be visible.

#### How to reproduce it (as minimally and precisely as possible):
I have no idea .. just do the same like me with much LP-Tokens.

#### Anything else we need to know?:
My wallet-address is: df1q73d6tqdxyq4crccwh0nklmgzjprv25e3nvzgc2
(you can check by yourself what happened)

**Comment by baerpunkt** [comment]
One more important note .. i tried to fix the visiblity-problem with adding some more token to the dSLV-dUSD-Pool, but with no luck .. the wallet still don't show the pool(s), same on defichain-income.com .. but the amount of token increased on defiscan.live .. to the blockchain at least is aware of my tokens.

**Comment by baerpunkt** [comment]
So actualy there is no way for me to remove my token from those both pools (dSLV-dUSD and dTLT-dUSD).

**Comment by baerpunkt** [comment]
As in the https://github.com/DeFiCh/ain/issues/949 exposed the blockchain seems does correctly everthing, even rewards are distributed to my wallet as the "listaccounthistory" shows.

The fault seems to lie on the wallet-side or in the interface between wallet and blockchain and should be followed up here.

**Comment by baerpunkt** [comment]
I checked now manually (in google-playstore) again if there is an update for the wallet and yes there is (in the night this didn't show up on my phone) .. the updated solved the problem how it seems. I see the missing pools now and can remove token from them.

So the ticket can be closed.

**Comment by thedoublejay** [comment]
Thank you @baerpunkt! Might be a caching issue and got resolved on app restart
