### ISSUE TITLE
`transactions` - main page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#159]
#### What would you like to be added:
Display all transactions
#### Why is this needed:
- [ ] Display transactions
- [ ] Type of Transaction
- [ ] Transaction Symbol 
      - Green for any amounts to be added to the wallet (Receive, rewards etc)
- [ ] ~~Filter option https://github.com/DeFiCh/wallet/issues/157~~
- [ ] Details https://github.com/DeFiCh/wallet/issues/158

![image](https://user-images.githubusercontent.com/25013382/122028012-2e78fb80-cdfe-11eb-9d22-f4e6ce03f536.png)

**Comment by fuxingloh** [comment]
/area ui-ux transactions
/assign @ivan-zynesis
/priority important-soon
/triage accepted

We can ignore filter, we aren't and I don't intend to support that.

You need to use this, endpoint. The SDK is already included. The test environment is included as well to automate choose remote or local.

- For the tx type that we don't support yet, you can ignore it also.
- You can implement pull to refresh for refreshing. 
- You don't need to store in the global state for this.
- You can set the count to 30 items per page.
- You can set it to lazy load on scroll

https://github.com/DeFiCh/whale/blob/4d8ab61f4aecd3283caa258c6ef3e93f95517172/packages/whale-api-client/src/api/address.ts#L44-L54
