### ISSUE TITLE
`auctions` - update to flatlist

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1593]
#### What would you like to be added:
We need to optimize the display on main auctions page. We can first update to flatlist and create a new array to combine all batches into a single list so we don't loop twice.

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:**  Verify the performance while the user is placing a bid

**Android:**

- [ ] Auctions > Place Bid > Verify app doesn't hang / navigation within the flow is smooth enough 
- [ ] Loans > Add Collateral > Borrow Loan token > Auctions > Place Bid > Verify app doesn't hang / navigation within the flow is smooth enough 

**iOS:** 

- [ ] Auctions > Place Bid > Verify app doesn't hang / navigation within the flow is smooth enough 
- [ ] Loans > Add Collateral > Borrow Loan token > Auctions > Place Bid > Verify app doesn't hang / navigation within the flow is smooth enough
