### ISSUE TITLE
`vault details` - add dollar value

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1594]
#### What would you like to be added:
Add dollar value on token amounts
It should look like similar to the Edit Collateral page. Ex. **200 DFI/$10000**

1. Vault Detail - Collateral Tab
![image](https://user-images.githubusercontent.com/25013382/144943161-628b9d15-3bdb-434a-9ca7-d0b2bcd908d8.png)
2. Loans tab - in Outstanding balance and interest amount
![image](https://user-images.githubusercontent.com/25013382/144943277-5eef6f08-448a-4293-ae26-2758ac015c4b.png)

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:**   To verify dollar value is displayed in vault details

**Android:**
- [ ]  Loans > Your vaults > Collateral Section
- [ ]  Loans > Your vaults > Loan Section
- [ ]  Loans > Your vaults > Details Section

**iOS:**
- [ ]  Loans > Your vaults > Collateral Section
- [ ]  Loans > Your vaults > Loan Section
- [ ]  Loans > Your vaults > Details Section

**Comment by fullstackninja864** [comment]
Created separate ticket for Loans tab #1639
