### ISSUE TITLE
`add/remove collateral` - dollar value

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1595]
#### What would you like to be added:
Display dollar value for Available and current fields
![image](https://user-images.githubusercontent.com/25013382/144943780-d982b2fc-b172-4cf6-a993-98b6eea3be5c.png)

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:** To verify dollar value is displayed in `add`/`remove` collateral

**Android:**

- [ ]  Loans > Your Vaults > `+`/`-`

**iOS:**
- [ ]  Loans > Your Vaults > `+`/`-`

**Comment by thedoublejay** [comment]
Duplicate of https://github.com/DeFiCh/wallet/issues/1636
