### ISSUE TITLE
`borrow loan token` - dollar value

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1596]
#### What would you like to be added:
Display dollar value based on user input. Don't include swap as we will not support entering of USD amount.
![image](https://user-images.githubusercontent.com/25013382/144943983-cabe84a9-e2ca-4e72-9470-a05a2238d720.png)

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:**   Verify dollar value is displayed for borrow loan token

**Android**

- [ ]  Loans > Create Vault >  Add Collateral > Borrow Loan Tokens > Verify dollar value for input

**iOS**

- [ ]  Loans > Create Vault >  Add Collateral > Borrow Loan Tokens > Verify dollar value for input
