### ISSUE TITLE
`payback loan and borrow more` - display dollar values

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1597]
#### What would you like to be added:
1. Display dollar values on Available;
![image](https://user-images.githubusercontent.com/25013382/144944152-9e18beeb-b780-4387-a51b-3a24458e7adc.png)

2. Amount to Pay and Resulting loan amount
![image](https://user-images.githubusercontent.com/25013382/144944207-34750b00-f01c-4e98-a210-bfa94686b36b.png)

3. Do the same with Borrow More page (Same layout)

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:**  To verify dollar value is displayed in `PAYBACK LOAN` flow and `BORROW MORE`

**Android:**
- [ ]  Loans > Your Vaults > Loans Section > `PAYBACK LOAN`  >  Verify dollar value displayed
- [ ]  Loans > Your Vaults > Loans Section > `BORROW MORE` > Verify dollar value displayed

**iOS:**
- [ ]  Loans > Your Vaults > Loans Section > `PAYBACK LOAN`  >  Verify dollar value displayed
- [ ]  Loans > Your Vaults > Loans Section > `BORROW MORE` >  Verify dollar value displayed
