### ISSUE TITLE
Every Transaction gives "Error Code: 0. 400 - BadRequest(/v0/mainnet/raw... 

### ISSUE THREAD

**Issue by kold312** [DeFiCh/wallet#1611]
#### What happened:
During the downtime of the chain i placed an transaction to reduce my LM pool. After a while I got a postive notification but nothing happend. Since then i get the Error Code: 0. 400 - BadRequest(/v0/mainnet/raw by every transaction i try. 
I have enough UTXO and even try https://utxo.mydeficha.in/index.php - i got a few UTXO but this does not change anything. 

#### What you expected to happen:
I would like to do transactions as normal.

**Comment by kyleleow** [comment]
Hello @kold312 , thanks for opening an issue. 
This issue has since been resolved in the latest version of Light Wallet. 

If you haven't already, please update to the v0.19.0 from [App Store](https://apps.apple.com/us/app/defichain-wallet/id1572472820) or [Google Play](https://play.google.com/store/apps/details?id=com.defichain.app)

Closing this issue, feel free to raise any other issue if you face them.

**Comment by kold312** [comment]
Sorry, but v0.19.0 did not resolve anything!

**Comment by kold312** [comment]
Thanks for reopen this. Of course i‘m on the latest Version, but i can‘t do anything in the App, even not swap Tokens to UTXO.

**Comment by kold312** [comment]
![62D2992D-3518-44BE-BA13-FA8F117E5533](https://user-images.githubusercontent.com/95728280/145150062-cacd1400-2659-407c-9c7c-b32b1a1bce23.png)

**Comment by kyleleow** [comment]
Would you mind to provide us your wallet address so we can investigate the issue on our end?

**Comment by kpdt** [comment]
similar here: 
- the version is 1.19.0
- UTXO in the wallet: > 80
- DFI part in the vault collateral: > 70%

Not able to pay back a loan, getting "Error Code: 0. 400 - BadRequest(/v0/mainnet/raw"

**Comment by kold312** [comment]
Thanks to Keng it works for me again. Great support. Great community!

**Comment by kpdt** [comment]
@kold312 what was a solution?

**Comment by kold312** [comment]
Could not do anything. Either Keng solved it after getting in touch with him via Telegram or it was resolved bei itself.

**Comment by githubcodetester** [comment]
This is not resolved and still happening. Also on iOS version 0.19.0

Unable to payback loans.

Also can’t add liquidity to LM pools.

Have sufficient DFI, dUSD and UTXO in all places.
![Uploading 2780EA76-1A0F-4C8C-8AE4-561E9EF08176.jpeg…]()
