### ISSUE TITLE
`pool swap` - improve breakdown on confirm pool swap page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1615]
#### What would you like to be added:
Currently, if there's a conversion needed, we display "amount to be converted". This looks like we're converting only a certain amount of DFI to Token B. 

We need to have a field for DFI to be converted, and Token A to be swapped.

![image (4)](https://user-images.githubusercontent.com/25013382/145163117-53c79c47-6553-4179-afbb-9aa784282c82.png)

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:**  Verify field is added for `DFI token` + `UTXO` while swapping tokens

**Android:**
- [ ]  DEX > SWAP > `DFI token` (DFI to be converted)and  `UTXO` should be displayed 

**iOS:**
- [ ]  DEX > SWAP > `DFI token` (DFI to be converted)and  `UTXO` should be displayed
