### ISSUE TITLE
Credit disappeared!

### ISSUE THREAD

**Issue by frankhelferich** [DeFiCh/wallet#1633]
650 DFI sent from wallet to cake, more than 3 days ago. Balance on wallet and cake = $0.00. No display of a transaction???

**Comment by thedoublejay** [comment]
@frankhelferich do you have the TX id? Also did you check this with cake side? if you can post the address here we can check on DeFiScan

**Comment by frankhelferich** [comment]
That's my problem, there is no transaction on Cake or my wallet, but my coins have disappeared. Cake support answered me that there are currently delays =(

**Comment by frankhelferich** [comment]
I only have proof that i transferred 650 dfi to the wallet
TX-ID: ea3a6287aced238e7a3f692945909728232e47967bab819f1d84d6220499ac21

**Comment by thedoublejay** [comment]
@frankhelferich ok let's keep this issue open until you get a response from Cake side

**Comment by frankhelferich** [comment]
After an update and a long time of synchronization, my wallet shows my balance again 😅. Everythings fine. Thanks for all 😃
