### ISSUE TITLE
vault details - add dollar value for loans card

### ISSUE THREAD

**Issue by fullstackninja864** [DeFiCh/wallet#1639]
#### What would you like to be added:
![image](https://user-images.githubusercontent.com/25013382/144943277-5eef6f08-448a-4293-ae26-2758ac015c4b.png)

**Comment by fullstackninja864** [comment]
@jtlntno-cake Will need design for this

**Comment by jtlntno-cake** [comment]
[Adding design link here for reference](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=5942%3A89201)

Reference for different states of Loan cards [here](https://www.figma.com/file/CMoIqpPpzeJTLumlwZNyz8/DSGN---Light-Wallet---Design-System?node-id=1210%3A18588)
