### ISSUE TITLE
Update icon set used to MaterialIcons and/or MaterialCommunityIcons

### ISSUE THREAD

**Issue by aentan** [DeFiCh/wallet#164]
#### What UI/UX improvements would you like to be implemented: 
Update icon set used to MaterialIcons and/or MaterialCommunityIcons.

#### Why is this needed:
The desktop app uses Material Design Icons. The designs also specify Material Design icons. We should unify all icons used in every product for consistency. MaterialCommunityIcons are additional and non-official icons that are consistent with the MD style, and may be useful if we need something not provided by the base set.

#### Which component/screens does this concern?:
Tab bar and anywhere else in the UI that shows icons.

#### Anything else we need to know?:
All design icon specifications are in Marvel handoffs.

**Comment by fuxingloh** [comment]
https://github.com/DeFiCh/wallet/pull/165#issue-672291416
