### ISSUE TITLE
Missing translation: DE

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#1644]
#### What translation improvements would you like to be implemented:
• Missing translation

#### Which component/screens does this concern?:
• Balances > Send > `CONTINUE`
**DE:**
```
Transaction type = Transaktionsart
Amount to send = Zu sendender Betrag
```
![211209 v0 19 4 - iOS:Android - Balances - Send - Continue - Missing DE1](https://user-images.githubusercontent.com/65014479/145359709-bc662a1d-25e1-4b7d-9823-5c7a3570bceb.jpeg)

**Comment by thedoublejay** [comment]
Will be fixed on other PR
