### ISSUE TITLE
Provide a smaller preview of the loans page

### ISSUE THREAD

**Issue by benameless** [DeFiCh/wallet#1655]
#### What would you like to be added:
Let me "hide" some information of the loans on the "Your Vaults" page. What is very, very important to see at first glance?
Vault-ID, the Vault#, current and future collateralization ratio, the visual bar. For easy handling also the two adding buttons.

I think we can save about 30% of the height of the vault preview.
Hide the collateral types, Active loan types, The amounts of that.

Do that with an open/close button.

#### Why is this needed:
I currently have 2 vaults active and can only preview 1,5 of them. Reduce the overview to its core values, will improve the UI/UX.  – sorry just saw there is an UX improvements section.

**Comment by izzycsy** [comment]
Hi @benameless , thanks for your feedback, the team will consider your feature request for future updates, I’m unable to provide a timeline at the moment as we’re prioritising other issues, however we’ll keep this ticket open for tracking. Thank you for your understanding and patience.
