### ISSUE TITLE
A history of actions done

### ISSUE THREAD

**Issue by benameless** [DeFiCh/wallet#1657]
#### What would you like to be added:
Whenever I add securities or take loans, there is currently no way to have a look on what I have done in the past.
I would love to be able to have a record of all my actions I have done. This could be a separate thing, but I think this is very important to have a track of what happened/was done by me. I think this should be done as well as possible, to have a simple and easy to read function. 

#### Why is this needed:
I do not think, that only an external company should have the "easy-to-use" UI with basic functions. DeFiChain has a very nice light wallet, and should also provide that feature. This would improve the UI/UX immensely.

**Comment by izzycsy** [comment]
Hi @benameless , thanks for your feedback, Transactions on the app is still WIP, however you can track your vault / address transactions via https://defiscan.live/ at the moment. Hope it helps.

**Comment by izzycsy** [comment]
Hi @benameless , regarding the issue [`UTXO transaction (sent/receive) are missing in the listaccounthistory at Jellyfish addresses (Light-Wallet)
#1732`](https://github.com/DeFiCh/wallet/issues/1732), we can further discuss the issue there. We would like to keep same issues in one thread. Thank you.
