### ISSUE TITLE
Add the information of "new collateral ratio" when adding securities

### ISSUE THREAD

**Issue by benameless** [DeFiCh/wallet#1658]
#### What would you like to be added:
When I add securites to an existing vault, i would like to know, how this effects the collateral ratio. If you take a loan, this feature is already enabled, but not in the case of adding more securities.
In the vault -> edit securities (Sicherheiten bearbeiten) -> + -> enter the amount -> preview should be on the next page

#### Why is this needed:
Improves the UX, the user can see, how the amount will affect the collateral ratio.  – sorry just saw there is an UX improvements section.

**Comment by thedoublejay** [comment]
Hi @benameless, thanks for the feedback. We have an open issue regarding this topic. Will close this and you can follow up on the other ticket. Thank you! - https://github.com/DeFiCh/wallet/issues/1636
