### ISSUE TITLE
Can't payback loan for a vault

### ISSUE THREAD

**Issue by dakshvar22** [DeFiCh/wallet#1660]
#### What happened: 

Hi! I am trying repay the loan on a vault using the light wallet app but i'm consistently getting an error like this: Cannot payback this loan amount for...
Its been 2 days since i've been trying now. How do I fix this? I even tried updating the app

#### What you expected to happen:

 the loan amount repaid

#### How to reproduce it (as minimally and precisely as possible): 

i am not sure how to reproduce it. My vault IDs are

`1ebdf28cd28a64af35ab9a9f762eef2ffbc2af6d4c092f6fde128fb1cff50258`

`4183d664fe57ae70b36208bdbe12e40c06d473866231458c37d8ae9d801e305b`

Both the vaults have the same issue.

The owner wallet address is `df1ql5ea4nnfjwcnvzmaqcvvpv9gr889n6edpgsw9x`

I have sufficient funds to pay the amount I am trying to repay.

Here's a screenshot of the error 
![Screenshot_20211209-213550_DeFiChain Wallet](https://user-images.githubusercontent.com/8708249/145474121-bba72b67-bfdf-4d85-a18a-f34bd2726a1b.jpg)

**Comment by thedoublejay** [comment]
Hi, will close this one since there's already an open issue for this. Please refer to this one - https://github.com/DeFiCh/wallet/issues/1660
