### ISSUE TITLE
#1498 `QA` - DEX - favorite pair card 

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1665]
#### Why is this needed:
Links to #1498

**Comment by izzycsy** [comment]
Acceptance Criteria: User able to "star" their preferred pair.

Android:
- [ ] DEX > `star` icon present
- [ ] DEX > select `star` > poolPair appears at top of screen

iOS:
- [ ] DEX > `star` icon present
- [ ] DEX > select `star` > poolPair appears at top of screen
