### ISSUE TITLE
`DEX` - Composite Swap - Remove explicit pairs on one hop

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1667]
#### What would you like to be added:
Once this change is merged from blockchain side, https://github.com/DeFiCh/ain/pull/956#discussion_r763925593, we don't need to specify the explicit path if it's only one jump (normal pool swap).

**Comment by fuxingloh** [comment]
This seems like it's going into enforcement for the `2.4.x` milestone. Since this behavior is already allowed we should implement it soon.

**Comment by fuxingloh** [comment]
It's not enforced anymore, we can close this when the PR below gets merged.

https://github.com/DeFiCh/ain/pull/956/files#diff-5b5f5b126aad5172f5e15066f2926f4afb57e75eb624b509f56233c14cd4b5c9R1178-R1181
