### ISSUE TITLE
Feature Request DFI Price in USDT/USDC

### ISSUE THREAD

**Issue by matteshe** [DeFiCh/wallet#1673]
#### What would you like to be added:
It would be nice to see directly the DFI DEX Price on the Main View.

#### Why is this needed:
ATM one must go to the DEX and start Swap with DFI and Usdt/USDC pair and enter a value to see the DEX price. Sometimes one ist only interested in the price. This would be much easier to get an overview instead of clicking trough the app.

**Comment by thedoublejay** [comment]
Hi @matteshe, we have plans of improving the DEX page to cater with this use case. Thanks for the feedback.

**Comment by thedoublejay** [comment]
Hi @matteshe, this one is already available on DEX with `1.4.0` updates. Thanks!
