### ISSUE TITLE
Every loan costs minimum 0.00000001 dToken interest per block

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/wallet#1674]
#### What happened:
Taking a loan since the 2.3.0 update, always charges a minimum of 0.00000001 (1e-8) interest per Block. this can result in massive interests.
f.e. a loan of 0.000001 (1e-6) TSLA currently costs 1% interest PER BLOCK

#### What you expected to happen:

charge the actual amount and not have a minimum interest of 1e-8

#### How to reproduce it (as minimally and precisely as possible):

take loan of 0.000001 in any token. then see the interest increase by 1e-8 per block

**Comment by thedoublejay** [comment]
Hi, we will be closing this one and opening an issue on the node side - https://github.com/DeFiCh/ain/issues/980
