### ISSUE TITLE
#1639 `QA` - vault details - add dollar value for loans card 

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1680]
#### What UI/UX improvements would you like to be implemented: 
 Related to [1639](https://github.com/DeFiCh/wallet/issues/1639)

Acceptance Criteria: to display the dollar value of the loan card

Android: 
- [ ] Loans > Your vaults > Loans sections verify relative dollar value is displayed for loan amount

iOS: 
- [ ] Loans > Your vaults > Loans sections verify relative dollar value is displayed for loan amount

**Comment by izzycsy** [comment]
![image](https://user-images.githubusercontent.com/65014479/146755395-33c88c0f-c02a-4599-9459-edb927c9227b.png)

USD value to be under dToken amount.
