### ISSUE TITLE
#1525  `QA` -  vault health bar - closer representation with min col ratio 

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1683]
#### What happened:

Related to [1525](https://github.com/DeFiCh/wallet/issues/1525)

**Comment by izzycsy** [comment]
Acceptance Criteria: Check that vault `health bar` matches `health tag`

Android: 
- [ ] Loans > Check that `health bar` & `health tag` matches
- [ ] Loans > Select `>` to view Vault Detail > Check that `health bar` & `health tag` matches


iOS:
- [ ] Loans > Check that `health bar` & `health tag` matches
- [ ] Loans > Select `>` to view Vault Detail > Check that `health bar` & `health tag` matches

**Comment by izzycsy** [comment]
Duplicated
