### ISSUE TITLE
#556  `QA` -`receive` - faq 

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1693]
Related: #556 

#### What would you like to be added:

`Acceptance Criteria:`  Verify receive faq content

**Android:**
- [ ] `Balances` > `Receive`  > click `?` > Verify FAQ content
- [ ] Translation (ZHS) 
- [ ] Translation (ZHT) 
- [ ] Translation (DE) 

**iOS:**
- [ ]  `Balances` > `Receive`  > click `?` > Verify FAQ content
- [ ] Translation (ZHS) 
- [ ] Translation (ZHT) 
- [ ] Translation (DE)

**Comment by izzycsy** [comment]
Related: #556
