### ISSUE TITLE
`EN` - Change "Auctioned collaterals" to "Collateral for auction"

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#1694]
![IMG_4108](https://user-images.githubusercontent.com/65014479/145772629-de6199bf-bb53-4c23-81e5-29480d166032.jpeg)

#### What translation improvements would you like to be implemented:
**EN:**
`Auctioned collaterals = Collateral for auction`

**ZHT:**
`Collateral for auction = 待拍賣的抵押品`

**ZHS:**
`Collateral for auction = 待拍卖的抵押品`

**DE:**
`Collateral for auction = Zu versteigernde Sicherheiten`

#### Which component/screens does this concern?:
Auction

#### Anything else we need to know?:
@ngyingzhong researched on several sites and they said it’s an uncountable noun, i.e. no _s_

**Comment by thedoublejay** [comment]
Update:

DE = Sicherheiten für Auktion
