### ISSUE TITLE
#561 - `QA` - `add liquidity` - faq 

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#1695]
Related: #561 

`Acceptance criteria:`  Liquidity mining` faq displayed on `knowledge base` page

**Android**
- [x] `Balances` > Settings > `About` > `Knowledge base` > `Liquidity Mining`
- [x] Translation (EN)
- [x] Translation (ZHS) 
- [x] Translation (ZHT) 
- [x] Translation (DE) 

**iOS**
- [x] `Balances` > Settings > `About` > `Knowledge base` > `Liquidity Mining`
- [x] Translation (EN)
- [x] Translation (ZHS) 
- [x] Translation (ZHT) 
- [x] Translation (DE)

**Comment by izzycsy** [comment]
![220120 v0 22 5 - iOS:Android - About - Knowledge Base - Liquidty Mining -  Missing ZHS](https://user-images.githubusercontent.com/65014479/150369515-9c9a6061-0936-4875-ba29-420f58eb0eef.PNG)

![220120 v0 22 5 - iOS:Android - About - Knowledge Base - Liquidty Mining -  Missing ZHT](https://user-images.githubusercontent.com/65014479/150369576-32b95343-3e31-4fca-84aa-1eef6ee56d56.PNG)


Actual: 
**Android & iOS**
• Missing translation for: 
> **FREQUENTLY ASKED QUESTIONS**

Expected: 
• ZHS & ZHT translation to apply for entire screen

How to reproduce: 
• `Balances` > Settings > `About` > `Knowledge base` > Liquidity Mining
