### ISSUE TITLE
Alert feature for vaults which are at risk

### ISSUE THREAD

**Issue by defichainbull** [DeFiCh/wallet#1721]
#### What would you like to be added:

Alert feature for vaults. As soon as a vault drops to the status "at Risk", an alert on the smartphone should be triggered

#### Why is this needed:
I think an alerting feature within the mobile apps as soon as a vault drops to the status "at Risk" would be a feature, that helps a lot of people to not get liquidated. I know there are services like "Dobby" which are used right now, but imo, this feature need to be integrated within the app directly.

**Comment by kyleleow** [comment]
Duplicated issue of #1653
