### ISSUE TITLE
Please notify via a beep or vibrate when a trade has executed.

### ISSUE THREAD

**Issue by dougolang** [DeFiCh/wallet#1739]
#### What UI/UX improvements would you like to be implemented: 

It would be really helpful if there was some kind of notification when a trade has executed. A beep or a vibrate or both would be good. Also a boop (downward beep) if the transaction fails would be good. Extra bonus if the user could control the sound for the beep.

#### Why is this needed:

I keep doing this process where I want to trade but it takes a few minutes for each trade and I put the phone down and then when I think of it next 10 minutes have gone by and its been ready for a while - I can't be the only one doing this. It would really save me time in the process and not make me feel obligated to keep one eye on my phone all the time if there was a beep.

#### Which component/screens does this concern?:

DEX

#### Anything else we need to know?:

Thanks for all the hard work maintaining the light wallet!

**Comment by izzycsy** [comment]
Hi @dougolang , thanks for your feedback, the team take your feature request into consideration for future updates, there’s no timeline at the moment as we’re prioritising other issues, however we’ll keep this ticket open for tracking. Thank you for your understanding and patience.

**Comment by defidone** [comment]
> 
> 
> 
> 
> #### What UI/UX improvements would you like to be implemented: 
> 
> 
> 
> It would be really helpful if there was some kind of notification when a trade has executed. A beep or a vibrate or both would be good. Also a boop (downward beep) if the transaction fails would be good. Extra bonus if the user could control the sound for the beep.
> 
> 
> 
> #### Why is this needed:
> 
> 
> 
> I keep doing this process where I want to trade but it takes a few minutes for each trade and I put the phone down and then when I think of it next 10 minutes have gone by and its been ready for a while - I can't be the only one doing this. It would really save me time in the process and not make me feel obligated to keep one eye on my phone all the time if there was a beep.
> 
> 
> 
> #### Which component/screens does this concern?:
> 
> 
> 
> DEX
> 
> 
> 
> #### Anything else we need to know?:
> 
> 
> 
> Thanks for all the hard work maintaining the light wallet!
> 
> 

I would love it!

**Comment by thedoublejay** [comment]
Due to the nature of the product (Decentralized), we don't store data or have a centralized notifications service. So now this is not possible. We would suggest using services like - https://defichain-dobby.com/#/setup

**Comment by 0ptim** [comment]
I think what @thedoublejay is talking about are common push notifications to the client, which requires a centralized notifications service.
But couldn't we implement this feature differently?
As soon as the state of the transaction completes, the application itself will push the sound/vibration, instead of a notification service.

**Comment by dougolang** [comment]
Yes I am sorry if my request was misleading but I'm not sure why it is
being trashed for being unfeasible - I don't want an external push
notification that relies on outside systems - I just want when the screen
says 'transaction complete' for the phone to beep - I do a little
programming and I don't see why this would be a technical impossibility at
all.
