### ISSUE TITLE
Non-Tech Userfriendlieness

### ISSUE THREAD

**Issue by ggrohmann** [DeFiCh/wallet#1758]
First of all: The light wallet is a huge step forward and it does make most things right!

#### What UI/UX improvements would you like to be implemented: 

Streamline the (initial) information shown in the screens: For most users (non-developers or nerds) a lot is not required or necessary and lets user feel overwhelmed. Take this stuff out or to an extended view (optional, register tab or via settings - plenty options to provide the information for interested users, if needed)

Furthermore: increase the use or size of icons or pictures a little to make it more appealing to the eye. It's always a little "boring" to have that much text (which is of course required). But our mind and our eyes are very happy, if they have more "brain-conform" things such as symbols, graphics and so on.

#### Why is this needed:

To have a wider user base, we want to welcome people, which are not super familiar with all the tech stuff and offer them an easy user experience where one can find **intuitively** things that I need or am looking for.

#### Which component/screens does this concern?:

Start screen, dex, vaults etc.

#### Anything else we need to know?:

Suggestions:
Wallet
- wallet address, vault address etc: I don't need to see all chars, for me the 1st and last four are important, e.g.: df1q...pq72. Click on it and it's in my clipboard or open an external blockchain site (already there) if I need full information
- UTXO/ Token: yes, technically important, but for me as a user a worthless information, I don't want to care about this :-)

Dex
- TVL: good information, but for users it doesn't need to be presented as the first thing on top, maybe move it to the bottom?
- Coin pairs: Awesome to tag them as favorit! 
- Coin pairs: Still a lot of needless information for me as a user: How many tokens are in the pool? Why do I care if I want to trade? (yes, if there is almost none liquidity, then I don't want to trade, but that's what the slippage setting is for). Maybe just have an icon (green, yellow, red) for liquidity to indicate when a pool has insufficient liqidity
- Coin pairs: APR: not really necessary in a dex. If a techie wants to add liquidity, he/she already informed himself before. Put it somewhere to an advanced view or tab.
- Coin pairs: perhaps have "Trade" and "Provide liquidity" in the same row (and put trade in first place, that's what the dex is for), so I can see more stocks/ token or whatsoever at the same time (below each other, meaning more rows)

Vault:
- Would be awesome, if I could swipe left / right to switch between my vault and search loans
- Once again: shrink the id to xxxx...xxxx (4 chars in front and end)

**Comment by izzycsy** [comment]
Hi @ggrohmann , thanks for your feedback, the team take your feature request into consideration for future updates, there’s no timeline at the moment as we’re prioritising other issues, however we’ll keep this ticket open for tracking. Thank you for your understanding and patience.
