### ISSUE TITLE
Transaction history: Show actual information (not only "Sent DFI")

### ISSUE THREAD

**Issue by ggrohmann** [DeFiCh/wallet#1759]
#### What would you like to be added:

The transaction history doesn't show, what I actually have done (swap, increase loan etc.). It only states sent or receive dfi, which is maybe right from a blockchain technical perspective, but as a user this is nonsense to me.

#### Why is this needed:

Everybody wants to see in the transaction history what he/she has really done.

**Comment by ab-tools** [comment]
That's indeed something I noticed already, too, and would be great to see improved:
At the moment the "Transactions" view in the light wallet is not really useful I would say...

**Comment by ab-tools** [comment]
I guess related to this: https://github.com/DeFiCh/wallet/issues/1732

**Comment by izzycsy** [comment]
Hi @ggrohmann , thanks for your feedback. Regarding the issue [`UTXO transaction (sent/receive) are missing in the listaccounthistory at Jellyfish addresses (Light-Wallet)
#1732`](https://github.com/DeFiCh/wallet/issues/1732), we can further discuss the issue there. We would like to keep same issues in one thread. Thank you. 

Thanks @ab-tools .
