### ISSUE TITLE
Defichain light wallet error - frozen Loan

### ISSUE THREAD

**Issue by hellasXpress** [DeFiCh/wallet#1789]
I need some urgent help with the light wallet. I set up my first Vault and took a Loan (500 DUSD). It is displayed correctly in the Vault itself, on the Defichain Explorer /Scan and also in Defi-income. But the loan is not displayed in the balance section of the light wallet! I can not use the loan. It has been days now and it is still not displayed in the balance section. It is also strange that when I try to repay the loan and click on the button repayment, I am shown that supposedly no DUSD are available to repay... It is like frozen, I have already deleted the app several times and reinstalled, wallet again imported.... all without success. The same phenomenon is on the iPad. Thus, I now pay interest but can not use my loan at all....  I have then again 1 DUSD additionally minted, this is then actually correctly displayed in the balance section and can also give it back. But just this single DUSD. but my first 500 DUSD remain as frozen! I have already tried to clarify the issue in all forums on Telegram, but no one had a purposeful idea. Maybe one of you has an idea? Am grateful for any tip, thanks , coming from Germany - Andonis

**Comment by hellasXpress** [comment]
Hi guys, I'm Andonis from Germany, I need some help with the light wallet. I set up my first Vault and took a Loan (500 DUSD). It is displayed correctly in the Vault itself, on the Defichain Explorer / Scan and also in Defi-income website. But the loan is not displayed in the balance section of the light wallet? I can not use the loan at all. It has been days now and it still is not displayed in the balance section. It is also strange that when I try to repay the loan and click on the button repayment, I am shown that supposedly no DUSD are available to repay... It is like frozen, I have already deleted the app several times and reinstalled, wallet again imported.... all without success. The exact same phenomenon is on the iPad. Thus, I now pay interest but can not use my loan at all....  I have then again 1 DUSD additionally minted, this is actually correctly displayed in the balance section and can also give it back. Only my first 500 DUSD remain as frozen! I have already tried to clarify the issue in several forums on Telegram, but no one had a purposeful idea. Maybe one of you has an idea? Am grateful for any tip

**Comment by thedoublejay** [comment]
Hi @hellasXpress can you provide us your address so we can check it on DeFiScan?

**Comment by hellasXpress** [comment]
Hi @thedoublejay here is my Vault adress:

cf6a03fd2194d21276a76a72f61afa2047c7a870a752b9e972839006f0a0fb82

do you need also my wallet adress?

thanks for helping

**Comment by thedoublejay** [comment]
Hi @hellasXpress, on one of your transactions you have swapped your DUSD to DFI. Now, the DUSD you loaned is currently swapped to DFI.

**Comment by hellasXpress** [comment]
Hi @thedoublejay ok but what does that mean regarding my problem, sorry but I am not so well versed with the connections in the wallet... I still don't see my 500 DUSD not in my balance section

**Comment by hellasXpress** [comment]
@thedoublejay Does this mean that my 500 DUSD is now part of my DFI in the balance section?

**Comment by thedoublejay** [comment]
> @thedoublejay Does this mean that my 500 DUSD is now part of my DFI in the balance section?

Yes

**Comment by hellasXpress** [comment]
@thedoublejay Ah , ok, then that was not intended and was my mistake ... sorry I guess I can make the whole thing undone in which I swap the proportional DFI back into DUSD and feed my loan again ?! Anyway, thanks for your help and my enlightenment ;) All the best, Andonis

**Comment by thedoublejay** [comment]
No worries, will be closing this issue now. Have a nice day!
