### ISSUE TITLE
add Button not reachable in german Version

### ISSUE THREAD

**Issue by M-Stege** [DeFiCh/wallet#1805]
#### What UI/UX improvements would you like to be implemented: 
In German Version is the add button in vault details/ add token as collateral not reachable when UTXO to token  window is shown.
I would like the window to be ad the top instead of the bottom

#### Why is this needed:
i cant really push the Button

#### Which component/screens does this concern?:
English Version:
Loans-->Edit Collaterals-->Add Token as Collateral
German Version
Darlehen-->Sicherheiten Bearbeiten-->Token als Besicherung hinzufügen

#### Anything else we need to know?:
German
![Screenshot_20211218-133448_DeFiChain-Wallet_LI](https://user-images.githubusercontent.com/84290446/147221615-6d1889f7-6713-488b-8621-872a9a60c12e.gif)
English
![Screenshot_20211223-112345_DeFiChain-Wallet](https://user-images.githubusercontent.com/84290446/147230368-3583db5f-3d46-4193-8ed5-e3daa407e4ba.gif)

**Comment by kyleleow** [comment]
Hello @M-Stege thanks for reporting the issue, this has been addressed in the latest app version of v0.22.0 

Could you try updating to the latest app version to see if it solves your problem?

**Comment by M-Stege** [comment]
Hello @kyleleow many thanks,
it is beautiful. I can scroll and any thinks i can see.
Marry Christmas
