### ISSUE TITLE
`token icon` - update all token icons across the app

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1827]
#### What would you like to be added:
We want to update the token icons for dTokens across the entire application. This will provide a more professional look to the app compared to using the brand colors, which might be a bit inconsistent especially for brands which have more distinct colors.

With this update, we need to update the supporting BG also, especially on some UI components.

![image](https://user-images.githubusercontent.com/25013382/147924333-050b351a-a86e-405f-8434-27af35ae2a8c.png)

#### Why is this needed:
https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=6556%3A133953

#### Breakdown

- [ ] Balances - Balances Row
- [ ] Send - Token Modal
- [ ] Send - Confirm Page
- [ ] DEX - Browse Pool Pairs
- [ ] DEX - Your Pool Pairs
- [ ] DEX - Swap Page
- [ ] Loans - Main Page
- [ ] Vaults - Main page
- [ ] Auctions - Main Page

**Comment by fullstackninja864** [comment]
For the company icons only we will be changing the background colour to `#0E0A0D`. For dUSD the icon will be the same as existing one.

**Comment by fullstackninja864** [comment]
On balances page use below icon style for LPT

<img src="https://user-images.githubusercontent.com/53080940/149904852-a2b8ff00-5571-43c1-b1eb-82c267e3163d.png"  width="40%"/>

**Comment by kyleleow** [comment]
@fullstackninja864 
- for dBTC-DFI pair, do you want to display as upper case "DBTC" in the icon?
- if we use this icon on balance page, do we need to update the icon used in DEX screen too? 

> On balances page use below icon style for LPT
> 
> <img alt="" width="40%" src="https://user-images.githubusercontent.com/53080940/149904852-a2b8ff00-5571-43c1-b1eb-82c267e3163d.png">
