### ISSUE TITLE
Add US$ Value to bidding tokens information - same as on defiscan.live/auctions

### ISSUE THREAD

**Issue by AndiyNW** [DeFiCh/wallet#1856]
#### What UI/UX improvements would you like to be implemented: 

add the USD value for the new/first bid of the token to easier calculate the bidding value!

#### Why is this needed:

would make life easier for people who want to participate in the auction and be able to calculate, if it's worth to bid! without doing the manual calculations and going back to the web and such!

#### Which component/screens does this concern?:
Display USD prices on Auction card and Auction detail page

- [x] #1985
![image](https://user-images.githubusercontent.com/25013382/150893798-26940da2-196d-4135-8db4-fa4b238e1ff0.png)

- [x] #1986
![image](https://user-images.githubusercontent.com/25013382/150893778-57b74e71-fcda-4254-a0ad-977269a56acd.png)

- [x] #1987
![image](https://user-images.githubusercontent.com/25013382/150903772-8319924b-9251-4433-87a5-a2910d4502fc.png)

#### Anything else we need to know?:

nope

**Comment by izzycsy** [comment]
Hi @AndiyNW , thanks for your feedback, the USD value is already being implemented in some features, the team take your feature request into consideration for future updates, we’ll keep this ticket open for tracking. Thank you for your understanding and patience.

**Comment by kyleleow** [comment]
Blocked by #2032
