### ISSUE TITLE
#1499 `QA` - `balances` - display portfolio value and token breakdown 

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#1863]
Related: #1499 

Acceptance Criteria: To display total portfolio value on balances + total dollar amount per token

Android: 
**Balances**
- [x] check Total Portfolio Value is present
- [x] check sum of Total Portfolio Value is correct
- [x] scroll to check prices are valid for each token
> Refer to calculation of price below
> Price via [DEX](https://defiscan.live/dex) 

**DEX**
- [x] Your pool pairs > Check prices are correct
- [x] || > `+ ADD MORE` > Check prices
- [x] || > `- REMOVE` > Check prices
- [ ] For `SWAP` cases: refer to #1993 
> Price via [DEX](https://defiscan.live/dex) 

**Loans**
- [x] `Browse loan tokens` > check prices 
- [x] `Browse loan tokens` > select `dGOOGL` > under `SELECT LOAN TOKEN` > check prices for all
> Price via [Oracles](https://defiscan.live/oracles) 

iOS:
**Balances**
- [x] check Total Portfolio Value is present
- [x] check sum of Total Portfolio Value is correct
- [x] scroll to check prices are valid for each token
> Refer to calculation of price below

**DEX**
- [x] Your pool pairs > Check prices are correct
- [x] || > `+ ADD MORE` > Check prices
- [x] || > `- REMOVE` > Check prices
- [ ] For `SWAP` cases: refer to #1993 
> Price via [DEX](https://defiscan.live/dex) 

**Loans**
- [x] `Browse loan tokens` > check prices 
- [x] `Browse loan tokens` > select `dGOOGL` > under `SELECT LOAN TOKEN` > check prices for all
> Price via [Oracles](https://defiscan.live/oracles) 

**Calculation of price via [DEX](https://defiscan.live/dex):** 
> if 1 dBTC = 14,730 DFI 
> and 1 DFI = 2.43 dUSDT
> 14,730 DFI = 2.43 * 14,730 = 35,793.9 dUSDT

**Comment by thedoublejay** [comment]
@dwivedinalin @izzycsy Some test cases to check. 
1. Can we have an expected value on MainNet based on DEX prices? Example, if I have 3 DFI, what's the value based on DEX prices?
2. Also check if total portfolio value sum is correct
3. Check prices of LP tokens if correct
4. Check prices of loan tokens are correct
5. When changing DEX, check if token price will change also
