### ISSUE TITLE
#1828 `QA` - `send` - update content when sending liquidity tokens

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#1864]
Related: #1828

Acceptance Criteria: Display warning message before users sent liquidity pool tokens (i.e, `DFI-dETH`, `DFI-dBTC`)

Android: 
- [ ] Balances > scroll to `DFI-dETH` > send > check for warning message
- [ ] Repeat for **all** pool pair tokens
- [ ] Translation (ZHS) present when language switched
- [ ] Translation (ZHT) present when language switched
- [ ] Translation (DE) present when language switched

iOS: 
- [ ] Balances > scroll to `DFI-dETH` > send > check for warning message
- [ ] Repeat for **all** pool pair tokens
- [ ] Translation (ZHS) present when language switched
- [ ] Translation (ZHT) present when language switched
- [ ] Translation (DE) present when language switched

**Comment by lu599040708** [comment]
这是什么鬼啊
