### ISSUE TITLE
`collaterals` - add resulting vault share when adding/removing collateral

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1867]
#### What would you like to be added:
When adding/removing collaterals, display resulting vault share.
#### Why is this needed:
For each collateral added, it would be helpful for users to understand how it will affect their current vault. This will also prevent some issues, like getting locked collateral due to improper balance.

**Comment by jtlntno-des** [comment]
Sharing updated design on the flow of managing collaterals. 
[Prototype - Add Collateral](https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?page-id=6556%3A133899&node-id=7924%3A113940&viewport=241%2C48%2C0.31&scaling=scale-down&starting-point-node-id=7924%3A113940&show-proto-sidebar=1)
[Prototype - Remove Collateral](https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?page-id=6556%3A133899&node-id=7945%3A115403&viewport=241%2C48%2C0.31&scaling=scale-down&starting-point-node-id=7945%3A115403&show-proto-sidebar=1)
[Design files for handoff](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=7924%3A113938)


Some notable changes are the ff:
- Relocated the vault collateralization bar from the bottom modal to the main page
- Redesigned bottom modal to include vault share
- Redesigned text field to include USD value of input to reduce clutter (not priority)

Let me know if any questions/concerns. Thanks!
