### ISSUE TITLE
Cant create a vault (BadRequest 400)

### ISSUE THREAD

**Issue by 7schlaefer** [DeFiCh/wallet#1869]
#### What happened:
Cant create a vault. Failed to convert UTXO (Error Code: 0 400 BadRequest):
![IMG_6B27E65F9A9E-1](https://user-images.githubusercontent.com/7863003/148440320-ac0177b7-d221-436d-915d-7a6f272a2b02.jpeg)

#### What you expected to happen:
Can create a vault.

#### How to reproduce it (as minimally and p
recisely as possible):
Try to create a vault.

#### Anything else we need to know?:
iPhone 13

**Comment by thedoublejay** [comment]
@7schlaefer Hi, can you check if you have at least 3 DFI (UTXO)?

**Comment by 7schlaefer** [comment]
@thedoublejay had only 2,099 UTXO but 130 Token. I converted 5 tokens. Now it works. But isn't that exactly what the conversion is supposed to do?

**Comment by thedoublejay** [comment]
@7schlaefer Yes, but in this case, you might have been in the boundary of 2 UTXO (vault fee) and TX fee. So the automatic conversion will fail
