### ISSUE TITLE
Payback dAPPL Collatoral

### ISSUE THREAD

**Issue by Tom7510** [DeFiCh/wallet#1873]
#### What you expected to happen: Payback of sAPPL in my Vault. 
- Adress: df1q2yw2sehgexqxr2pqe0x83zgflmuxdr4q84n62d
- Vault: 7d45468c70910d25e017d660e1a9db94bf101b6a2a6e16642695af7398c2e1b8

#### How to reproduce it (as minimally and precisely as possible): I went to the pay back and entered the amount and entered "agree payback". After entering my PIN for agreeing the transaction, it was agreed but then aborted with the effor code:

Error Code: 0
Cannot payback this amount of loan for AA 

#### Anything else we need to know?:

I tried really everything -> just paying back half of it, changing digits of the pay back amount, closing the wallet and opening it again with a new trial to pay back, adding dAPP collatoral (which works) and trying to pay back again

Thanks for further support!

**Comment by thedoublejay** [comment]
Hi @Tom7510, there's an existing issue with loan payback, please check - https://github.com/DeFiCh/wallet/issues/1623.

Currently, only overpaying of loans work. Extra payment will be returned to your wallet.
