### ISSUE TITLE
create vault failed with error 0: malformed tx vout

### ISSUE THREAD

**Issue by Holgi2402** [DeFiCh/wallet#1876]
#### What happened: 
USING THE LIGHT WALLET IN TESTNET: Adress  tf1ql6swzzc7uxz22lf4rsc52dj4n7asuprnchqhln

Step 1 select vault scheme -> next was ok
Step 2 swap Token to tx was ok (transaktion finished)
Step 3 press creating the vault failed after signing with pssword

Error Code: 0
malformed tx vouts,creation vault fee is 1.00000000 DFI (code 16). Txid f0f615cffc37e3fd466280da9c2f2f7b0124ec825b572b7fbe1f7a5337b97f10

**Comment by thedoublejay** [comment]
Hi @Holgi2402, do you have existing UTXO for fees?

**Comment by Holgi2402** [comment]
who has to assign the issue?

**Comment by Holgi2402** [comment]
area/app

**Comment by Holgi2402** [comment]
i`m nor sure. the wallet shows me 

450 DFI
UTXO 2.09998680
Token 447.94984157

answers this your question?

**Comment by thedoublejay** [comment]
@Holgi2402 Yes, can you try to manually convert a bit more UTXO? From the Balances page, there's a convert button there. Try to convert at least 1 more Token, then try your operation again.

**Comment by Holgi2402** [comment]
ok, i changed 5 Token to UTXO and tryed it again to create a vault.

Result: now the error comes directly, because no tansaktion before is needed because i already have 7 UTXO.

**Comment by Holgi2402** [comment]
i`ll like to test, but the error is still present. Do you need anything more from me to work on this issue?

**Comment by Holgi2402** [comment]
area/wallet

**Comment by Holgi2402** [comment]
area/loans

**Comment by Holgi2402** [comment]
sorry, but i don`t know how to put a label on the issue

**Comment by thedoublejay** [comment]
@Holgi2402 Hi no worries, just to confirm you have 7 UTXO and some tokens right? And trying it on testnet but still fails? Maybe you can provide a screenshot of the error so we can further investigate. Thank you!

**Comment by Holgi2402** [comment]
you can`t take a screenshot of the whole Error because you have to swipe 4 times to see the whole error. Because of this i posted the whole error description in the issue

**Comment by thedoublejay** [comment]
Hi @Holgi2402 can you check if this issue still persists on your end?

**Comment by Holgi2402** [comment]
Hi @thedoublejay, now it worked fine. The issue can be closed. Thank you
