### ISSUE TITLE
`tech` - implement `babel-plugin-transform-remove-console`  to remove console log on prod builds

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1887]
#### What would you like to be added:
`console.log` statements can be a blocker on the JS thread for React Native. We can add this babel plugin to ensure that prod builds doesn't have console.logs when generated. Refer to the links below:

https://babeljs.io/docs/en/babel-plugin-transform-remove-console/
https://reactnative.dev/docs/performance#using-consolelog-statements

**Comment by chloezxyy** [comment]
this plugin has a dependency on colors, won't be able to use it for now - will find for alternative package instead
