### ISSUE TITLE
`e2e` - settings - dark mode toggle

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1888]
#### What would you like to be added:
From the settings page, we have a toggle for light/dark mode. We would like to have a test to check this scenario. 

Add a test to check when switching to light, it activates light theme. Same with Dark theme. Since we don't have snapshot testing yet, let's test these things:

- [x] On light mode, check if sun icon is activated. Same with dark mode
- [x] On switching, check if the opposite icon is activated
- [ ] Check bottom nav if it changes background and icon colors

**Comment by chloezxyy** [comment]
Unable to add test for bottom nav as there is no related attributes to use

**Comment by chloezxyy** [comment]
Unable to add test the last case on bottom nav as there are no related attributes to use
