### ISSUE TITLE
"Your vaults" and "Your pool pairs" not updated after switching addresses

### ISSUE THREAD

**Issue by igrex** [DeFiCh/wallet#1915]
#### What happened: 
I have multiple addresses to manage different liquidity mining pools and vaults separately on the mobile wallet on Android (v0.22.0). Switching between the addresses leads to data not being displayed correctly in the areas "Your vaults" and "Your pool pairs". The displayed vault or pool pairs that belong to the previously selcted address are still shown instead. As a workaround you can select "swap" and immediately go back in the area "Your pool pairs" or select "Browse loan tokens" and immediately go back in the area "Your vaults". Or you can just restart the app. 

#### What you expected to happen:
When switching addresses, all relevant screens should display only data relevant for the selected address. 

#### How to reproduce it (as minimally and precisely as possible): 
Create a second address, create a vault or add token to a lm pool pair and then switch addresses. 
 
#### Anything else we need to know?:
Just a question: How can I as an experienced Java developer (20+ years) find a way into DeFiChain coding ;-)

**Comment by igrex** [comment]
/area/app

**Comment by igrex** [comment]
/area/app

**Comment by igrex** [comment]
> @igrex: There are no 'area' labels on this issue. Adding an appropriate label will greatly expedite the process for us. You can add as many area as you see fit. **If you are unsure what to do you can ignore this!**
> 
> You can add area labels by leaving a `/area` comment.
> 
> Details

`/area/app`

**Comment by izzycsy** [comment]
Hi @igrex , thanks for opening this issue, please give us time to investigate.
