### ISSUE TITLE
Error Code 0: Cannot payback this amount ... (DUSD)

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFiCh/wallet#1932]
DefiChain Light Wallet v0.22.0

I have a active Vault with open DUSD loan (5535 USD), (
Vault is Min. 150% Collateralization, current ratio is 285%
I have 2830.12 DUSD free available in my wallet.
I have 1136 DFI (Token) free available in my wallet and 10 UTXO.

I want to paypack 2800 DUSD to my loan.

Issue:
Every time I submit the payback (2800 DUSD) I get Error message "Error Code 0: Cannot payback this amount of "

How to:
- Go to Manage Loans/Loans
- Click Payback Loan 
- 5535.60 DUSD is prefilled in "How much do you want to pay back"
- change to 2800 DUSD (available 2830.12 DUSD)
- Click CONTINUE
- Transaktion Details will be displayed and new Resulting Collateralization (577.57%)
- Click confirm Payment
- Sign Transaction with Code
- Transaction authorized will be displayed
- then "Error Code 0: Cannot payback this amount of " will be displayed

Expected:
- Transcation should be prozessed without error
- Expect to see a valuable error message if eny error 

I tried it multiple times throughout the day but allways same error.

What is wrong here?
I urgently need to repay the loan.
What to do now?  

Hint:
I recently changed my loan scheme from 200% to 150% with no issues. Loan was always overcollateralized.

![img1](https://user-images.githubusercontent.com/77509687/149805461-9c1d82d9-5af8-4d9b-a574-8d7e6ac4a9d9.jpg)
![img2](https://user-images.githubusercontent.com/77509687/149805465-2c3cec3a-8fd6-47f6-bda9-ba1f11ea7a61.jpg)
![img3](https://user-images.githubusercontent.com/77509687/149805480-2d125f6b-68b6-40ec-891b-2e91b9ec65be.jpg)
![img4](https://user-images.githubusercontent.com/77509687/149805488-16cbadb7-c7ad-498c-a9b2-7cd8133dfa24.jpg)
![img5](https://user-images.githubusercontent.com/77509687/149805498-d83433ce-fb17-4482-bfd2-346e2965e528.jpg)
![img6](https://user-images.githubusercontent.com/77509687/149805512-ec84492b-46f2-47c5-986d-78f1aa242466.jpg)

**Comment by Darkman-Q-Tester** [comment]
Update:
I tested further and found out that although I can't pay back all the available DSUD at once, I can do it in smaller pieces. 
So instead paying back 2830 DUSD at once I tried to pay back 1000 and so on. Sometimes it worked without issue sometimes it did not worked with same error as descripted in this bug.
Here are the payback transactions I did or tried to do:
1000 worked
1000 worked
830 failed
500 failed
100 worked
230 failed
100 worked
100 failed
remaining available DUSD = 630.12
400 failed
100 failed
250 failed
50 failed
123 failed
Could not manage to pay back more. Available DUSD = 630.12

It looks like that how much you can pay back is purely random, can't see a pattern.
It should be possible to pay back any outstanding amount.

**Comment by thedoublejay** [comment]
Hi @Darkman-Q-Tester, there's an going discussion on this issue regarding this - https://github.com/DeFiCh/wallet/issues/1623

**Comment by thedoublejay** [comment]
HI @Darkman-Q-Tester, Fort Canning Hill is now live. Partial payment for loans should work now.
