### ISSUE TITLE
#1827 `QA` - `token icon` - update all token icons across the app

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#1933]
Related: #1827 

Acceptance Criteria: All tokens to be updated

**Comment by dwivedinalin** [comment]
**Acceptance Criteria:**. To verify the token icon has a black background for both light mode and dark mode 

`Android:`
- [ ]  Light Mode > Balance > DEX > Your pool pairs > Verify token icon background
- [ ]  Light Mode > Balance > DEX > Browse pool pairs > Verify token icon background
- [ ]  Light Mode > Balance > DEX > Swap page > Verify token icon background
- [ ]  Light Mode > Loans > Borrow Loan Tokens 
- [ ]  Light Mode > Balances > Send > Verify Token Modal
- [ ]  Light Mode > Balances > Send > Confirm Page


`iOS:`
- [ ]  Dark Mode > Balance > DEX > Your pool pairs > Verify token icon background
- [ ]  Dark Mode > Balance > DEX > Browse pool pairs > Verify token icon background
- [ ]  Dark Mode > Balance > DEX > Swap page > Verify token icon background
- [ ]  Dark Mode > Loans > Borrow Loan Tokens 
- [ ]  Light Mode > Balances > Send > Verify Token Modal
- [ ]  Light Mode > Balances > Send > Confirm Page
