### ISSUE TITLE
front matters of light wallet

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#196]
#### What would you like to be added:

- Icons for iOS/Android and etc.
- App Store banner images and etc.

> Where can I get the assets for them?

/triage accepted
/priority important-soon
/area ui-ux
/assign @aentan @jtlntno-cake

**Comment by thedoublejay** [comment]
@aentan @jtlntno-cake regarding this topic, this page might help - 
1. Overall icons - https://docs.expo.io/guides/app-icons/
2. Playstore Preview - https://support.google.com/googleplay/android-developer/answer/9866151?hl=en
3. App Store - https://developer.apple.com/app-store/marketing/guidelines/
