### ISSUE TITLE
allow `DFI` payment for DUSD loans

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#1965]
#### What would you like to be added:
Based on https://github.com/DeFiCh/dfips/issues/99, we would like to allow payment of DUSD loans only with DFI.
Additional context: https://github.com/DeFiCh/ain-private/issues/3

When paying using DFI, there's a 1% fee imposed. Need to have this design as well.

Requirements:

- [ ] Add a feature flag which will be set to Public
- [ ] Add this feature only for DUSD loans
- [ ] Need to check on the API on which parameters to pass if DFI is used as loan payment
- [ ] E2E tests
- [ ] When paying using DFI, there's a 1% fee imposed

![image](https://user-images.githubusercontent.com/25013382/151474071-3d354952-00c8-4ba1-82c7-b58f9839c1c4.png)

**Comment by ngyingzhong** [comment]
## Translations

**DE**
```
Loan details = Details zum Darlehen

With interest = zzgl. Zins

How much of the loan do you want to pay? = Wie viel des Darlehens willst du zurückzahlen? 

Select payment token = Token für die Zahlung auswählen

A 1% fee is applied when you pay with DFI = Wenn du mit DFI bezahlst, wird eine Gebühr von 1% erhoben

Read more = Mehr dazu

Amount to pay = Zu zahlender Betrag

Resulting (token; e.g. DFI or DUSD) balanced = Ergibt (DFI oder DUSD) 

Vault = Vault

Excess amount = Überschüssiger Betrag

Paying (amount) as loan payment. = Rückzahlung eines Darlehenbetrags von (amount)
```

**FR**
```
Loan details = Détails du prêt

With interest = ac intérêts de

How much of the loan do you want to pay? = Quelle part du prêt voulez-vous rembourser?

Select payment token = Sélectionner le token de remboursement

A 1% fee is applied when you pay with DFI = Des frais de 1% sont appliqués quand vous payez en DFI

Read more = En savoir plus

Amount to pay = Montant à payer

Resulting (token; e.g. DFI or DUSD) balanced = Tokens (DFI ou DUSD) restant

Vault = Vault

Excess amount = Montant excédant

Paying (amount) as loan payment. = Paiement de (amount) en remboursement du prêt
```

**ZHT**

Pending

**ZHS**

Pending
