### ISSUE TITLE
`Bottom Drawer` for displaying transaction and network activity

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#201]
#### What would you like to be added:

Instead of using the navbar which is size fragmented and has a different design language in each native platform. We should use Bottom Tab Bar and have a Drawer/Fold above that tab bar instead.

/area ui-ux

**Comment by fuxingloh** [comment]
We can use `store` to hold transaction & network activity since it's a global state

**Comment by fuxingloh** [comment]
For displaying of transaction and network activity:

Transactions are only confirmed after it's included in a block. Hence displaying the transaction until it gets confirmed. A pending transaction.

Transactions and network activity; block ticking forward is related as the network is not ticking forward or unable to find a connection.

Both pieces of state should be displayed about BottomTab

```
┌───────────────────────────────────────┐
│                  ...                  │ 
┌─────────┬─────────┬─────────┬─────────┐
│    A    │    B    │    C    │    D    │
```

**Comment by thedoublejay** [comment]
@fuxingloh ok so basically it will look like something like this but located at the bottom
![image](https://user-images.githubusercontent.com/25013382/124859000-a7c0d400-dfe1-11eb-865b-ec8f6d74c2b2.png)


Some questions about the flow:
1. I assume the flow would be: (Let me know if it's what expected)
- Hidden in general
- On any transaction, it will be displayed as long as there's a network request
2. Can we expand it? Like when you click, it will open a more detailed page where you can copy the txid, redirect to explorer and other details for the request

**Comment by fuxingloh** [comment]
Yup it's

1. Hidden by default
2. With any pending transaction
3. Unable to connect to Whale

**Comment by fuxingloh** [comment]
For expanding, ideally yes, but not within this scope. We can create another issue to track that.
