### ISSUE TITLE
`auctions` - update collateral values from oracle to DEX

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2029]
#### What would you like to be added:
In the Auction details page, we would like to update the collaterals USD value to use DEX value instead of Oracle. 

![image](https://user-images.githubusercontent.com/25013382/151472229-9f3d3768-311f-4af0-9e12-837b6fa7bc91.png)

**Comment by kyleleow** [comment]
This will also be blocked by #2032
