### ISSUE TITLE
`announcements` - integrate with `status.defichain.com` to display alerts on incidents and maintenance

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2058]
#### What would you like to be added:
Related to https://github.com/DeFiCh/wallet/issues/1849, as a second iteration, we can utilize `status.defichain.com` to display in the event of any incidents or maintenance from the API side. The order of priority will be as follow:

1. Emergency
2. Incidents
3. Maintenance
4. Announcements

Use https://status.defichain.com/api/v2/summary.json as reference. Parse it to use `incidents` or `scheduled_maintenances`

- [ ] Add a button from DeFi Testing screen (Top up UTXO etc.) that will trigger the empty incidents/scheduled_maitenance so QAs can check.

Edit (@pierregee): For all possible props/values - https://metastatuspage.com/api#status

**Comment by jtlntno-cake** [comment]
Current design iteration link. Copy content for each is TBC soon. 
https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=7541%3A135750

cc: @ngyingzhong @thedoublejay @pierregee

**Comment by kyleleow** [comment]
> Add a button from DeFi Testing screen (Top up UTXO etc.) that will trigger the empty incidents/scheduled_maitenance so QAs can check.
Due to the technical challenge of intercepting API, this particular button will be deferred to future releases and will not be address in #2150
