### ISSUE TITLE
Deprecate `NumberText` in components/index.ts

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#208]
Remove NumberText in `components/index.ts` and all implementation that uses it (transaction screen). It's an over-abstraction that shouldn't be introduced in the first place.

/triage accepted
/area core
/assign @ivan-zynesis 
/priority important-soon

**Comment by thedoublejay** [comment]
@fuxingloh I have removed this on my PR - https://github.com/DeFiCh/wallet/pull/202
