### ISSUE TITLE
Performance issues since auctions were added to Android App

### ISSUE THREAD

**Issue by MTNST-AL** [DeFiCh/wallet#2112]
#### What happened:
Since the auctions are live as non beta feature, the app is very laggy and often shows connection outages.
All interactions with the UIs feel like they have a 0.5s delay which was not present with previous versions. The overall snappy feeling for previous versions is gone.

Devices where these delays happen:
- Samsung Galaxy S20+
- Samsung Galaxy Tab S7
- Amazon Fire 10

#### What you expected to happen:
That the UI stays as smooth as it was on 0.8 or 0.9

#### How to reproduce it (as minimally and precisely as possible):
Install v.0.8 and compare the overall smoothness and delays to v.11

#### Anything else we need to know?:
This is my first public github issue, sorry if i missed anything

**Comment by thedoublejay** [comment]
Hi @MTNST-AL, thanks for the feedback. We will be working on these performance issues soon.

**Comment by thedoublejay** [comment]
Hi @MTNST-AL, we have introduced some improvements with `1.3.0`. Please have a look and let us know if you noticed any difference.
