### ISSUE TITLE
Passcode prompt disappears occasionally when confirming txns.

### ISSUE THREAD

**Issue by LuisAsano** [DeFiCh/wallet#2139]
#### What happened: When performing any txn such as dex swaps or adding liquidity the passcode prompt will dissappear before being able to key in passcode and will be stuck on the screen(see screenshot attached). Even after pressing the back button and returning to the txn page it remains in that state. The only workaround for now is killing the app and restarting the entire txn which most of the times is a minor hassle but during periods of price volatility can be a bigger issue.

OS: Android 11
Phone model : Samsung note 20 ultra

#### How to reproduce it (as minimally and precisely as possible): It happens randomly and I have not been able to replicate it by force. I have noticed it happens more frequently when trying to perform multiple txns consecutively like utxo swap>dex swap> add liquidity

(Screenshot of interface when issue happens)
![Screenshot_20220209-113800_DeFiChain Wallet](https://user-images.githubusercontent.com/79193414/153118178-f8100863-65dc-42f5-bca6-68a6b019e86a.jpg)

**Comment by thedoublejay** [comment]
Will be closing this in favor of #2175
