### ISSUE TITLE
Next Collateralization ratio displayed incorrectly

### ISSUE THREAD

**Issue by defidone** [DeFiCh/wallet#2144]
#### What happened:
The next collateralization ratio in the light wallet only ever shows the current ratio. The correct one is on Defiscan. 

#### What you expected to happen:
Correct representation of the next Collateralization ratio

#### Anything else we need to know?:
System: IOS

**Comment by thedoublejay** [comment]
Hi, this one will be fixed on the next app update. Thanks!
