### ISSUE TITLE
When paying back loan limit the amount that can be entered as loan repayment

### ISSUE THREAD

**Issue by dougl888** [DeFiCh/wallet#2145]
#### What UI/UX improvements would you like to be implemented: 
A few things When repaying back loan using DFI 
1) Input field value should be denominated in the chosen repayment token DFI  (raised in #2121)
2) Available amount should display the available balance of the token in the wallet (DFI or DUSD) depending on the repayment token.
3) Max and 50% button should be calculated token required according to the loan balance, and indicate if there isnt enough in the wallet.
4) Excess amount and Resulting balance doesnt consider overpaying of the loan using DFI, and what will be returned back to the wallet in such case.

#### Why is this needed:
Better UX 

#### Which component/screens does this concern?:
Light Wallet Manage Loan

#### Anything else we need to know?:
![image](https://user-images.githubusercontent.com/99323924/153176993-0a2f0271-2ab3-4033-9cbc-792f1f451b3b.png)

**Comment by pierregee** [comment]
Hi @dougl888 , thank you for reporting! we are in discussion with UX behaviour related to this
