### ISSUE TITLE
UI Element uninteractable for automation

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#2164]
#### What happened:
Token list is un-interactable for selection.

#### What you expected to happen:
Should be able to select tokens i.e DFI, dBTC etc

#### How to reproduce it (as minimally and precisely as possible):
DEX > SWAP > Try to check proper attributes are added to the token list i.e name, id, name, text

#### Anything else we need to know?:

<img width="1440" alt="Screenshot 2021-12-29 at 2 07 16 PM" src="https://user-images.githubusercontent.com/32018980/153808591-cd8c7930-dd98-4bc0-96e0-483e940b8d86.png">

> Post changes to be verified on appium inspector whether element is interactable or not

**Comment by rox1338** [comment]
Tried to reproduce on Android and web but didn't succeed.
@dwivedinalin could you be more specific?
