### ISSUE TITLE
`transaction passcode` - restart transaction

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2175]
#### What would you like to be added:
Current user flow:
1. User proceeds with a transaction (e.g, Converting, Add Liquidity, Swap etc.)
2. Submit button will be disabled for a while, then it will display the passcode prompt

Scenario A: Passcode prompt displayed properly. User will be able to proceed with their transaction.
Scenario B: Passcode prompt doesn't show. Submit button will be disabled. Users will not be able to proceed with other transactions (as we only allow one transaction for now)

Thing to solve is:
In the event where passcode prompt doesn't display, allow users to be able to "restart" their transaction.

Linked https://github.com/DeFiCh/wallet/issues/2139

https://www.youtube.com/watch?v=1JUbhJ9KZEU

**Comment by jtlntno-cake** [comment]
[Sharing prototype for this flow](https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?page-id=6556%3A133899&node-id=7857%3A111398&viewport=241%2C48%2C0.93&scaling=scale-down&starting-point-node-id=7857%3A111398&show-proto-sidebar=1)

In this particular example, I used 5 seconds for demonstrative purposes only - not prescripting it as there may be technical considerations in the length of the waiting time the user has before restarting his/her transaction.
