### ISSUE TITLE
`Balances` - loading icon not visible

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#2238]
![image (2)](https://user-images.githubusercontent.com/65014479/155087284-877fadfb-3341-4730-8616-50ff5e052795.png)

#### What happened:
• Loading icon is not visible

#### What you expected to happen:
• Loading icon should be visible

#### How to reproduce it (as minimally and precisely as possible):
• `Balances` > pull screen downwards to trigger reloading

#### Anything else we need to know?:
**Device:** iPhone 13 Pro Max
> Suggestion: Update colour across devices to make it more visible

**On Android:** 
![1645515524696](https://user-images.githubusercontent.com/65014479/155087515-cd0ca84d-2756-41ba-a831-85678f5bb6c4.jpg)
![1645515524714](https://user-images.githubusercontent.com/65014479/155087520-8103a89a-c716-4526-af2c-5837f6416549.jpg)

**On iOS:**
![IMG_0931](https://user-images.githubusercontent.com/65014479/155087561-50fc97f2-511e-467a-96a8-b879da41888a.jpg)
![IMG_0932](https://user-images.githubusercontent.com/65014479/155087567-77892364-ae57-435f-aadf-4020845ca837.jpg)

**Comment by kyleleow** [comment]
@izzycsy can you still reproduce this?

**Comment by izzycsy** [comment]
Cannot be reproduced, issue resolved. @kyleleow
