### ISSUE TITLE
`DEX` - when searching with filters, only include the filtered tokens

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2271]
#### What would you like to be added:
When searching with a token filter (e.g, DUSD pair, DFI pair), tokens which are not part of the filtered set are still displayed.

Search only from the filtered set and not on the entire token list.

**Comment by kyleleow** [comment]
I think searching shouldn't be bounded by filters. If a searching is bounded by filters, then the filter information should be clearly displayed / informed in the searching UI, else the user would not know the current filter while searching
<img width="315" alt="image" src="https://user-images.githubusercontent.com/40191153/155646720-50532d31-7227-479d-bdea-b5e83b969239.png">

**Comment by kyleleow** [comment]
However, another bug that is related to this is that, cancelling a search after typing at least one character would reset the all pool pairs regardless of which button filter is active

Steps:
- DEX screen, tap `DUSD pairs` filter
- Tap search icon from top left
- Enter `a`
- Tap `X` to cancel search
- Noticed the pool pairs displayed under `DUSD pairs` filter includes all pool pairs

**Comment by thedoublejay** [comment]
> I think searching shouldn't be bounded by filters. If a searching is bounded by filters, then the filter information should be clearly displayed / informed in the searching UI, else the user would not know the current filter while searching <img alt="image" width="315" src="https://user-images.githubusercontent.com/40191153/155646720-50532d31-7227-479d-bdea-b5e83b969239.png">
> 
> One example we can refer is from apple website, the search will always bypass the tab filtering <img alt="image" width="492" src="https://user-images.githubusercontent.com/40191153/155647365-0141093d-3142-4409-862a-47eee48ecc2f.png"> link: https://www.apple.com/my/search/ipad?src=serp

Yeah but on your example, you're on searching on "Explore". Same as searching in All. If you search on Accessories, you don't see the iPad but only the accessories related to it. Same with when you are on DFI/DUSD pair.

**Comment by thedoublejay** [comment]
> However, another bug that is related to this is that, cancelling a search after typing at least one character would reset the button filter and includes all pool pairs
> 
> Steps:
> 
> * DEX screen, tap `DUSD pairs` filter
> * Tap search icon from top left
> * Enter `a`
> * Tap `X` to cancel search
> * Noticed the pool pairs displayed under `DUSD pairs` filter includes all pool pairs

For this, let's create an issue for it

**Comment by kyleleow** [comment]
> Yeah but on your example, you're on searching on "Explore". Same as searching in All. If you search on Accessories, you don't see the iPad but only the accessories related to it. Same with when you are on DFI/DUSD pair.
The accessories that you see is the searching suggestion but not the result, when you click enter after typing `ipad` in accessories, it will still bring you to `explore tab` and show the product

**Comment by jtlntno-des** [comment]
I would suggest the search function in the header to bypass any content filters as (1) the user's primary intent in using is to find a LM pair so creating another layer of complexity may confuse user (e.g. user don't see a DFI pair just because he/she is on DUSD pair filter), and (2) another intended function of the search in the header is to be a more precise filter function
