### ISSUE TITLE
indicator for DEX and Oracle prices

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2288]
#### What would you like to be added:
We are displaying prices across the app. Sometimes, we're using DEX or Oracle. It's not clear to the users from which source are the prices calculated.

Since most are using DEX prices, there will not be any change for DEX prices. For Oracle, we will use this icon.

- [ ] If the price is from oracle. display the globe icon
- [ ] Clicking on the icon, it will show a tool tip to explain the purpose of it. Will provide final copy 
<img width="213" alt="image" src="https://user-images.githubusercontent.com/25013382/166874989-d3763810-2836-4e78-9225-396e44b93ae2.png">
- [ ] Need to list out all screens that uses oracle prices. TODO @chloezxyy can you list them here

Prototype:
https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/BR-PRD---Mobile-Light-Wallet?page-id=6556%3A133899&node-id=10106%3A204883&viewport=241%2C48%2C0.09&scaling=scale-down&starting-point-node-id=11698%3A208247&show-proto-sidebar=1

**Comment by thedoublejay** [comment]
https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/BR-PRD---Mobile-Light-Wallet?page-id=6556%3A133899&node-id=10106%3A204883&viewport=241%2C48%2C0.09&scaling=scale-down&starting-point-node-id=11698%3A208247&show-proto-sidebar=1

**Comment by chloezxyy** [comment]
Screens with dex prices:
1. Portfolio - Total Portfolio Value - loans 
2. Loans - Your vaults (Total Collateral (USD), Total Loans(USD)), Browse loan tokens (Price (USD))
