### ISSUE TITLE
LightWallet: Frontend Responsive Layout Error

### ISSUE THREAD

**Issue by Motopasion21** [DeFiCh/wallet#2289]
#### What happened: Frontend responsive error annual interest pool pairs on Huawei Pro30.

"DUSD-Paar" - double-spaced
"Jahreszins:" - double-spaced
"123%" - double-spaced

Someone has reported a similar problem with an Iphone 11 Pro, too

![Screenshot_20220228_111709](https://user-images.githubusercontent.com/100567503/155965756-2a8bad8a-850c-485b-a7a1-2220ac301f3a.jpg)

**Comment by arakis2022** [comment]
Same problems with iPhone XS and Samsung 6 edge

**Comment by thedoublejay** [comment]
Hi @Motopasion21 @arakis2022, thanks for raising the issue! We will take a look at this.
