### ISSUE TITLE
`wallet avatars` - update avatar design

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2316]
#### What would you like to be added:
Update wallet avatar designs. Pending final designs from design team.

**Comment by jtlntno-des** [comment]
Reference: https://boringavatars.com/

We would use the style `bauhaus` and listed below are the following hex codes:

Light mode:
- #EE63B9
- #346DCD
- #F5D547
- #09200D
- #2FA66B

Dark mode:
- #CD5099
- #4471BA
- #E1C94E
- #F0F7F1
- #6CC99C

![image](https://user-images.githubusercontent.com/85162376/156526279-3ed2370a-4d6e-4082-a1c9-62539ad09a84.png)

![image](https://user-images.githubusercontent.com/85162376/156526573-632522a3-d088-446a-9825-8752f6573fb6.png)
