### ISSUE TITLE
Auctions - Unable to `QUICK BID` from main screen

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#2327]
#### What happened:
• Unable to `QUICK BID` from main Auctions screen
• Able to `QUICK BID` if click into Auction card

#### What you expected to happen:
• User with enough balance should be able to `QUICK BID` / `PLACE BID`

#### How to reproduce it (as minimally and precisely as possible):
• Check balance is sufficient for desired auction
• Auctions > Select `QUICK BID`  > `QUICK BID` button remains grey
![220304 v1 4 1 - iOS - Auctions -  Unable to QUICK BID1](https://user-images.githubusercontent.com/65014479/156744338-ef93997e-3028-47f3-98cb-26cd8c04b3e4.PNG)

• Auctions > Click into auction > Bid history tab > Select `QUICK BID` > `QUICK BID` button is active
![220304 v1 4 1 - iOS - Auctions -  Unable to QUICK BID2](https://user-images.githubusercontent.com/65014479/156744336-f519e263-159a-4dbf-8dfc-80bbd74165a4.PNG)

• Auctions > Click into auction > Collateral for auction tab > Select `QUICK BID` > `QUICK BID` button is active
![220304 v1 4 1 - iOS - Auctions -  Unable to QUICK BID3](https://user-images.githubusercontent.com/65014479/156744332-5b098e39-d213-4fa8-b5c2-c4c39d356e7c.PNG)

• Auctions > Click into auction > Auction details tab > Select `QUICK BID` > `QUICK BID` button is active
![220304 v1 4 1 - iOS - Auctions -  Unable to QUICK BID4](https://user-images.githubusercontent.com/65014479/156744313-bfc4fd46-84e1-4ff1-a5df-f7ebf26a94d8.PNG)

**Comment by thedoublejay** [comment]
@izzycsy Can you help us give more examples/scenarios to replicate this? We're having a hard time reproducing the issue
