### ISSUE TITLE
`portfolio` - sorting tokens

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2338]
#### What would you like to be added:
Ability to sort tokens based on these criterias:

- [ ] Highest Value
- [ ] Lowest value

![image](https://user-images.githubusercontent.com/25013382/157795023-96b44d84-6fdf-436f-b652-028c0e7961aa.png)

@chloezxyy Let's use Highest Value/Lowest Value. Let's not add USD as future iterations can be switched to BTC, Euro etc.

**Comment by thedoublejay** [comment]
@chloezxyy something to take note, how would it look like with translated labels

**Comment by chloezxyy** [comment]
Adding in design link for easy reference:
https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=6556%3A133899

**Comment by thedoublejay** [comment]
Put the list of tokens that we have
