### ISSUE TITLE
`loans` - allow DUSD payment of any loans

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2352]
#### What would you like to be added:
With the upcoming hard fork, we would like to have the ability to pay other loans with DUSD. Same concept as https://github.com/DeFiCh/wallet/issues/1965

**Comment by ngyingzhong** [comment]
Design prototype: https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?page-id=6556%3A133899&node-id=9394%3A170709&viewport=241%2C48%2C0.47&scaling=scale-down&starting-point-node-id=9394%3A170709&show-proto-sidebar=1

@jtlntno-des

**Comment by jtlntno-des** [comment]
Updated [prototype link](https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?page-id=9531%3A297427&node-id=9593%3A188982&viewport=241%2C48%2C0.7&scaling=scale-down&starting-point-node-id=9593%3A188982&show-proto-sidebar=1) to show disabled state on selecting a payment token in preparation for the hard fork
