### ISSUE TITLE
`vault share` - display default values on 0 or max amount

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2361]
#### What happened:
With the new topic https://github.com/DeFiCh/wallet/issues/1867, there are two cases where we don't display a vault share. Display N/A for both

- [ ] When there are no collaterals yet, try to input "0". It will not display any vault share. 
![Image from iOS (1)](https://user-images.githubusercontent.com/25013382/157350800-db5c5dd4-cf8b-42a5-8207-96a2e165a479.png)

- [ ] When there is exactly one collateral, try to remove the entire amount of collateral. 
![Image from iOS](https://user-images.githubusercontent.com/25013382/157350867-1bab6c5f-0da2-4bab-8c2b-b284e2f100c4.png)

**Comment by chloezxyy** [comment]
Scenario:
To display 0.00% when removing the max amount of collateral when there are more than 1 collaterals in total.
To display N/A when removing the max of only same existing collateral when there is only 1 collateral in total.
