### ISSUE TITLE
`loans` - allow DUSD to contribute to 50% of total collateral

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2371]
#### What would you like to be added:

This feature allows DUSD to be counted towards the DFI requirement for vault collateral, where collateral factor = 99%. 

Simply put, DUSD proportion + DFI proportion ≥ 50%

Examples

30% DFI, 40% DUSD, 30% dBTC :white_check_mark: 

50% DUSD, 50% dBTC :white_check_mark: 

100% DUSD :white_check_mark:

For the upcoming hard fork, we will include DUSD on the 50% calculation check. These are checked on two scenarios:
- [x] Removing collateral
<img width="370" alt="Screenshot 2022-03-21 at 3 36 04 PM" src="https://user-images.githubusercontent.com/25013382/159220372-28d88346-56d3-461e-8896-b9e3a5322974.png">

- [x] Taking a loan
<img width="450" alt="Screenshot 2022-03-21 at 3 35 46 PM" src="https://user-images.githubusercontent.com/25013382/159220339-d14ea335-288a-4a28-8261-f21f2aa0cef9.png">

- [x] Add a feature flag since this will only be enabled after the hard fork block

**Comment by jtlntno-des** [comment]
Updated per feedback to add vault collateral sum of DFI and DUSD (showing an error state and the normal state)

![image](https://user-images.githubusercontent.com/85162376/160341733-d5baa7d4-262e-495c-88b2-49ffd12993e1.png)

![image](https://user-images.githubusercontent.com/85162376/160341926-5a5fd221-d384-47ea-81e0-3a7eddb17688.png)

**Comment by ngyingzhong** [comment]
Latest update on drawer modal. 

What changed: 
- Removed vault share in the modal - focusing the attention of the modal on vault requirement
- Vault requirement only pertains to DFI and DUSD - however, we will still display this component to all the other collateral tokens as they still affect the calculation of vault requirement. The /50% in the right part is fixed to 50% as the vault requirement needed to be fulfilled
- Updated designs below are applied to both add/remove collateral tokens and to all collateral tokens (even dBTC/USDT/USDC)

Screens: https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=9531%3A297428

![image](https://user-images.githubusercontent.com/66629826/160395357-11b519d3-e27f-494f-9ee2-6b74b1045d92.png)
![image](https://user-images.githubusercontent.com/66629826/160395376-faa7197a-a9cb-4c1d-af8d-4e18649aece7.png)


@jtlntno-des @thedoublejay
