### ISSUE TITLE
`portfolio` - empty state

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2387]
#### What would you like to be added:

![image](https://user-images.githubusercontent.com/25013382/157825980-aa958678-e85b-44c3-8f1f-0c96c3eee3ee.png)

**Comment by 0ptim** [comment]
Maybe there could be a link/button added like _"Where can I get DFI?"_.
- The link could display a list similar to the one on [defichain.com](https://defichain.com/) on the top right.
- Or go to [this](https://defichain-ecosystem.com/) page.
- Or [this](https://fivesteps.defichain.ac/) one.

![empty_portfolio_addition](https://user-images.githubusercontent.com/25133399/159648568-ac52b525-06b2-448d-bb44-f96443e593bd.png)

**Comment by thedoublejay** [comment]
Hi @0ptim, thanks for the suggestion! We have discussed it also briefly with this issue - https://github.com/DeFiCh/wallet/issues/2335 but we haven't updated the design for it. We will forward your suggestion to the design team
