### ISSUE TITLE
implement `coachmarks`

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#245]
#### What UI/UX improvements would you like to be implemented: 
Implement coachmarks on initial start of user application. It will highlight the most important features and some guides on what to do. 

Might be useful especially for new users @fuxingloh @jtlntno-cake @aentan 

Ex. https://github.com/mohebifar/react-native-copilot

**Comment by fuxingloh** [comment]
I don't think we should do this, rather have UX that are obvious.

**Comment by aentan** [comment]
> I don't think we should do this, rather have UX that are obvious.

Agree.

**Comment by fuxingloh** [comment]
> > I don't think we should do this, rather have UX that are obvious.
> 
> Agree.

/close

**Comment by thedoublejay** [comment]
@aentan @fuxingloh yup just a suggestion. Obvious UX is relative to each user. Not all users will have basic understanding of all functions etc. Especially when we have more complex features, like Atomic swap
