### ISSUE TITLE
Seed Phrase instead of .bak 

### ISSUE THREAD

**Issue by thbestforyourbizdeployment** [DeFiCh/wallet#2469]
Issue:
hello, ive been using the seed phrase to restore my wallet every time there is a problem. I was told today, that Seed phrase are not working anymore.
I have installed the native app and the saiive.live in Desktop (Linux, OS X and Windows ) same issue using the seed phrase. tried the native app defichain mobile in android same issue.
QUESTION:
What is the most recent version I can download the native desktop app in Linux or Windows to be able to enter my seed phrase and then be able to keep using the backup?

**Comment by thedoublejay** [comment]
Hi @thbestforyourbizdeployment do you mean for the desktop wallet? We never removed the restore option for seed phrase. Only the creation of wallet. You can still use it.

**Comment by thbestforyourbizdeployment** [comment]
Correct, Desktop wallet, it syncs  100% but it never shows any balance, 
Zero balance on all tokens and synthetics.
