### ISSUE TITLE
App Version 1.7.0 is crashing and doesn't starts 

### ISSUE THREAD

**Issue by Kassius84** [DeFiCh/wallet#2505]
#### What happened:
On Telegram in channel DeFiChain EN, two people were reporting the same issue with the latest version of the App 1.7.0. The App does not start and is directly crashing.
 The app cache and data were deleted but still the same issue. 

#### What you expected to happen:
Normal start of the App. 

#### Anything else we need to know?:
Please find some additional information attached.

**Comment by Kassius84** [comment]
![IMG_20220328_231047_160](https://user-images.githubusercontent.com/86849926/160487938-79485e8a-0121-4188-9608-b4a9fc0edc16.jpg)

**Comment by thedoublejay** [comment]
@Kassius84 We are checking the issue

**Comment by thedoublejay** [comment]
@Kassius84 1.7.1 should be out now on Android.
