### ISSUE TITLE
Translation (DE): Current translation for "LP Token" breaks UI

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#2535]
![2022-04-01 14 51 03](https://user-images.githubusercontent.com/65014479/161211015-1fbee427-2561-473b-a5a7-72fd6a95c4a4.jpg)

#### What translation improvements would you like to be implemented:
DE
```
LP tokens = L. Pool-Token
```

#### Which component/screens does this concern?:
• Portfolio

**Comment by rox1338** [comment]
As an Austrian an therefore natural speaker in German, I would prefer "LP Token".
I created a PR: #3184
