### ISSUE TITLE
`DEX` - estimated to receive and total to be swapped - add USD value

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2594]
#### What would you like to be added:
On the pool swap page, when doing swaps. There is a row called "Estimated to receive" and "Total to be swapped". Add a USD value on it.

![image](https://user-images.githubusercontent.com/25013382/164645776-0f55293b-a1d2-4f17-8d0e-de8e238513d5.png)

Layout should look similar to other prices
![image](https://user-images.githubusercontent.com/25013382/164645829-dd96796c-db8d-47ff-94ef-ae304a321f1a.png)

**Comment by thedoublejay** [comment]
@rox1338 You can also check this issue

**Comment by rox1338** [comment]
will have a look
