### ISSUE TITLE
Cannot add ETH as Collateral 

### ISSUE THREAD

**Issue by daffilein** [DeFiCh/wallet#2612]
#### What happened: When adding ETH to a new or existing Vault, I receive the error message attached (Error Code: 0 Negative price (ETH / USD)(code 16))
![WhatsApp Image 2022-04-11 at 01 08 08](https://user-images.githubusercontent.com/85686628/162663671-b0d848a8-7048-44bc-9401-3fcd9e6c47bc.jpeg)

**Comment by thedoublejay** [comment]
Hi @daffilein, there is no active price yet for it and it will only be available after this block - https://defiscan.live/blocks/countdown/1786180

**Comment by daffilein** [comment]
perfect, thank you!

**Comment by daffilein** [comment]
thanks for your quick reply.
