### ISSUE TITLE
100% Token added as collateral doesn't appear at Portfolio  token list page

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#2613]
#### What happened:
While 100% available token is added as collateral token does not appear in token list on portfolio page

#### What you expected to happen:
Token added 100% as collateral should be displayed on Portfolio page

#### How to reproduce it (as minimally and precisely as possible):
Check tokens available (DUSD, dLTC, dBTC)
Add 100 % as collateral

**Comment by kyleleow** [comment]
Being tracked in #2702
