### ISSUE TITLE
`collaterals` - remove collateral from list if active price is 0

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2623]
#### What happened:
During hard forks, we sometimes add collaterals on the list of collateral tokens. Sometimes, when the "price" from the oracle is not ready, users won't be able to add until the price from oracle is live.

To solve this issue, we would like to remove the collateral token on the list of collaterals IF the active price is 0. 

To make it easy, you can develop it on Playground network. You may go to Settings => Network => Playground => Click on Playground again. There will be options there to click/top up tokens. With this, you will be able to create a vault.

The easy way is to just filter the list of collateral tokens if active price is 0.

**Comment by thedoublejay** [comment]
@rox1338 You can check this one, let me know your thoughts about it.

**Comment by rox1338** [comment]
@thedoublejay looks feasible so far. Will have a  closer look tomorrow.
