### ISSUE TITLE
`add liquidity` - go back to token details screen

### ISSUE THREAD

**Issue by kyleleow** [DeFiCh/wallet#2680]
#### What UI/UX improvements would you like to be implemented: 
- After entering `add liquidity` screen from `token details` screen, going back should be `token details`, currently it is going back to `DEX` screen

#### Why is this needed:
- UX consistency

#### Which component/screens does this concern?:
- token details
- add liquidity

#### Anything else we need to know?:
- Add liquidity screen and confirm liquidity screen into `BalancesNavigator`

**Comment by pierregee** [comment]
Also happens to Remove Liquidity from Token Detail Screen of LPs
