### ISSUE TITLE
`welcome screen` - display app version

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2703]
#### What would you like to be added:
Display app version on welcome screen. Currently, there's no way to determine the app version if you're not on wallet context (e.g, About Screen)
![image](https://user-images.githubusercontent.com/25013382/165072866-3358d1fd-9eca-4581-99ac-3119654c46fc.png)

**Comment by rox1338** [comment]
About Screen uses the following terminology: v1.8.2
The mockup uses the following terminology: Version 1.8.2
I think we should unify that and also use Version 1.8.2 in the about screen.

**Comment by jtlntno-des** [comment]
Agree - thanks for the suggestion. This new treatment on the version display is the most updated treatment - of which we can also apply in the About us Screen. Sharing [design links](https://www.figma.com/file/CMoIqpPpzeJTLumlwZNyz8/BR-DSM---Light-Wallet?node-id=3344%3A85289) for assistance

![image](https://user-images.githubusercontent.com/85162376/165685844-26c57c05-d332-4780-8040-e1c1e510db0d.png)
