### ISSUE TITLE
`convert` - tokens vs UTXO screen

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#272]
#### Why is this needed:
Screen to explain Tokens vs UTXO
#### Which component/screens does this concern?:
![image](https://user-images.githubusercontent.com/25013382/125595807-de328d2f-f8db-4250-9c8a-dc14f3b5a52b.png)

**Comment by kyleleow** [comment]
@jtlntno-cake any marvel link for this screen?

**Comment by thedoublejay** [comment]
@kyleleow https://marvelapp.com/prototype/66795j4/screen/80595968
