### ISSUE TITLE
Price Rates - order of token display

### ISSUE THREAD

**Issue by pierregee** [DeFiCh/wallet#2735]
#### What would you like to be added:
The order of the token displayed in price rates should be aligned with https://defiscan.live/
Follow the order of the pairing. If it's dBTC-DFI, then dBTC should be displayed first.
Align with Scan and go with the non-DUSD/DFI token as the “primary” token. Some examples to illustrate:

**dBTC-DFI**
```
Price Rates: 
dBTC = ...
DFI =  ...
```
**dTLSA-DUSD**
```
Price Rates: 
dTSLA = ...
DUSD =  ...
```
**DUSD-DFI**
```
Price Rates: 
DUSD = ...
DFI =  ...
```
![image](https://user-images.githubusercontent.com/13292662/165927200-8287d24a-5fba-4d9d-845e-7b58e7e08b6e.png)

- [ ] Main DEX Screen
- [ ] Check on Swap page if applicable
- [ ] Check on Add Liquidity page if applicable
- [ ] Check on Remove Liquidity page if applicable

#### Why is this needed:
This works better if we want to move towards a proper DEX trading experience

**Comment by thedoublejay** [comment]
@rox1338 In case you're checking, you can take a look at this one.

**Comment by izzycsy** [comment]
![Screenshot_2022-05-20-17-41-24-140_com defichain app](https://user-images.githubusercontent.com/65014479/169501499-4f92b617-c4e0-47ab-810f-46694e2014c2.jpg)

When `Remove Liquidity`, DFI is always on top, we will need to update the display of token order for this under **PRICES** section too.

**Comment by rox1338** [comment]
I already considered that in my PR #2814
