### ISSUE TITLE
Error Code: 0 prompt UI occupied

### ISSUE THREAD

**Issue by fanoack** [DeFiCh/wallet#2744]
I have the following issue in the light wallet: Error Code: 0 prompt UI occupied
This happens when I try to make any action.

Could somebody help me?

**Comment by pierregee** [comment]
Hi @fanoack, is there any ongoing transaction submitted? - this error comes when there is ongoing txn and its not done yet and before that user is trying to initiate next one. Are you in the`playground` network or `mainnet`?

**Comment by fanoack** [comment]
Hi pierregee, Yes that could be I started a payback of a part of my loan. This transaction wasn´t never finished. I am in the mainnet.
Do you have any idea what I can do?

**Comment by fanoack** [comment]
Problem is solved after restart. Thank you
