### ISSUE TITLE
nextCollateral ratio uses DUSD value of 1 in collateral

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/wallet#2754]
When DUSD is added as collateral, its value is fixed at 0.99, but the LW uses a value of 1 for calculating the next ratio.

error happens by using same  "getActivePrice" for loans and collaterals

https://github.com/DeFiCh/wallet/blob/c5dfb71a4ca7e0f418c9bc13f43b96246f13f28e/mobile-app/app/screens/AppNavigator/screens/Loans/hooks/NextCollateralizationRatio.ts#L5-L19

getActivePrice always returns 1 for DUSD
https://github.com/DeFiCh/wallet/blob/c5dfb71a4ca7e0f418c9bc13f43b96246f13f28e/mobile-app/app/screens/AppNavigator/screens/Auctions/helpers/ActivePrice.ts#L6

**Comment by thedoublejay** [comment]
Hi @kuegi we are checking this. Thanks for raising.

**Comment by adrian-schnell** [comment]
@thedoublejay as hint - kuegi also opened this issue for defiscan:
https://github.com/DeFiCh/scan/issues/1175
