### ISSUE TITLE
collateral stucked in vault

### ISSUE THREAD

**Issue by Rolesch** [DeFiCh/wallet#2799]
I accidentally put dETH and dBTC in my vault, without any DUSD/DFI. I did not take any loan. Now I wanted to remove my dBTC to change some part in DFI for the vault. Now the system does not allow me to remove my dBTC due to the 50% rule. But I did not take any loans so far. This is ridiculous. Can you please fix this? Thank you.

**Comment by thedoublejay** [comment]
@Rolesch Which version are you using? Can you provide some screenshots?

Also, if you close the vault, you will get back all your collaterals back.
