### ISSUE TITLE
rename all `balances` files to `portfolio`

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#2809]
#### What would you like to be added:
We have renamed "balances" to "portfolio". To improve coding, let's change all filenames, references etc. from "balances" to "portfolio".

Example, "BalancesScreen" would be renamed to "PortfolioScreen". 

@chloezxyy please list out all the changes, also don't forget to test well.

**Comment by chloezxyy** [comment]
BalancesScreen -> PortfolioScreen
balances -> portfolio
Balances -> Portfolio

1. Folder names
2. File names
3. AppLinking
4. Translations key-value pairs and destination file path
5. E2E test cases description
6. Unit test cases mounted component
