### ISSUE TITLE
Gather list of error messages on light wallet

### ISSUE THREAD

**Issue by Graciaho** [DeFiCh/wallet#2830]
#### Why is this needed:

Related to https://github.com/DeFiCh/wallet/issues/1500

**Comment by thedoublejay** [comment]
1. Insufficient UTXO DFI
2. Not enough balance
3. Price is higher than indicated
4. Insufficient DFI collateral (≥50%)
5. Pool does not have enough liquidity
6. Cannot payback loan due to invalid price
7. No live fixed prices for loan token
8. Vault does not have enough col. ratio

@Graciaho
