### ISSUE TITLE
`auctions` - update collateral values from oracle to DEX

### ISSUE THREAD

**Issue by chloezxyy** [DeFiCh/wallet#2838]
#### What happened:
In the Auction details page, we would like to update the collaterals USD value to use DEX value instead of Oracle.

#### What you expected to happen:
In the Auction details page, collaterals USD value to use DEX value

#### How to reproduce it (as minimally and precisely as possible):
Auctions -> Click on an auction card -> Click on Collateral for auction tab

#### Anything else we need to know?:
Linked to #2029

**Comment by kyleleow** [comment]
Added in PR #2989
