### ISSUE TITLE
`loans` - active loans values overflow in vault card

### ISSUE THREAD

**Issue by kyleleow** [DeFiCh/wallet#2847]
#### What UI/UX improvements would you like to be implemented: 
- To not overflow UI out of bound

#### Why is this needed:
- UI consistency

#### Which component/screens does this concern?:
- Loans screen > Your vaults tab

#### Anything else we need to know?:
![image](https://user-images.githubusercontent.com/40191153/170214637-ba69f1e6-37bf-4ccb-82fb-f4b73bd3acf8.png)

**Comment by thedoublejay** [comment]
@rox1338
