### ISSUE TITLE
`Remove Liquidity` - Negative value

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#2883]
https://user-images.githubusercontent.com/65014479/170932987-c3196ad3-3f65-44ed-908c-12bbf581f5a1.mp4

![Screenshot_2022-05-30-14-45-27-619_com defichain app](https://user-images.githubusercontent.com/65014479/170933647-11490d16-b38d-4a75-b5c9-737aab70ead3.jpg)

#### What UI/UX improvements would you like to be implemented: 
• App should not reflect negative value

#### Which component/screens does this concern?:
App version: v1.12.3
• Remove Liquidity

#### Anything else we need to know?:
To reproduce: 
• Requires 0.00000356 dPLTR-DUSD
• In Portfolio, check to have 0 DUSD
`DEX` > scroll to **dPLTR-DUSD** > `- REMOVE` > input **1%** > `CONTINUE` > scroll to bottom, **Resulting DUSD** will reflect a negative value

**Comment by thedoublejay** [comment]
@rox1338 this one, we can prevent showing negative amounts here

**Comment by thedoublejay** [comment]
@rox1338 I think for now, let's just prevent it on the display side. Or maybe put a minimum of 0

**Comment by pierregee** [comment]
@rox1338 I'll leave this one to you and yea I agree to check if tokenB is DFI first to make sure resulting DUSD won't be affected
