### ISSUE TITLE
`Favorite` icon overlaps with token name

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#2894]
![image](https://user-images.githubusercontent.com/65014479/171130958-d2b64414-20f6-4c5b-9330-b0f192309c18.png)

#### What UI/UX improvements would you like to be implemented: 
Padding for icons when device screen is small

#### Why is this needed:
• On smaller device screens, the `favorite` icon overlaps with token name

#### Which component/screens does this concern?:
DEX

#### Anything else we need to know?:
Only on small device screens

**Comment by thedoublejay** [comment]
This one also @rox1338

**Comment by rox1338** [comment]
Couldn't reproduce it.
So it is either fixed or I am doing something wrong.
@thedoublejay

**Comment by thedoublejay** [comment]
@rox1338 It's for a specific screen size. Might need to re-adjust display to replicate

**Comment by rox1338** [comment]
Yeah, I tried. More details no how to (re)produce this might help. @izzycsy @thedoublejay
