### ISSUE TITLE
Address book `Search` field - Placeholder text typo

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#2952]
![IMG_BC6981C7BD0E-1](https://user-images.githubusercontent.com/65014479/172337869-b2b8092e-f120-4146-8c59-c2efe17d7436.jpeg)

#### What UI/UX improvements would you like to be implemented: 
Placeholder text should be "Search address book”

EN
```
Search Address book = Search address book
```

#### Why is this needed:
Typo: “Search Address book” in search field. Placeholder text should be "Search address book”

#### Which component/screens does this concern?:
Address Book search field

#### Anything else we need to know?:
To reproduce:
`Settings` > select `Address Book` > placeholder text in `Search` field

**Comment by kyleleow** [comment]
This has been fixed in #2947
