### ISSUE TITLE
dAMZN-dUSD pool value wrong

### ISSUE THREAD

**Issue by AndiyNW** [DeFiCh/wallet#2958]
#### What you expected to happen:
Showing similar value as before stock split

#### How to reproduce it (as minimally and precisely as possible):
Have pool

#### Anything else we need to know?:
Nope

**Comment by thedoublejay** [comment]
It's being investigated now on the whale side

**Comment by fuxingloh** [comment]
Fixed in https://github.com/JellyfishSDK/jellyfish/pull/1533
