### ISSUE TITLE
Swap issue with hash but tx not executed

### ISSUE THREAD

**Issue by VanesD95** [DeFiCh/wallet#3008]
#### What happened: 
In the last days we as a Team have experienced a swap issue with different wallets. 
During some swap we correctly recieve the tx hash, but after some block update the balance stays the same as before.
The tx seems to be not executed.

#### What you expected to happen: 
Balance update after tx confirmation.

#### How to reproduce it (as minimally and precisely as possible): 
It casually happens sometimes after the swap.

**Comment by thedoublejay** [comment]
@VanesD95 Hi, until now, your tx is not executed?

**Comment by thedoublejay** [comment]
@VanesD95 Yes it was the first time this was reported. Can you check on https://defiscan.live/ if your tx was successful?

**Comment by VanesD95** [comment]
The tx were successfull on defiscan but the desktop wallet updated the balance after a couple of hours.
