### ISSUE TITLE
`settings` - download a copy of mnemonic seed

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#301]
#### What would you like to be added:
Once user has created a wallet. He should be able to download a copy on his mnemonic seed. Wallet Encryption #57 is a dependency of ticket as there should be a security verification before revealing the mnemonic seed.

**Comment by jtlntno-cake** [comment]
Screen containing the mnemonic seeds can be seen here:

• https://marvelapp.com/prototype/ce4111i/screen/81013174/handoff
• https://marvelapp.com/prototype/ce4111i/screen/81091541/handoff

Some notes:
• We require security measures before displaying the mnemonic words(either passcode, face id or touch id)
• The mnemonic words are displayed within app.

**Comment by thedoublejay** [comment]
@kyleleow For this implementation, you can skip the Passcode validation step first. @ivan-zynesis is currently working on that page, we just add it here once ready.

So for now, the flow would be:
1. Settings Page
2. Click on View Recovery Words
3. Display Recovery Words

**Comment by thedoublejay** [comment]
Pending changes from this issue on jellyfish side - https://github.com/DeFiCh/jellyfish/issues/503
