### ISSUE TITLE
`explorer` URL handling

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#303]
#### What would you like to be added:
For all actions that provides transactions (e.g, Send, Add/Remove Liquidity), we need a way to manage the redirect or open the tx in the explorer. The URL will depend on the network. Whether it's Mainnet, testnet etc.

Example, when click on Send, it opens the Ocean Interface. There's a TX ID there that when you click, it will open the explorer URL.

Create a common method that will open the tx on the dedicated URL depending on the network.

Mainnet - https://mainnet.defichain.io/#/DFI/mainnet/tx/(tx id here)
Testnet - https://testnet.defichain.io/#/DFI/testnet/home/tx/(tx id here)
Playground - https://playground.defichain.com/v0.7/regtest/transactions/(tx id here)

Need to apply these in these components: 
1. OceanInterface 
2. TransactionDetail Page

**Comment by kyleleow** [comment]
@thedoublejay does local playground and remote playground return the same url?
