### ISSUE TITLE
The total auction value (USD) too high

### ISSUE THREAD

**Issue by pawn-police** [DeFiCh/wallet#3041]
#### What happened:
The total auction value (USD) displayed is way too high for this particular auction:
![image](https://user-images.githubusercontent.com/94628327/175369916-1e5109f4-1cc0-4661-8f6f-468792ead863.png)

#### What you expected to happen:
The collateral should be worth somewhere around 50 USD at the time of writing. Not 2443 USD. Here is the same auction batch in defiscan.live without the display issue:
![defiscan](https://user-images.githubusercontent.com/94628327/175372107-196301f9-2864-4f8e-b85b-93fb0ae53869.png)

#### How to reproduce it (as minimally and precisely as possible):
There is only one auction consisting of one batch active currently so it is unclear if this would happen for all the auctions. 
I can reproduce the issue using version 1.14.0 of the wallet on Android.

**Comment by thedoublejay** [comment]
Fixed now with `1.14.2`
