### ISSUE TITLE
`settings` - licenses, privacy policy and terms of use

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#305]
#### What would you like to be added:
Section on the settings page to view Licenses, Privacy Policy and terms of use
#### Why is this needed:

/triage accepted
/priority important-soon
/area ui-ux
/assign @jtlntno-cake

**Comment by jtlntno-cake** [comment]
Do we need to have separate pages for each (licenses, privacy policy and terms of use)? And do we also have the content that we can check for each? @thedoublejay

**Comment by thedoublejay** [comment]
Closing as main ticket will be this one - https://github.com/DeFiCh/wallet/issues/376
