### ISSUE TITLE
`console` - screen 

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#307]
#### What would you like to be added:
Ability to do rpc commands via console. 

Need your input on this @fuxingloh

**Comment by fuxingloh** [comment]
It takes the same amount of effort to create console interfacing then to implement them, as they are light implementation we need to map the opcodes. We don't have access to the tradtional console on light infrastructure.

**Comment by jtlntno-cake** [comment]
Console screen seen here:
https://marvelapp.com/prototype/ce4111i/screen/81140878

Located in settings

**Comment by fuxingloh** [comment]
There is no way to do a console on light wallet.

We might implement this when we bring support to desktop wallet. Will close this for now as it shouldn't be tracked.
