### ISSUE TITLE
White screen after splash screen on Android 12

### ISSUE THREAD

**Issue by wyssen** [DeFiCh/wallet#3223]
Hello dear community.
Since a few days, my Light Wallet (latest version) under Android 12 stopped working. When I open the app, I briefly see the splash screen with the DeFiChain-Icon and "Birthday Research" at the bottom, but then a white screen is appearing just nothing happens anymore. I have the same issue on two different devices with Android 12. On one of them, I have completely removed the app and reinstalled. Problem still persists...

Is this issue know? I have a OnePlus Nord 2T 5G which comes with the OxygenOS 12.1 with Android Security Patch from  2022.06.

The wallet worked on this device before

![pic](https://user-images.githubusercontent.com/9450822/181433917-7459e242-78d9-4500-b0af-7a0d9b170f0e.png)
.

Thank you so much

**Comment by thedoublejay** [comment]
Hi @wyssen, do you still face the issue now?

**Comment by wyssen** [comment]
Hello. Yes, the problem persist. I try a few times per day, but the problem
is still the same. After the short splash screen, nothing but white... Do
you have any idea?

**Comment by thedoublejay** [comment]
hI @wyssen I don't have an idea for now. But can you try uninstalling and installing? Ensure you have your 24 words first

**Comment by wyssen** [comment]
Hi. This was the first thing I tried as mentioned in my initial post.

"I have the same issue on two different devices with Android 12. On one of
them, I have completely removed the app and reinstalled. Problem still
persists..."

Best regards

**Comment by wyssen** [comment]
The problem seams resolved with the latest update of the Wallet. Thank you.
