### ISSUE TITLE
List of countries where the App is available

### ISSUE THREAD

**Issue by dbilousov** [DeFiCh/wallet#3240]
Hi guys 

I just wanted to ask in which countries the App is available to download in App Store and Play Store?

Kind regards
Dennis

**Comment by thedoublejay** [comment]
@dbilousov We are using the default settings of both play stores. Do you have any specific country to check?

**Comment by dbilousov** [comment]
Hey @thedoublejay any news on this?

**Comment by thedoublejay** [comment]
Hi @dbilousov, sorry I was out on a holiday. Yes it was available for both Russia and Ukraine. Both on Android and App Store.

**Comment by thedoublejay** [comment]
@dbilousov Anything else needed? Otherwise, I will close this issue

**Comment by dbilousov** [comment]
@thedoublejay Thank you and hope you had a good holiday! Please close the issue
