### ISSUE TITLE
Minor UI issues in LW 2.0 designs 

### ISSUE THREAD

**Issue by dwivedinalin** [DeFiCh/wallet#3256]
#### What happened:

#1 Toggle currency button with odd spacing
#2 these button should be evenly spaced when theres only 4 buttons
#3 wrong icon for external link
#4 check if font size is correct (bottom value should be smaller than top)
#5 filter buttons not full rounded corners
#6 text alignment off
#7 address content alignment off, padding should be 20px
#8 no need for ext link icon here (its already on the card bellow), and address should be full two liners.
#9 spacing should be 12px instead of 8px
#10 learn more about DFI should link to FAQ instead? (edited
#11. the padding of DFI button increases after 1 round of toggling

#### Anything else we need to know?:

<img width="394" alt="Screenshot 2022-08-03 at 3 22 28 PM" src="https://user-images.githubusercontent.com/32018980/182579780-c47bd884-4483-4546-b3bb-1f9d69c70418.png">

<img width="392" alt="Screenshot 2022-08-03 at 3 22 43 PM" src="https://user-images.githubusercontent.com/32018980/182579826-26e4e030-b221-4d7b-9e1a-f9f3ada1dc21.png">

<img width="396" alt="Screenshot 2022-08-03 at 3 22 57 PM" src="https://user-images.githubusercontent.com/32018980/182579884-6294c35b-d4d3-4c69-8102-f4def8fd7588.png">

<img width="389" alt="Screenshot 2022-08-03 at 3 23 11 PM" src="https://user-images.githubusercontent.com/32018980/182579933-3b61cb6a-7755-4be9-a124-e322b952461c.png">

<img width="366" alt="Screenshot 2022-08-03 at 3 23 28 PM" src="https://user-images.githubusercontent.com/32018980/182579976-b970b544-2b50-4f72-a7cc-44efcdaa2722.png">

<img width="382" alt="Screenshot 2022-08-03 at 3 24 48 PM" src="https://user-images.githubusercontent.com/32018980/182580295-56aeced6-16fe-483c-8c8a-ee2ebcf2877d.png">

**Comment by kyleleow** [comment]
Won't fix for item #1, #5 and #11 for now.
