### ISSUE TITLE
Wrong language (translation) on add liquidity screen

### ISSUE THREAD

**Issue by RoMi1981** [DeFiCh/wallet#3400]
#### Anything else we need to know?: I attached a screenshot with this issue. I'am on the german translation, maybe it will show right on different lang settings. I'am on light wallet v2.4.3, Android

![Screenshot_20220902-114620_DeFiChain Wallet](https://user-images.githubusercontent.com/51130674/188113951-639bbf07-5a74-4c6a-8d71-30d7f2170f59.jpg)

**Comment by RoMi1981** [comment]
Android

**Comment by lykalabrada** [comment]
Hi @RoMi1981, thanks for reporting the issue, this has been fixed on [PR-3378](https://github.com/DeFiCh/wallet/pull/3378) and will be included in the upcoming release
