### ISSUE TITLE
Testflight / Beta Access

### ISSUE THREAD

**Issue by Mark76DefiChain** [DeFiCh/wallet#3446]
I suggest to create a Testflight (iOS) or Beta Access Pre-Release of new Light Wallet Versions, so that more users could test new features.

Access should only be for users, which confirms they know and accept the risks
Best Practice: Use the Beta only on testnet and on a second mobile phone.

**Comment by thedoublejay** [comment]
Hi @Mark76DefiChain we have this since the release of Light Wallet. You can join this group for more info https://t.me/DefiProductReview

**Comment by Mark76DefiChain** [comment]
Hi, maybe we misunderstood each other. I was speaking about testing pre-release versions. Testflight Version of the wallet is 2.0.0, current Release is 2.4.3... Will the next light wallet version be available for pre-release testing? (2.5?)
