### ISSUE TITLE
"Unloop Loan"-Function is missing: No option to pay back Loan with Collateral

### ISSUE THREAD

**Issue by daffilein** [DeFiCh/wallet#3476]
Scenario: I have a vault with only DUSD as Collateral and only DUSD Loans (Looped Vault).

It was announced that there would be the possibility to pay back this complete DUSD Loan directly with the Vaults' Collateral in one step. I cannot find a button for this functionality on the Testnet. This should be implemented in the Testnet, because  it is immensely important to be able to test that function before it goes live, as there are currently dozens of millions of DUSD in looped loans, and many of these users will want to unloop their loan after the next Update using this functionality.

**Comment by thedoublejay** [comment]
Hi @daffilein, we are still working on this feature and not yet available anywhere. You can check the status with this PR - https://github.com/DeFiCh/wallet/pull/3462
