### ISSUE TITLE
add code completion to e2e test file

### ISSUE THREAD

**Issue by kyleleow** [DeFiCh/wallet#354]
#### What would you like to be added:
Add cypress into `tsconfig.json`'s types

#### Why is this needed:
To improve intelligent code completion feature in e2e .spec

#### Additional note:
Currently adding `types` into `tsconfig.json` will cause the following issue when running Missing Translation workflow
`Error: app/translations/reporter/index.ts(2,21): error TS2307: Cannot find module 'fs' or its corresponding type declarations.`

**Comment by fuxingloh** [comment]
Similar to this https://github.com/DeFiCh/wallet/issues/324

**Comment by fuxingloh** [comment]
/duplicate in favor #324
Assigned 324 to @kyleleow
