### ISSUE TITLE
🐛 Unspendable DFIs block any transactions

### ISSUE THREAD

**Issue by mrgrauel** [DeFiCh/wallet#3663]
#### What happened:
I received a masternode block reward on my light wallet address. After receiving the reward no transaction is possible until the DFI is `trusted` and not in `immature` or `untrusted_pending` state.

> bad-txns-premature-spend-of-coinbase, tried to spend coinbase at depth 1 (code 16)

#### What you expected to happen:
* I should still be able to do transactions
* Unspendable DFI shouldn't be shown in the balance

#### How to reproduce it (as minimally and precisely as possible):
* redirect masternode rewards to a light wallet address via `rewardaddress` in `defi.conf`
* wait for the masternode to find a block
* try to do a transaction

#### Anything else we need to know?:
I believe it's a missing feature in the ocean api, because it doesn't report if the DFI is `immature` `untrusted_pending` or `trusted`.

Related to https://github.com/kuegi/defichain_maxi/issues/100

**Comment by thedoublejay** [comment]
Closing here and opening on Jellyfish repo - https://github.com/JellyfishSDK/jellyfish/issues/1807
