### ISSUE TITLE
50% / max buttons for input fields

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#375]
#### What would you like to be added:
For fields that has max button, add the button 50% as well to select 50% of available amout.
Screens to be updated:
1. Send
2. Convert
3. DEX - Add Liqudity
4. DEX - Swap

![image](https://user-images.githubusercontent.com/25013382/127761786-188098b0-2641-4c0c-9c03-fedd0de812f8.png)

#### Why is this needed:
/triage accepted
/assign @kyleleow

**Comment by thedoublejay** [comment]
@jtlntno-cake Would it make sense to use "HALF" here instead of "50%"?

**Comment by jtlntno-cake** [comment]
@thedoublejay 'Half' was originally used but was changed to '50%' because of localization concerns.
