### ISSUE TITLE
App won't start on new phone "Nothing Phone 1"

### ISSUE THREAD

**Issue by Sumpfi-75** [DeFiCh/wallet#3791]
Hello together,

Problem:
Defichain and DFX Swiss App freeze at Start logo.

Details:
I have the new Nothing Phone 1 mobile phone. I installed the Defichain and DFX Swiss app from the Google Play Store. After starting the apps, the startup logo freezes everytime.

If you need anything else, let me know. But I'm not a professional and need help :-)

![Screenshot_20221120-132545](https://user-images.githubusercontent.com/82049639/203642341-31d5d101-dc1f-45ad-9ada-e26c633a3d02.png)
![Screenshot_20221120-132724](https://user-images.githubusercontent.com/82049639/203642397-512e7f14-40b5-4d64-9183-3ac0901997aa.png)
![Screenshot_20221120-132714](https://user-images.githubusercontent.com/82049639/203642474-ccfa0d57-68d5-473f-9dbd-651809f869e2.png)

**Comment by thedoublejay** [comment]
Can you try to uninstall, install the latest app from Play store? Does it still happen?

**Comment by Sumpfi-75** [comment]
Thanks doublejay,
deinstall and a new install resolve the Problem. 👍
