### ISSUE TITLE
`settings` - change passcode

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#385]
#### What would you like to be added:
On an encrypted wallet, we need to have the ability to change the passcode. 

#### Why is this needed:
/assign @jtlntno-cake 
/area ui-ux wallet
/priority important-soon
/needs design
/triage accepted

**Comment by jtlntno-cake** [comment]
Change passcode flow to be seen in this Marvel prototype:
https://marvelapp.com/prototype/ce4111i/screen/81013174
