### ISSUE TITLE
dUSD Factor of 1.2 is used on the Payback Screen

### ISSUE THREAD

**Issue by mrgrauel** [DeFiCh/wallet#3904]
#### What happened:
* dUSD Factor of 1.2 is also added to the USD value if paying back a loan

<img width="271" alt="image" src="https://user-images.githubusercontent.com/148758/215966598-e7d96609-e277-4479-a084-6c32f5587e17.png">

#### What you expected to happen:
* the factor isn't added

#### How to reproduce it (as minimally and precisely as possible):
* take a dUSD loan
* payback loan and check collateral ratio on the payback screen vs. the real ratio after paying back

**Comment by kyleleow** [comment]
Thanks for opening a ticket, we'll look into this.
