### ISSUE TITLE
cannot reset custom service provider

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/wallet#3918]
#### What happened:
On Android, App version 2.17.0
I set the custom ocean url to my defichain on testnet. now trying to reset it back to the main ocean is not working.

When I tap the reset button it asks for my password and then spins infinitly

trying to just enter the offcial url doesn't work either as there is no way to confirm it.

#### What you expected to happen:

clicking the reset button should reset it to main ocean

**Comment by kevzzsk** [comment]
We are taking a look into this issue, but was unable to reproduce.
