### ISSUE TITLE
Changing Ocean Link to mydefichain not working without restart

### ISSUE THREAD

**Issue by marcelkb** [DeFiCh/wallet#3930]
#### What happened:
after switch of url on ios app,
the account balances was empty and the connection logo still red.
Needed to do a manuell refresh/restart of the app.
Another User reported in the german group the same behaviour on android.

#### What you expected to happen:
switch happen, all account balances are automatically refreshed, vault correctly shown without the need to restart

#### How to reproduce it (as minimally and precisely as possible):
Switched the ocean url to mydefichains in a time where normal ocean is down

**Comment by thedoublejay** [comment]
@marcelkb This is the expected behavior, as the app needs to restart to refresh the entire state. We don't plan on update it soon.
