### ISSUE TITLE
`TextInput` placeholder not visible on iOS device

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#408]
#### What happened:
On all TextInput, placeholders (e.g, Enter an amount here), is not visible on iOS devices.

**Comment by kyleleow** [comment]
Placeholder is working fine on iOS 14.7.1 iPhone 12
![image](https://user-images.githubusercontent.com/40191153/128694393-1ce486e3-f334-4008-ac39-9336c5d55973.png)
