### ISSUE TITLE
error logging/stats monitoring for wallet

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#41]
#### What would you like to be added:
Some kind of stats monitoring, error logging tool that we can use. Especially JS errors, which page error occurred etc. 

One tool I have used before:
https://raygun.com
#### Why is this needed:
View errors for users with logs, browser used, location etc. It will also display how many users are encountering this error, when it was first encountered etc.

**Comment by fuxingloh** [comment]
We should not add tracking tools into the app for decentralization reasons. Incorporating also creates more supply chain attack vectors.

**Comment by fuxingloh** [comment]
Instead of having a centralized collection of logs, we still need to ability to collect logs for anomalous condition that we can't trace.

**Comment by thedoublejay** [comment]
Ok for this ticket, we can add a feature to be able to generate some kind of `debug package` and users will be able to give/send to us.

**Comment by thedoublejay** [comment]
@fuxingloh I'm thinking on how we can implement a error report/logging tool. 

My idea is:
1. Generate all error logs to a file (via https://www.npmjs.com/package/react-native-logs)
2. From the wallet, there will be a option to send logs somewhere
3. The log file can be sent to either of the following:
   a. Upload all log files to some storage 
   b. Directly create issue on Github
   c. Send to engineering email

Let me know your thoughts about it

**Comment by fuxingloh** [comment]
@izzycsy do you have any inputs before I comment on this?

**Comment by izzycsy** [comment]
Agree with @thedoublejay and also with anomalous issues. It'd be good if the user can self resolve the issue as well, maybe too far fetched 😂 I was thinking like Apple support. They go through some filtering of their issues first, then open a bug ticket before, but this might be considered centralised already. Your thoughts?

**Comment by thedoublejay** [comment]
Regardless of what we pick, I guess spamming of logs might be an issue. So that's something to think about as well. 

@izzycsy there are a lot of centralized solutions available but we want to avoid that as much as possible

**Comment by fuxingloh** [comment]
Let's wait for beta before we implement this, I think we will have a clearer picture by then
