### ISSUE TITLE
`scrypt` - lower difficulty 

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#422]
#### What would you like to be added:
Lower scrypt difficulty to make encryption faster - https://github.com/DeFiCh/wallet/pull/403#discussion_r682700736
#### Why is this needed:
/area ui-ux wallet
/priority important-soon
/triage accepted

**Comment by fuxingloh** [comment]
Reducing difficulty to 1-2 seconds should be adequate
