### ISSUE TITLE
`biometric` - display unlock screen

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#434]
#### What UI/UX improvements would you like to be implemented: 
Wallet should have an unlock step before opening for privacy purposes
#### Anything else we need to know?:
/triage accepted
/area ui-ux

**Comment by thedoublejay** [comment]
Linked to https://github.com/DeFiCh/wallet/issues/444

**Comment by izzycsy** [comment]
Expected: Wallet to have an unlock step before opening

**Android:**

- [ ]  1. After #444 > switch to another app on device > switch back immediately to DeFiChain Wallet > biometric should trigger
- [ ] 2. ... > switch to another app on device > wait for more than 1 min > switch back to DeFiChain Wallet > biometric should trigger

**iOS:**

- [ ]  1. After #444 > switch to another app on device > switch back immediately to DeFiChain Wallet > biometric should trigger
- [ ] 2. ... > switch to another app on device > wait for more than 1 min > switch back to DeFiChain Wallet > biometric should trigger
