### ISSUE TITLE
`settings` - opt in for Biometric Authentication

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#444]
#### What would you like to be added:
For existing wallets, have the ability to opt-in for Biometric Authentication from Settings page.
#### Why is this needed:
/triage accepted

**Comment by izzycsy** [comment]
Expected: For existing wallets, ability to opt-in for Biometric Authentication from Settings page


**Android:**

- [ ] 1. Settings > Toggle on Biometric Authentication > Prompt triggered 

**iOS:**

- [ ] 1. Settings > Toggle on Biometric Authentication > Prompt triggered
