### ISSUE TITLE
explicit labels for UTXO and Token DFI

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#447]
#### What happened:
“Add Liquidty” page, it should be shown as DFI (Token). The example here, I have DFI, but no token form. Took me a bit to realize that it’s because I’m missing token.

**Comment by kyleleow** [comment]
Do you want to update the label on the Dex List Screen too? 
![image](https://user-images.githubusercontent.com/40191153/128687573-a49b9cbc-fa9f-42c3-ab9f-4b047b88c2fd.png)

**Comment by thedoublejay** [comment]
@kyleleow nope, only on Add Liquidity and DEX probably. Only for input fields
