### ISSUE TITLE
view wallet on DeFiScan

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#463]
#### What would you like to be added:
We can have a button in the wallet to view the current loaded wallet in DeFiScan. Something like `View on DeFiScan`. Not sure if we have that page yet.
#### Why is this needed:

/area ui-ux

Let me know your thoughts about it @fuxingloh @aentan  @jtlntno-cake

**Comment by fuxingloh** [comment]
We don't have that yet, but yup it's something on the todo for `DeFi Scan`. So it will be something like `defiscan.live/address/:address`

**Comment by ngyingzhong** [comment]
A short product document for this feature for discussion/ documentation.

## Background

With the address page on DeFi Scan live, users are able to view transactions and balances related to a specific address on the website. 

## Objectives

- To allow users to have a holistic view of their decentralised address on DeFiChain
    - Serves as a stop-gap measure before the light wallet is ready to offer a native transaction page

## Assumptions

1. The [address switching feature](https://github.com/DeFiCh/wallet/issues/910) is coming soon on the light wallet — to include in design consideration

## User Stories

### User story 1: Users want to be able to access information relating to their wallet from various points in the light wallet

**Proposed features/ interactions:**

1. `View on Scan` action to be available on:
    1. Balance tab
    2. Vaults tab
    3. Auctions tab
2. To consider the eventuality of multiple addresses in a single wallet when designing

**Note:** DEX might not require this action now as the information on Scan and on the wallet is the same, with the exception of Total Liquidity and Price Ratio. 

- There's plans to design a individual pool pair pages with specific pool pair information — `View on Scan` on DEX could be applied when this feature is released on Scan.

@jtlntno-cake @thedoublejay

**Comment by izzycsy** [comment]
Acceptance Criteria: User's `Wallet Address` directs user to _defiscan.live/address/d123..._

Android: 
- [ ] Balances > Select `Wallet Address` at top of screen > directs user to _defiscan.live/address/d123..._


iOS: 
- [ ] Balances > Select `Wallet Address` at top of screen > directs user to _defiscan.live/address/d123..._

Note the following will be included in future versions: 
• Vaults tab
• Auctions tab
