### ISSUE TITLE
`balances` - hide balances option

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#465]
#### What would you like to be added:
From Balances Page, beside the portfolio title, there should be an Eye icon. Clicking it should change all amounts to `****`

- [ ] Use `eye` and `eye-off` from MaterialCommunityIcons
- [ ] It should be stored on LocalStorage
- [ ] It should only update Balances page

**Comment by jtlntno-cake** [comment]
Screens can be seen in this [link](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/Mobile-Light-Wallet?node-id=287%3A11410)

Let me know if any questions

**Comment by izzycsy** [comment]
![hide bal](https://user-images.githubusercontent.com/65014479/136948826-b9e2a0cd-e473-4bc0-85ec-ab17f7c77847.png)

Acceptance Criteria: User able to show/hide balances.

Android: 

- [ ] Balances > Select `hide balances` > All numeric amount should display `*****`
- [ ] Balances > Select `show balances` > All `*****` should display token balances

iOS: 
- [ ] Balances > Select `hide balances` > All numeric amount should display `*****`
- [ ] Balances > Select `show balances` > All `*****` should display token balances
