### ISSUE TITLE
`offline` - screen

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#467]
#### Why is this needed:
When the user doesn't have network connection, display a screen for it

**Comment by thedoublejay** [comment]
![image](https://user-images.githubusercontent.com/25013382/129284873-f241d91c-49eb-4900-9ec0-826590a4c4f2.png)

@jtlntno-cake we can use a more attractive logo here. Like astronaut getting lost or something

**Comment by kyleleow** [comment]
@thedoublejay does this screen needs to be triggered in everywhere of the App?

Right now the app is regularly calling multiple APIs, e.g.: balance, stats, tokens, if this happen the user will be stuck in this screen until he/she gets a connection

**Comment by thedoublejay** [comment]
@kyleleow I think there's an expo library to check the network connection. We need to use that
