### ISSUE TITLE
`splash screen` - main page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#47]
#### What would you like to be added:
A splash screen for the light wallet. 
#### Why is this needed:
It will be displayed on start of the app.

**Comment by fuxingloh** [comment]
Currently, it's automatically handled with system-level hooks

https://github.com/DeFiCh/wallet/blob/6e51566b5b5e3d1502a820ec5f4acdc2abfea8bd/hooks/useCachedResources.ts#L14

The image used is here https://github.com/DeFiCh/wallet/blob/main/assets/images/splash.png

/assign @thedoublejay

**Comment by jtlntno-cake** [comment]
For the launch screen, we use this:
https://marvelapp.com/prototype/c572fa6/screen/79800477

We can also use this for privacy overlays, especially when moving from 1 app to another
