### ISSUE TITLE
OnboardingCarousel to start from `index={0}`?

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#485]
#### What UI/UX improvements would you like to be implemented: 

I always wonder why we are not starting on `index={0}` for OnboardingCarousel. Is there a reason for this?

https://github.com/DeFiCh/wallet/blob/699174723157302faf4c726d9d38f7d59ca96a9d/app/screens/WalletNavigator/screens/components/OnboardingCarousel.tsx#L76

**Comment by thedoublejay** [comment]
@fuxingloh no it was a bug for testing purposes. Will adjust
