### ISSUE TITLE
`RestoreMnemonicWallet` to auto trim whitespace

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#486]
#### What UI/UX improvements would you like to be implemented: 

```
super low priority ticket
```

To auto trim whitespace so that whitespace doesn't show up as error when restoring.

Also, there is a method to validate whether the word is part of the 2048 series:
https://github.com/DeFiCh/jellyfish/blob/8427771654378f306dc8ada699369a50db5866b0/packages/jellyfish-wallet-mnemonic/src/mnemonic.ts#L14-L20

**Comment by thedoublejay** [comment]
@fuxingloh would it be a security issue to add the validate for 2048 series?

**Comment by fuxingloh** [comment]
Nope, the mnemonic words belongs to a dictionary of 2048 words. If it's not inside the dictionary it's not part of the mnemonic series.
