### ISSUE TITLE
`CI` - run e2e tests on interval to test core functionalities

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#489]
#### What would you like to be added:
Currently, we have tests that run on mainnet. We can have a CI that runs on interval (every hour? or every 6 hours). To test if all our features run fine. We can integrate a Slack Reporter (https://www.npmjs.com/package/cypress-slack-reporter) that triggers a message on failure or maybe opsgenie once we're in prod.
#### Why is this needed:
@fuxingloh need your thoughts on this

**Comment by fuxingloh** [comment]
Sounds good, but I think cron every morning 9 am SGT might be a better interval for us. Gives us time to respond in the morning and into the afternoon.

For cypress slack reporter, we are using the `cypress.io` dashboard. The slack reporter is a build-in feature so we can just use that instead. I have invited you to our cypress.io dashboard.

**Comment by fuxingloh** [comment]
I have added it to Slack, but muted it for now.
