### ISSUE TITLE
`wallet` - create new wallet

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#49]
#### What would you like to be added:
Create new wallet
#### Why is this needed:
Ability to Create a new wallet

- [ ] Create new wallet button
- [ ] Generate 24 mnemonic seed
- [ ] Verify mnemonic seed
- [ ] Encrypt wallet page (Pending design)

![image](https://user-images.githubusercontent.com/25013382/119117307-b23c0400-ba5b-11eb-8d05-1331621f1390.png)

![image](https://user-images.githubusercontent.com/25013382/119117625-fe874400-ba5b-11eb-930d-16f0bc6bd302.png)

![image](https://user-images.githubusercontent.com/25013382/119117644-02b36180-ba5c-11eb-81b0-d3cfba9169e7.png)

**Comment by fuxingloh** [comment]
- [ ] @thedoublejay to create another ticket for encrypting, it is not as important now. We still need upstream changes for this to work. https://github.com/DeFiCh/jellyfish/issues/133

1. Use a StackController
2. Wallet name default to a placeholder called `default`
3. Verify mnemonic seed to do all 24 words, no skipping. Dangerous if we skip, we need to go on the defensive here.
4. Verify mnemonic seed not to show 3 options, show all 24 options.
5. Follow the ledger implementation, don't make it any easier to create a wallet.

/triage accepted
/priority important-soon
/assign @thedoublejay

**Comment by fuxingloh** [comment]
I will add the wallet dependencies in another PR for you.
