### ISSUE TITLE
`balances` - main page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#50]
#### What would you like to be added:
Balances Page
#### Why is this needed:
Ability to display balances, send and receive tokens
- [ ] Balances Page
- [ ] Token List

![image](https://user-images.githubusercontent.com/25013382/119118178-8b320200-ba5c-11eb-8c05-fab6e88d8ab8.png)

**Comment by thedoublejay** [comment]
@jtlntno-cake For the navigation buttons here, "Receive", "Send" and "Swap". I think it will be an issue on other languages since they might have longer words for it. What do you think if we change it to symbols? Like how we do it on the app

**Comment by jtlntno-cake** [comment]
I see your point @thedoublejay . However, I think having the button labels as icons only may affect its clarity due to icons' loose perceptions to various cultures/biases of other people. Having a swap icon without any label may not look like a swap-button without any label text. That's why important action buttons generally do well with a label than just an icon.

In this sense, we can first keep the labels and then should we encounter lengthy text in other translations, I'll come up with a design that accommodates the lengthy text.

**Comment by thedoublejay** [comment]
@jingyi2811  These are some examples, maybe you can create a mockup:
1. German
Send - "Senden",
Receive - "Empfangen",
Swap - "Swap"

2. Chinese Traditional
"send": "發送"
"receive": "接收"
"swap": "兌換"

3. French
"send": "Envoyer",
"receive": "Recevoir",
"swap": "Swap",

**Comment by jtlntno-cake** [comment]
Got it. I'll create a mockup for these translations

**Comment by jtlntno-cake** [comment]
![image](https://user-images.githubusercontent.com/85162376/122005714-8c024d80-cde8-11eb-9fe0-3617ad5f7e6b.png)

Adding here a design iteration in consideration of points listed above. A few updates:

- Redesigned buttons to include icon and translated labels
- Changed location of add coin and added label for increased clarity. Section header was also added for visual balance
- Removed QR icon button.

Let me know if any questions/clarifications. Thanks

@aentan @thedoublejay @fuxingloh 

Here's the marvel link: **https://marvelapp.com/prototype/c572fa6/section/1387755**

**Comment by fuxingloh** [comment]
For the entire top, we aren't going to support in the early version.

![image](https://user-images.githubusercontent.com/4266087/122008083-32e7e900-cdeb-11eb-8dcf-c2b95fb0dd91.png)

We will never support:

![image](https://user-images.githubusercontent.com/4266087/122008149-43985f00-cdeb-11eb-89af-97027874dbb6.png)

See #51 

Fiat we will never support until it's completed in whale https://github.com/DeFiCh/whale/issues/136
![image](https://user-images.githubusercontent.com/4266087/122008236-61fe5a80-cdeb-11eb-9436-e8f297504f9e.png)

**Comment by jtlntno-cake** [comment]
@fuxingloh What do you mean exactly by never supporting the button, 'add-coin'? Is it on the design language sense or functionality-based?

As for other comments, i understand that we're still at early build phase. All good.

**Comment by thedoublejay** [comment]
@jtlntno-cake `Add Coin` button is used to add tokens which is not displayed on the balances page. Example, on the balances page we only show BTC and DFI. If you click on `Add Coin`, it will add it on the display

**Comment by jtlntno-cake** [comment]
So we want to display all coins by default in the balances page. This reduces configuration and dev costs while not necessarily hampering the user's experience. Assuming we don't have more than (let's say) 20 coins in the page, the the display would be pretty manageable

**Comment by thedoublejay** [comment]
I think we don't want to display all coins especially if they don't have any balances. Probably we only want to display the main tokens (DFI, BTC, ETH, USDT, BCH). The rest (custom tokens) will only be displayed when it has any amount.

**Comment by thedoublejay** [comment]
Hey @jtlntno-cake, @fuxingloh raised a point regarding the display of UTXO/Account split of DFI. I think it's a good point that we can address now. Currently, in the app, we're displaying the total and split between UTXO and Token. This is one of the mostly discussed issue for the app before. 

If we have a split in display, the next flow that we need to consider is how users are going to convert Token to UTXO or vice versa in the wallet.

**Comment by jtlntno-cake** [comment]
Hey @thedoublejay - just wanted to clarify first if I understand correctly – we want to display within this balances page both the total and the split of UTXO and Token (which currently only displays the total). 

Also, for the second point, is this a new flow that is has not yet been added in previous screens?
