### ISSUE TITLE
`balances` - add/remove token to balances page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#51]
#### What would you like to be added:
Ability to add token in balances page
#### Why is this needed:
Ability to add/remove token in balances page
![image](https://user-images.githubusercontent.com/25013382/119118422-bf0d2780-ba5c-11eb-81c6-fad8bd488133.png)

**Comment by fuxingloh** [comment]
I don't understand what's the purpose of this, we should list all assets by default.

**Comment by thedoublejay** [comment]
> I don't understand what's the purpose of this, we should list all assets by default.

I think mostly to not populate the token list with tokens you don't have. But can be low prioritized. We can just have display all tokens, then have a "Hide zero balances" button somewhere.
