### ISSUE TITLE
Wallet FAQ CMS

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#510]
#### What would you like to be added:
Need to create an FAQ CMS site for all wallet related questions.
#### Why is this needed:
Need to add a link on the wallet as well.

**Comment by thedoublejay** [comment]
@fuxingloh is this the final URL? I'll add it on the wallet

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: Redirect user to FAQ CMS site for all wallet related questions.

**Android:**
- [ ] 1. Settings > Help > FAQ > Chrome browser opens to FAQ site


**iOS:**
- [ ] 1. Settings > Help > FAQ > Safari browser opens to FAQ site
