### ISSUE TITLE
`address` - wallet address not accepted by Cake and Desktop App, need to verify with exchanges

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#516]
#### What happened:

Wallet Address generated by `DeFiCh/app` doesn't work on Cake and Desktop App, we need to update them. We need to track for exchanges too.

#### Exchanges:

- [x] `DeFiCh/app`
- [x] Cake
- [x] Bittrex
- [x] KuCoin
- [x] Hotbit 
- [x] Bitrue

**Comment by uzyn** [comment]
Cake-side support will be added this week. Tracker: https://www.pivotaltracker.com/story/show/179175655

**Comment by thedoublejay** [comment]
DeFi App side will also be added - https://github.com/DeFiCh/app/issues/1021
