### ISSUE TITLE
`send` - long addresses overextends the address field

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#518]
#### What happened:
Sample address: dYMGt3FQ4hrEWKAyJqotz2PEWzbVsmXMnF
![Screenshot_20210810-170343_Expo Go](https://user-images.githubusercontent.com/25013382/128839645-3841d4d1-ccda-4886-afd9-90572f18b4a7.jpg)

**Comment by kyleleow** [comment]
I change so that field will not overextend.
Do you want to overflow the address to newline? Or we clip it with or without ellipsis?

**Comment by thedoublejay** [comment]
@kyleleow overflow it to new line, maybe increase the size of TextInput to make it look like a text area. Address validation is important and we can't clip it
