### ISSUE TITLE
`transaction authorization` - After entering the passcode to sign a transaction, stuck at that page and transaction doesn't get signed.

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#522]
#### What happened:

On iOS TestFlight v0.3.2, Playground

1. Send 0.5 `USDT` to another address
1. After entering the passcode to sign a transaction, stuck at that page and the transaction doesn't get signed.

**Comment by thedoublejay** [comment]
https://user-images.githubusercontent.com/25013382/128950567-812039d7-4a53-4f70-a3d9-03774f187231.mp4

**Comment by thedoublejay** [comment]
Another video 

Uploading video-1628649565.mp4…

**Comment by thedoublejay** [comment]
Another video

https://user-images.githubusercontent.com/25013382/128965650-347ae5ad-8fa9-424e-ab21-fd3835e84179.mp4

**Comment by thedoublejay** [comment]
Re-opening this as it's still occurring on some devices.
