### ISSUE TITLE
`send` - confirmation page

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#525]
#### What UI/UX improvements would you like to be implemented: 

For sending of token and UTXO, before signing a transaction, users should be prompt that they are sending tokens and properly validate the transaction.

#### Why is this needed:

1. UTXO the address is correct and they have access to it or it's the correct destination
2. DST Token, they are sending it to an address that can receive DST. Sending DST to an exchange that can't process DST will lead to loss of funds.

#### Which component/screens does this concern?:

Before transaction signing screen.

#### Anything else we need to know?:

/triage accepted
/priority urgent-now

**Comment by thedoublejay** [comment]
I agree with this but instead of a checkbox, @jtlntno-cake proposed a confirm screen instead.
![image (1)](https://user-images.githubusercontent.com/25013382/128959697-e1082296-a517-42bb-837b-e485be4f6bd0.png)
