### ISSUE TITLE
`loader` - main loader

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#53]
#### What would you like to be added:
Loader component
#### Why is this needed:
Must have loading icon and injectable text (so it can be reused)
![image](https://user-images.githubusercontent.com/25013382/119119045-64c09680-ba5d-11eb-86f3-d5361623313d.png)

**Comment by fuxingloh** [comment]
Put it in `components/*`, test this component with unit tests with basic snapshot testing. Don't import any libraries for this, we can create the component from scratch.

/triage accepted
/assign @thedoublejay
/priority urgent-now
