### ISSUE TITLE
`confirm liquidity` - UI update

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#553]
#### What would you like to be added:
Update confirm liquidity UI page

![image](https://user-images.githubusercontent.com/25013382/129282588-5efdb7e4-49bb-49c2-b824-0850be1353e2.png)

**Comment by ivan-zynesis** [comment]
I think we have have to solve the maxPrice together.

Context:
- Technically use can only specify input amount and max price (to buy output token)
- Allowing setting output amount is only to quick calculate input required
- The summary preview on (dex swap) input page no longer needed
