### ISSUE TITLE
`balances` - Unified DFI across app

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#554]
#### What would you like to be added:
We would like to combine DFI (UTXO) and DFI (Token) across all apps. There won't be any distinction between UTXO and Token. 

What are the main challenges for this ticket? 

- [ ] Update balances to display combined UTXO and Token DFI

#### Why is this needed:

![image](https://user-images.githubusercontent.com/25013382/129283359-479bbc36-7b70-4acd-a7ac-f80bcd5229a1.png)

**Comment by thedoublejay** [comment]
@jtlntno-cake we might have some inconsistent flows with this. What will happen now to the Token Detail screen?

**Comment by thedoublejay** [comment]
@kyleleow You can start with this. It will be the first task for multiple changes on different pages (as we're combining Token and UTXO). But there's still some pending tasks to be done on jellyfish side. For now, you can start working on the balances page. Remove the icons for now, just use caret and redirect it to TokenDetail page of DFI (UTXO).

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: Redirect user to FAQ CMS site for all wallet related questions.

**Android:**
- [ ] 1. Settings > Help > FAQ > Chrome browser opens to FAQ site


**iOS:**
- [ ] 1. Settings > Help > FAQ > Safari browser opens to FAQ site

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: On Balances screen, DFI Token and UTXO should be sum of both.

**Android:**
- [ ] 1. Balances > total DFI = sum of UTXO + Token


**iOS:**
- [ ] . Balances > total DFI = sum of UTXO + Token

**Comment by kyleleow** [comment]
> @kyleleow You can start with this. It will be the first task for multiple changes on different pages (as we're combining Token and UTXO). But there's still some pending tasks to be done on jellyfish side. For now, you can start working on the balances page. Remove the icons for now, just use caret and redirect it to TokenDetail page of DFI (UTXO).

@thedoublejay i believe this comment was made when the design is not ready? I'll start to implement based on the design available in figma v0.10.0 now

**Comment by thedoublejay** [comment]
> > @kyleleow You can start with this. It will be the first task for multiple changes on different pages (as we're combining Token and UTXO). But there's still some pending tasks to be done on jellyfish side. For now, you can start working on the balances page. Remove the icons for now, just use caret and redirect it to TokenDetail page of DFI (UTXO).
> 
> @thedoublejay i believe this comment was made when the design is not ready? I'll start to implement based on the design available in figma v0.10.0 now

Yes, before starting with development. Check first on jellyfish side on how are we going to handle multiple transactions
