### ISSUE TITLE
`transaction authorization` - ability to update titles

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#560]
#### What would you like to be added:
Make title and subtitle customizable so context can be updated.
#### Why is this needed:
![image](https://user-images.githubusercontent.com/25013382/129283589-c5af0f11-01f4-4af9-b414-288890a16943.png)

**Comment by thedoublejay** [comment]
Prototype: https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Light-Wallet?page-id=83%3A2917&node-id=100%3A4789&viewport=217%2C532%2C0.9296819567680359&scaling=scale-down&starting-point-node-id=87%3A3548&show-proto-sidebar=1

**Comment by thedoublejay** [comment]
@jtlntno-cake let's keep the transaction preview that we added. Some tx details for the user. Example:

![image](https://user-images.githubusercontent.com/25013382/129649105-69b1c185-c4be-4865-b809-7b665a8cbe85.png)

**Comment by thedoublejay** [comment]
@ivan-zynesis  we can separate the Tx queue logic and the UI for this. Ideally the UI would be as dump component as possible that just accepts content. So we can use it for TX auth and Non-TX auth

**Comment by jtlntno-cake** [comment]
@thedoublejay Agree with enriching context for the authorization screen. I edited the screens to reflect the updated copy. 
![image](https://user-images.githubusercontent.com/85162376/129659969-e82c29de-0d32-4ae5-9332-bcfdf3608fe0.png)
![image](https://user-images.githubusercontent.com/85162376/129660048-084dcd71-2548-496e-a728-50e2a9582290.png)
![image](https://user-images.githubusercontent.com/85162376/129660102-c2521c04-cb73-4416-a2e2-74d3417456eb.png)
![image](https://user-images.githubusercontent.com/85162376/129660126-49e83ecf-c0f1-4664-afa3-ad60faa28a69.png)
