### ISSUE TITLE
`InputText` - atomic component

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#564]
#### What would you like to be added:
Atomic component for InputText

- [ ] Must have styling for inline validation
- [ ] Placeholder color (as it's broken on iOS)
- [ ] Styling for error of forms, red outline
- [ ] Update usage across all screens
- [ ] Clear button
- [ ] Ability to accept right side components. Like QR code or Token Symbol
- [ ] Ability to accept titles

![image](https://user-images.githubusercontent.com/25013382/132604954-d84864af-687d-4aa1-b274-ce92e89c2a81.png)

**Comment by kyleleow** [comment]
@thedoublejay, do you mean placeholder color is broken on iOS?

>  Placeholder color (as it's broken on iOS)

I just tested on iOS device with a red color, the placeholder color is working
![IMG_C7BAE802E2A5-1](https://user-images.githubusercontent.com/40191153/133219844-d49e213f-9d71-4068-a010-4506b368a867.jpeg)

**Comment by thedoublejay** [comment]
@kyleleow it works if it's explicit. But if it's using system color default, it's not visible on some devices.

**Comment by kyleleow** [comment]
@thedoublejay i have checked the prototype provided by jonathan, cant seems to find any inline validation UI for now, is it a feature in future?

**Comment by izzycsy** [comment]
@kyleleow I think @thedoublejay might be referring to this, hope it helps:  

`#000000` — 40% opacity
<img width="455" alt="Screenshot 2021-09-15 at 6 37 40 PM" src="https://user-images.githubusercontent.com/65014479/133418784-d7e82f40-3d7f-42dd-979a-79a7151773c7.png">

`#000000` 
<img width="453" alt="Screenshot 2021-09-15 at 6 38 46 PM" src="https://user-images.githubusercontent.com/65014479/133418899-d1f4a2a2-8adb-4541-9cf2-a38721b76399.png">

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: UI to be consistent

**Android:**
- [ ] Must have styling for inline validation
- [ ] Placeholder `color` (as it's broken on iOS)
- [ ] Styling for error of forms, `red` outline
- [ ] Update usage across all screens
- [ ] `Clear` button
- [ ] Ability to accept right side components. Like QR code or Token Symbol
- [ ] Ability to accept titles

**iOS:**
- [ ] Must have styling for inline validation
- [ ] Placeholder `color` (as it's broken on iOS)
- [ ] Styling for error of forms, `red` outline
- [ ] Update usage across all screens
- [ ] `Clear` button
- [ ] Ability to accept right side components. Like QR code or Token Symbol
- [ ] Ability to accept titles

**Comment by jtlntno-cake** [comment]
Please also refer to the design system ([specifically this link for the text field)](https://www.figma.com/file/XdKJSI9TGYAf1VXJCQf2cZ/?node-id=50%3A947) for the various state of the component. Let me know if I miss anything so I can also add it to the design system moving forward. Ideally, we can capture the different states and add them to a central document so it's easier to ensure consistency. 

@thedoublejay @izzycsy @kyleleow

**Comment by kyleleow** [comment]
@jtlntno-cake thanks for the link.

May I ask what is the use case of the 'iOS layout' section in your design system? I thought we are suppose to create a similar design for both platform?

I ask because i noticed there some differences between that and the v0.10.0 prototype screen, e.g.: [send screen](https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Light-Wallet?page-id=287%3A11410&node-id=730%3A19638&viewport=241%2C48%2C0.8&scaling=scale-down&starting-point-node-id=730%3A19638&show-proto-sidebar=1)

**Comment by jtlntno-cake** [comment]
@kyleleow 

You can ignore that section for now. Those iOS text fields were the older text fields (with the previous intent of designing for native platform designs) and was just kept there for preservation.

The main thing to refer would be the prototype for what component should be used while the design system would be a reference for the various states of each components, among other things.

**Comment by kyleleow** [comment]
Hey @jtlntno-cake, @thedoublejay mentioned that not to use "0.00" as the placeholder for numeric text input, do you have any other options? Or I'll re-use the previous placeholder "Enter an amount"

**Comment by jtlntno-cake** [comment]
@kyleleow Sure, let's retain 'Enter an amount'. Thanks!

**Comment by thedoublejay** [comment]
@izzycsy This topic will need to re-test:

- [ ] Send Page
- [ ] Convert Page
- [ ] Add Liquidity Page
