### ISSUE TITLE
`network` - select outside of wallet context

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#566]
#### What would you like to be added:
Currently, when user is out of wallet context (e.g, Onboarding, restore flow). User doesn't have a way to select networks. He needs to create a wallet first and is currently a funnel.

- [ ] Add on Create Wallet Guidelines (First Screen only)
- [ ] Restore page

#### Why is this needed:

**Comment by jtlntno-cake** [comment]
@thedoublejay I think having an option to select TestNet over MainNet would propose more risk to a broader set of users. The scenario i'm thinking here is that when a casual user creates a wallet and because of curiosity, happens to encounter an option to select the network – if they do not understand which network to select, it would cause unnecessary friction to the casual user who just wants to create the wallet.

We want users to understand that MainNet is generally the network to use and to transact with, and having that option before the wallet is created could cause additional complaints, confusion, or dropoffs to a user segment - even more than the user segment that benefits from this feature

**Comment by aentan** [comment]
Default is mainnet. 99% of users will use mainnet.

Only few will want to change to test net to test things. For these people they'd go to Settings.

Let it be mainnet by default. Most consumer wallets don’t allow user to choose in the onboarding. It’s potentially problematic.

I won’t even hide it in an “advance options” thing during onboarding. It needs to be idiot proof for 99% of people.

Only way is to create wallet in mainnet, then change to test net if they want to.

They’d need main net address anyway. Can’t think of any use case where somebody only wants to have test net addresses.

**Comment by thedoublejay** [comment]
@jtlntno-cake @aentan Default is always mainnet. No question on that. The problem lies when switching networks inside a wallet.

Let's say you already created your wallet in Mainnet. Then "accidentally" you changed networks via Settings page. This will cause the wallet to "exit" because user doesn't have a wallet created on this network. It will exit to the wallet create screen. So for users who have "exited", they won't be able to return to their wallet anymore unless they create a wallet on Testnet => Change Settings to Mainnet. This is the scenario that we're trying to avoid. At least they won't be stuck

**Comment by aentan** [comment]
Got it. Now I understand. @jtlntno-cake we need a solution for this use case.

**Comment by fuxingloh** [comment]
Maybe we should remove network selection option from setting all together? (Showing without ability to select) Only able to switch once you have exited.

**Comment by thedoublejay** [comment]
@fuxingloh this would then be troublesome for users who have wallets created on both networks. as they need to unlink - 24 words - set new pincode

**Comment by aentan** [comment]
Here's a possible solution.

**Onboarding (first wallet)**
Has to be mainnet

**Subsequent wallet creation**
Allow for network selection during wallet creation

**Settings**
No network switching

- Network is tied to wallet, as it should be
- If you want to go testnet, you'd need to create a testnet wallet

**Comment by thedoublejay** [comment]
@kyleleow 
![image](https://user-images.githubusercontent.com/25013382/131277638-ebca5c20-4095-4d8e-9e33-be39b79031b5.png)

https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Light-Wallet?page-id=83%3A2917&node-id=244%3A17466&viewport=217%2C532%2C0.9296819567680359&scaling=scale-down&starting-point-node-id=244%3A17466&show-proto-sidebar=1

https://github.com/gorhom/react-native-bottom-sheet

**Comment by kyleleow** [comment]
@thedoublejay to double confirm, this option can be triggered in restore wallet screen and the way to trigger is to tap on the header title in top navigator?

**Comment by thedoublejay** [comment]
> @thedoublejay to double confirm, this option can be triggered in restore wallet screen and the way to trigger is to tap on the header title in top navigator?

Yes

**Comment by kyleleow** [comment]
@thedoublejay for the available networks, are we hardcoding to just two options? 

Or shall we be consistent with the options available in the settings screen, which is defined in `environment.ts`

**Comment by thedoublejay** [comment]
@kyleleow same as with Settings page. Networks vary depending on build (e.g, Production doesn't have local)
