### ISSUE TITLE
`create wallet` - on click back

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#567]
#### What would you like to be added:
When you're creating a wallet, and go back to the previous screen. Alll the mnemonic words will reset. Add a warning to the user that when he exits the mnemonic page, it will reset all current words.

![image](https://user-images.githubusercontent.com/25013382/129284560-3e8d4383-7095-4da1-a1f3-c05527e83cd2.png)

**Comment by ivan-zynesis** [comment]
It will quite annoying if I realize I made small mistake when jotting down the mnemonic and unable to check it again (get reset).

**Comment by thedoublejay** [comment]
@ivan-zynesis this alert will display when going back from Create Mnemonic to I accept screen of Onboarding
