### ISSUE TITLE
`pool swap` - add tests for price change on swap

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#579]
#### What would you like to be added:
This should be tested on Mainnet. The goal is to make sure that price displayed is correct for poolswap. Example, 0.00001 BTC per DFI or 1000 DFI per BTC. We want to make sure that the price displayed is the actual and correct price from MainNet. We can use API to cross validate the values.

#### Why is this needed:

- [ ] Run tests on change
- [ ] Add on smoke test

**Comment by izzycsy** [comment]
`Acceptance criteria`
Expected: Price displayed to be accurate for pool swap
_Validate prices with: —_ 

**Android:** 

- [ ] 1. DEX > Select `dETH-DFI` > `Swap` > input 1 dETH, should reflect 1,XXX DFI (Token) 
- [ ] 2. || > swap token position > input 1 DFI, should reflect 0.00000990 dETH
- [ ] 3. || > Select `dBTC-DFI` > ||
- [ ] 4. || > Select `dUSDT-DFI` > ||
- [ ] 5. || > Select `dDOGE-DFI` > ||
- [ ] 6. || > Select `dLTC-DFI` > ||
- [ ] 7. || > Select `dBCH-DFI` > ||
- [ ] 8. || > Select `dUSDC-DFI` > ||


**iOS:**

- [ ] 1. DEX > Select `dETH-DFI` > `Swap` > input 1 dETH, should reflect 1,XXX DFI (Token) 
- [ ] 2. || > swap token position > input 1 DFI, should reflect 0.00000990 dETH
- [ ] 3. || > Select `dBTC-DFI` > ||
- [ ] 4. || > Select `dUSDT-DFI` > ||
- [ ] 5. || > Select `dDOGE-DFI` > ||
- [ ] 6. || > Select `dLTC-DFI` > ||
- [ ] 7. || > Select `dBCH-DFI` > ||
- [ ] 8. || > Select `dUSDC-DFI` > ||
