### ISSUE TITLE
`transaction authorization` - updates

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#581]
#### What would you like to be added:

- [x] Bit sluggish now, takes 1-2 seconds delay per type
- [x] If there's an initial error, Transaction Authorization displays for a sec and goes back to error page. Before it won't show up the transaction auth if there's an initial error
- [x] Delay on showing InputPin (1-2 seconds)

**Comment by fuxingloh** [comment]
@ivan-zynesis with all transactions combined into one screen authorizing it. I think it might make sense to recreate the `JellyfishWallet` once without promise proxying on the AuthorizationScreen itself. I think this will greatly reduce complexity and cut down on code complexity.

**Comment by ivan-zynesis** [comment]
> @ivan-zynesis with all transactions combined into one screen authorizing it. I think it might make sense to recreate the `JellyfishWallet` once without promise proxying on the AuthorizationScreen itself. I think this will greatly reduce complexity and cut down on code complexity.

Make sense. Another useMemo do not harm much (single source of truth). Will start on this solution today.

**Comment by fuxingloh** [comment]
Just to be coherent to what I mean:

With all the transactions moved into a single screen for signing, `useWalletContext()` should not be used for transaction signing, we can just use it for reading of addresses (xpubkey).

For transaction signing, this allows us to remove the global `Authorization Component` and use a simple `Modal` push without nasty View set height tricks. 

With the newly pushed component, we can simply recreate the entire `wallet` after user enters their passphrase and pass that passphrase with promptPassphrase. Once the transaction is fully signed, we can dispose the pushed component all the newly created `Wallet` within that context. This keep the code relavitely clean.
