### ISSUE TITLE
`skeleton loader` - initial implementation

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#609]
#### What would you like to be added:
Do an initial implementation of skeleton loader on one page. So we can test the look and feel first before fully implementing everywhere. Start with DEX Screen, Add some skeleton loader on pool pairs while it's still fetching
#### Why is this needed:

Something like this - https://www.npmjs.com/package/react-native-skeleton-content
or this one I think is better - https://www.npmjs.com/package/react-content-loader

**Comment by kyleleow** [comment]
@thedoublejay by default, is there a specific number of placeholder that you want to display? 
The poolpair api is pulling 50 by default, but I don't think we should we should display 50.

Is one enough?
<img width="371" alt="Screenshot 2021-08-19 at 3 47 36 PM" src="https://user-images.githubusercontent.com/40191153/130029593-a9b4177d-24de-4f0e-a324-073eba34a010.png">
