### ISSUE TITLE
`slippage tolerance` - redesign

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#636]
#### What would you like to be added:

![image](https://user-images.githubusercontent.com/25013382/137442227-a3b5c178-1b8c-4762-b987-e1fdf68decd7.png)
![image](https://user-images.githubusercontent.com/25013382/137442246-d6f475d3-4bd2-4404-a220-0f30ecb31e83.png)

#### Why is this needed:
https://github.com/DeFiCh/wallet/pull/635

**Comment by fuxingloh** [comment]
The max is a 64bit integer number, 100% max and fair enough. 

But I guess when people enter custom, they are looking for <1% rather than above 20%

**Comment by izzycsy** [comment]
Acceptance Criteria: Redesign of `slippage tolerance` feature

Android: 
- [ ] Check UI
- [ ] Select `1%`, `3%`, `5%`, `10%`, `20%`
- [ ] Select  `Custom`, key in 100% & other numbers

iOS:
- [ ] Check UI
- [ ] Select `1%`, `3%`, `5%`, `10%`, `20%`
- [ ] Select  `Custom`, key in 100% & other numbers
