### ISSUE TITLE
`pool swap` - allow editing of token to swap

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#641]
#### What would you like to be added:
Allow editing of token to swap

**Comment by izzycsy** [comment]
`Acceptance criteria`
Expected: Ability to edit **Token B**, currently only able to edit input of Token A

**Android:** 

- [ ] 1. DEX > Select `dETH-DFI` > `Swap` > input 1 dETH `(Token A)`, should reflect 1,XXX DFI (Token) `(Token B)` > change input of `Token B`
- [ ] 2. || > swap token position > input 1 DFI `(Token A)`, should reflect 0.00000990 dETH `(Token B)` > change input of `Token B`
- [ ] 3. || > Select `dBTC-DFI` > ||
- [ ] 4. || > Select `dUSDT-DFI` > ||
- [ ] 5. || > Select `dDOGE-DFI` > ||
- [ ] 6. || > Select `dLTC-DFI` > ||
- [ ] 7. || > Select `dBCH-DFI` > ||
- [ ] 8. || > Select `dUSDC-DFI` > ||


**iOS:**

- [ ] 1. DEX > Select `dETH-DFI` > `Swap` > input 1 dETH `(Token A)`, should reflect 1,XXX DFI (Token) `(Token B)` > change input of `Token B`
- [ ] 2. || > swap token position > input 1 DFI `(Token A)`, should reflect 0.00000990 dETH `(Token B)` > change input of `Token B`
- [ ] 3. || > Select `dBTC-DFI` > ||
- [ ] 4. || > Select `dUSDT-DFI` > ||
- [ ] 5. || > Select `dDOGE-DFI` > ||
- [ ] 6. || > Select `dLTC-DFI` > ||
- [ ] 7. || > Select `dBCH-DFI` > ||
- [ ] 8. || > Select `dUSDC-DFI` > ||
