### ISSUE TITLE
add social media links on about page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#643]
#### Why is this needed:

- [ ] Add YouTube link - https://www.youtube.com/channel/UCL635AjCJe6gNOD7Awlv4ug
- [ ] Add Twitter Link - https://twitter.com/defichain

Add Telegram Announcements link on Community Screen
- [ ] https://t.me/defichain_announcements

**Comment by jtlntno-cake** [comment]
Here's the design for the added social media links in this page. 
https://marvelapp.com/prototype/ce4111i/screen/81221212/handoff

@kyleleow let me know if any questions or concerns. thanks!

**Comment by thedoublejay** [comment]
@kyleleow for the Telegram icon, no need to put it on About as it's part of the community screen. Just add YT and twitter
![image](https://user-images.githubusercontent.com/25013382/129836195-b2c0e483-456d-4f4e-85c0-7b6376a3c0ed.png)

**Comment by kyleleow** [comment]
@jtlntno-cake apparently material icons doesnt have youtube and twitter icon, is there any other alternatives we can use from material icons?

**Comment by thedoublejay** [comment]
You can use MaterialCommunity if it's not there @kyleleow

**Comment by kyleleow** [comment]
@thedoublejay is this label and order of the new Telegram Announcements link looks ok to you? 
![image](https://user-images.githubusercontent.com/40191153/129863013-63fd9aee-674b-418e-8662-50a5e9c750db.png)
