### ISSUE TITLE
push notifications

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#644]
#### What would you like to be added:
Allows us to send notifications (if user permits). Ex. when a transaction has been confirmed, etc.

The scenario would be, assuming users allow notifications:
1. Send a token
2. Transaction signed and broadcasted
3. Wait for it to be sent/timeout 
4. Send notification

Some things to consider:

- [x] Only push when allowed
- [x] Translations 
- [x] Add logo of app
- [x] Only push notification when user still has the same wallet loaded
- [x] Only push notification if wallet is on background

#### Why is this needed:
https://docs.expo.dev/versions/latest/sdk/notifications/

**Comment by thedoublejay** [comment]
Need your inputs on this @jtlntno-cake  @fuxingloh

**Comment by fuxingloh** [comment]
Don't think it's feasible: 
- for push notification we need a server to track balances and push from which we aren't doing for light wallet
- for background notification the OS doesn't allow the kind of processing that make sense from UX perspective

**Comment by izzycsy** [comment]
Acceptance Criteria: To receive notifications (eg. when a transaction has been confirmed, etc.)

Assuming users allow notifications:

Android: 

- [ ] Convert DFI > Switch out of app > Receive notification
- [ ] Send a token > Switch out of app > Receive notification
- [ ] Add LP > Switch out of app > Receive notification
- [ ] Remove LP > Switch out of app > Receive notification

iOS: 

- [ ] Convert DFI > Switch out of app > Receive notification
- [ ] Send a token > Switch out of app > Receive notification
- [ ] Add LP > Switch out of app > Receive notification
- [ ] Remove LP > Switch out of app > Receive notification
