### ISSUE TITLE
`dex` - display TVL and total liquidity per pair

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#647]
#### What would you like to be added:
Display TVL and total liquidity per pair in DEX page. Is it available from API? @fuxingloh

**Comment by fuxingloh** [comment]
Yup, it's available as an optional value. We use that in DeFiScan as well

**Comment by izzycsy** [comment]
Acceptance Criteria: In DEX, user able to view TVL

Android: 
- [ ] DEX > TVL at top of screen

iOS:
- [ ] DEX > TVL at top of screen
