### ISSUE TITLE
hide small balances

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#649]
#### What would you like to be added:
Use 0.0000001 as baseline for small balances. This is only a temporary option. Can be saved on localStorage

**Comment by thedoublejay** [comment]
Linked to https://github.com/DeFiCh/wallet/issues/667

**Comment by fuxingloh** [comment]
Is this an option? Or permanently?

**Comment by thedoublejay** [comment]
@fuxingloh it's an option, like a toggle on the balances page
