### ISSUE TITLE
`dex explorer` - link 

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#651]
#### What would you like to be added:
Add link on Dex Screen to https://defiscan.live/dex

**Comment by izzycsy** [comment]
Acceptance Criteria: Direct user to [DeFiScan](https://defiscan.live/dex) via DEX

Android: 
- [ ] DEX > click on pool pair > opens browser to DeFiScan

iOS:
- [ ] DEX > click on pool pair > opens browser to DeFiScan
