### ISSUE TITLE
`balances` - show all DST tokens on desktop even if balance is zero

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#667]
#### What would you like to be added:
Currently, by default we only show DFI and UTXO DFI by default. Users will not know that they can send other DST tokens as well. You can use parameters isDAT and !isLP to filter only DST tokens like Bitcoin, Ethereum etc..

**Comment by fuxingloh** [comment]
I don't we should implement this because DST will keep growing when we launch Loan.
