### ISSUE TITLE
`recovery words` - ability to refresh 24 recovery words

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#670]
#### What would you like to be added:
We need a way to refresh the current set of 24 recovery words. 

- [x] Add an alert on click of refresh
- [x] Add some buffer time and skeleton loader to show randomizing effect
- [x] e2e tests

#### Why is this needed:
https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Light-Wallet?page-id=287%3A11410&node-id=663%3A12999&viewport=241%2C48%2C0.8&scaling=scale-down&starting-point-node-id=642%3A17235&show-proto-sidebar=1

**Comment by jtlntno-cake** [comment]
We can utilize [RefreshControl](https://reactnative.dev/docs/refreshcontrol) here plus an icon in the header to inform the users the functionality of refreshing the recovery words. 

![Screen Shot 2021-08-20 at 11 25 24 PM](https://user-images.githubusercontent.com/85162376/130257936-763b2cb2-04f2-45c8-9813-348a56af2807.png)


Behavior can be seen in this [proto](https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Light-Wallet?page-id=83%3A2917&node-id=244%3A17491&viewport=241%2C48%2C0.48&scaling=scale-down&starting-point-node-id=244%3A17491&show-proto-sidebar=1)

**Comment by fuxingloh** [comment]
It's beyond just the conversation on refreshing it's the narrative of how they are derived. I will write a more detailed story soon.

**Comment by thedoublejay** [comment]
@jtlntno-cake @fullstackninja864 we won't add refreshcontrol here to avoid unexpected and irritating behavior for users when scrolling their screen. Let's stick to the button for now
