### ISSUE TITLE
`skeleton` - balances page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#675]
#### What would you like to be added:

- [ ] Add two rows

#### Why is this needed:
![image](https://user-images.githubusercontent.com/25013382/130212380-c5936fce-382a-436c-a421-0db5588988b6.png)

**Comment by kyleleow** [comment]
@thedoublejay is this related to #667 ? If yes, should we add more rows in advanced?

**Comment by thedoublejay** [comment]
@kyleleow It's ok keep it 2 rows. It's just a placeholder for loading

**Comment by kyleleow** [comment]
@thedoublejay I found that there are already a placeholder data shown in balance screen that is coming from the initial state in redux store.

The only difference is that currently it will always show "0" before token API returns the exact balance value

Do you want to actually change this behaviour?
