### ISSUE TITLE
Update all react function calls instead of using JSX.Element

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#694]
#### What would you like to be added:
Update usage of React Function components to JSX.Element. We should always use JSX.Element

- [ ] Dex Screen - PoolPairRowYour, PoolPairRowAvailable
- [ ] TransactionDetail - RenderRow

#### Why is this needed:
https://kentcdodds.com/blog/dont-call-a-react-function-component

**Comment by kyleleow** [comment]
@thedoublejay I have checked that the functions that you mentioned are not using any hooks in their implementations so they are not violating any rules of hooks. 

I also didnt get the hooks rendering error from these screen.

Do you mean to refactor them into a standalone file?

**Comment by thedoublejay** [comment]
@kyleleow they cannot use hooks because they're not JSX.Elements

**Comment by kyleleow** [comment]
Adding item below in TransactionScreen:
- TransactionRow
- LoadMore
