### ISSUE TITLE
Warning when activating masternode without operator privkey

### ISSUE THREAD

**Issue by IraGraves** [DeFiCh/wallet#697]
#### What would you like to be added:
When using the "activate" button on a masternode for which the wallet does not hold the private key for the operator address, a warning should be displayed before continuing.

#### Why is this needed:
This would avoid seriously messing up the wallet in some scenarios, as I learned yesterday. I set up a masternode on a VPS (creating the operator address on the VPS), and managing the owner address from the desktop wallet (following this: https://defichain-wiki.com/wiki/Masternode_installation_extended). This works fine. However, the desktop wallet shows the masternode as "local" and in a grey/inactive state, offering a button to "activate" it. This button is so tempting that, although I had a bad feeling, I clicked on it... The desktop wallet then tried to activate the masternode locally, which failed due to lack of the key for the operator address. This rendered the wallet unusable as after starting it every time it immediately lost connection to the node (debug showed that it was because of the missing privkey for the operator node) and the GUI was unusable. I fixed this by switching off the internet connection and feeding in the missing privkey which I exported from the VPS.

**Comment by thedoublejay** [comment]
Hey @IraGraves, is this PR for the desktop app? This repo is for the mobile wallet repository. If yes, can you create it on the desktop repo? Thank you! https://github.com/DeFiCh/app/issues

**Comment by IraGraves** [comment]
Sorry, my bad. It is for the desktop app. I will create it there.

**Comment by thedoublejay** [comment]
@IraGraves No worries, thank you!
