### ISSUE TITLE
Feature Gating

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#725]
#### What would you like to be added:

Feature gating creates a list of configurations isolated from the main app, accessible via settings. They can be used to enable/disable app features.

With feature gating, we can release new features for testing directly into the main app and have it disabled. Advanced users can choose to enable features while they are in beta.

#### Why is this needed:

This allows us to move faster bring testing features early to a handful of users. Release early, test early, and iterative early.

**Comment by izzycsy** [comment]
Acceptance Criteria: In `Settings` screen, users able "opt-in" for new `Features`

Android:
- [ ] Settings > Opt-in for Beta Features 
- [ ] Check disclaimer
- [ ] Check if Beta Feature is available

iOS:
- [ ] Settings > Opt-in for Beta Features 
- [ ] Check disclaimer
- [ ] Check if Beta Feature is available

**Comment by jtlntno-cake** [comment]
Hey guys, here's the design and prototype for Feature gates. Let me know if there's any thoughts or feedbacks

[Screens](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?node-id=4158%3A66838)

[Prototype](https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/PRDCT---Mobile-Light-Wallet?page-id=3985%3A62946&node-id=4158%3A66840&viewport=241%2C48%2C0.42&scaling=scale-down&starting-point-node-id=4158%3A66820&show-proto-sidebar=1)

**Comment by izzycsy** [comment]
Acceptance Criteria: In `Settings` screen, users able "opt-in" for `Beta Feature(s)`

Switch Network: **Playground**
Android: 
- [ ] Beta feature for 0.15.0: Loans
- [ ] User to "opt-in" on Beta features via `Settings` > `About`
- [ ] _Beta feature_ visible only if Beta feature is available to "opt-in"
> • If there's no Beta feature, then user won't see this link
> • If there is Beta feature, user can click to opt-in


iOS: 
- [ ] Beta feature for 0.15.0: Loans
- [ ] User to "opt-in" on Beta features via `Settings` > `About`
- [ ] _Beta feature_ visible only if Beta feature is available to "opt-in"
> • If there's no Beta feature, then user won't see this link
> • If there is Beta feature, user can click to opt-in
