### ISSUE TITLE
cannot swap DFI to BTC from bigger amount of 1 DFI

### ISSUE THREAD

**Issue by BastianReed** [DeFiCh/wallet#728]
i want to swap my DFI Token into BTC. 
I have 68 DFI Token and 11 DFI UTXO.
If i use more than 1 DFI to swap, the "Continue" Button is displayed grey and not confirmable.

I use the Android Defichain Wallet.

**Comment by thedoublejay** [comment]
Hey @BastianReed, we have an issue regarding this. https://github.com/DeFiCh/wallet/issues/689. It's currently hard to reproduce on our end. Can you give us more info or step by step on how you have encountered this? Also, as a workaround, you may try to restart the app and try again. Some users reporting this only on initial start of app.

**Comment by thedoublejay** [comment]
@BastianReed, also if you can provide us what app version, phone version and model you have so we can check. thanks

**Comment by thedoublejay** [comment]
Hey @BastianReed, this has been fixed with the latest app update `v0.10.5`. Please update your app via App/Google Store.
