### ISSUE TITLE
`UI` - UTXO vs Token (de)

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#739]
#### What UI/UX improvements would you like to be implemented: 
German: 
`An andere Wallets senden` bleeds pass centre-line 

Suggestion: 
Reduce `green tick` size to make space for words

#### Which component/screens does this concern?:
![210830 v0 9 0 - Android - Convert - German translation bleed](https://user-images.githubusercontent.com/65014479/131314940-57af02b6-c706-4d6c-aaf3-03f8a01d2e52.jpg)

**Comment by kyleleow** [comment]
@jtlntno-cake do you have any suggestion on this? I would suggest to make it flow to newline as a more future proof solution.

**Comment by jtlntno-cake** [comment]
I would suggest to just make it overflow to new line to keep things simple. But do keep in mind that there's a chance this screen shall be redesigned to match with the upcoming FAQ pages. 

So let's go with the easiest implementation first @kyleleow

**Comment by kyleleow** [comment]
Noted, will proceed with overflowing to newline for now.
