### ISSUE TITLE
Android: main tabs obstructing UI when numpad keyboard is active

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#744]
#### What happened: 
• **Android:** Bottom navigation bar (`Balances` | `DEX` | `Tx` | `Settings`) remains when numpad keyboard **is activated**, user may accidentally select 1/4 main tabs when clicking 1 / 2 / 3, resulting in having to restart their initial action (i.e. send, DEX, etc)

![210831 v0 9 1 - Android - Send - main tabs obstructing UI when numpad keyboard is active](https://user-images.githubusercontent.com/65014479/131371691-a22348ff-6c93-4002-9b21-2a804db1d279.jpg)

#### What you expected to happen:
• When numpad keyboard is active, bottom navigation bar should be hidden

#### How to reproduce it (as minimally and precisely as possible):
• Send any amount to trigger numpad keyboard 
• Try selecting 1 / 2 / 3
• User may accidentally select `Balances` / `DEX` / `Transactions`

#### Anything else we need to know?:
• Occurs only on Android, no issues on iOS device.

**Comment by thedoublejay** [comment]
This one is also the default behavior for Android devices.
