### ISSUE TITLE
Android - Settings: YouTube link inactive

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#745]
https://user-images.githubusercontent.com/65014479/131372135-cbf48875-849a-479b-85c7-e3de49a81f5a.mp4

#### What happened:
• Android: Youtube link does not work. Clicking effect occurs but does not open YouTube app.

#### What you expected to happen:
• YouTube App to launch and redirects user to DeFiChain's YouTube page

#### How to reproduce it (as minimally and precisely as possible):
• Go to Settings > About
• Click `YouTube` icon

#### Anything else we need to know?:
• Bug only on Android, no issue for iOS

**Comment by thedoublejay** [comment]
This works when you have YouTube installed. Just tested it on my device. Unfortunately we can't do anything about it as it's a system level config. On some phones, you can't even uninstall youtube.
