### ISSUE TITLE
`send`: info for reserved UTXO dfi

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#759]
![210831 v0 9 1 - iOS - Balances - 0 1a](https://user-images.githubusercontent.com/65014479/131493483-3c52f819-1526-428e-a911-442452e29987.jpg)

![210831 v0 9 1 - iOS - Balances - 0 1b](https://user-images.githubusercontent.com/65014479/131493511-51e1c1a3-d852-4bc1-a2fa-2b54617b7330.jpg)

#### What UI/UX improvements would you like to be implemented: 
• Currently, when user navigates from `AMOUNT BALANCE` screen to `Send to other wallet`, balance reflected in `Send to other wallet` is` -0.1` DFI 

> In `AMOUNT BALANCE` screen, balance = `0.55496217` DFI
> In `Send to other wallet` screen, balance = `0.45496217` DFI

Suggestion: 
• To display real balance, but is user click on `MAX`, show `MAX -0.1`
• Add `i` icon stating why is there a lower balance in other screens except main balance. 
• Copy: "0.1 DFI UTXO will be set aside for fees and such, this is your available balance to transact"

#### Why is this needed:
• Prevent users from being confused on why their balance reflected is different

#### Which component/screens does this concern?:
• `Send to other wallet`
• `Convert DFI` 

#### Anything else we need to know?:
https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Light-Wallet?page-id=287%3A11410&node-id=698%3A17615&viewport=241%2C48%2C0.8&scaling=scale-down&starting-point-node-id=698%3A17615&show-proto-sidebar=1

Note:

- [ ] This is only for UTXO DFI, for sending other tokens, we don't display this

**Comment by thedoublejay** [comment]
Linked to this ticket - https://github.com/DeFiCh/wallet/issues/736

**Comment by kyleleow** [comment]
@thedoublejay do i need to change all the current UI to match the new prototype? 
![image](https://user-images.githubusercontent.com/40191153/132430605-d7807c5e-5b07-4acd-9ad3-aa9f6afb9082.png)

---
Or do I only have to change the auto deduction logic and display the "`i` A small utxo amount is reserved for fees` onto the current convert screen?
