### ISSUE TITLE
`recovery words FAQ` - new screen

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#773]
#### What would you like to be added:
From Create Guidelines screen - View Recovery words 

Some things to consider: It should be reusable component (as it will be used on other screens). Also, it  should be a screen that can be called from anywhere (as we will consolidate them from Settings -> Knowledge Base).

- [ ] Accordion from description
- [ ] German translations

#### Why is this needed:
https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Light-Wallet?page-id=287%3A11410&node-id=642%3A17182&viewport=241%2C48%2C0.8&scaling=scale-down&starting-point-node-id=642%3A17235&show-proto-sidebar=1
<img width="349" alt="Screenshot 2021-09-02 at 5 03 13 PM" src="https://user-images.githubusercontent.com/25013382/131815819-7b3d31e8-f40d-422f-8e92-c51dc5af399b.png">

**Comment by izzycsy** [comment]
Acceptance Criteria: Updated design for Recovery Word FAQ

Android: 

- [ ] Check for any typo

iOS: 

- [ ] Check for any typo
