### ISSUE TITLE
`network detail screen`

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#774]
#### What would you like to be added:
From header, when you click, it will open this screen for more details. Last sync will be coming from interval polling.

#### Why is this needed:
https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Light-Wallet?page-id=287%3A11410&node-id=659%3A12498&viewport=241%2C48%2C0.8&scaling=scale-down&starting-point-node-id=665%3A12670&show-proto-sidebar=1
<img width="296" alt="Screenshot 2021-09-02 at 5 08 16 PM" src="https://user-images.githubusercontent.com/25013382/131816664-718bda91-9814-467d-97f2-61342f80b6ef.png">

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: On any screen were `Network` is visible, user to be able to view more details about network. 

**Android:**


**iOS:**
