### ISSUE TITLE
[Android] Wallet doesn't sync?!

### ISSUE THREAD

**Issue by Babwenbiber** [DeFiCh/wallet#781]
After providing the seed words my wallet got loaded.
Unfortunately, The wallet has 0 balance.
I triple checked the seed but this seems to be valid.

#### What happened:
balance of 0 and no transactions
#### What you expected to happen:
balance in sync with my balance of the desktop app
#### How to reproduce it (as minimally and precisely as possible):
Enter Seed and password -> check balance
#### Anything else we need to know?:
Using Hawaii P30lite

**Comment by thedoublejay** [comment]
@Babwenbiber Did you use the seed from desktop wallet? If yes, you cannot use it and must need to create a new one in the mobile wallet. You can transfer your funds from Desktop wallet to Mobile wallet. Just make sure you're using >v2.6.2 desktop wallet to be able to send to mobile app.

**Comment by Babwenbiber** [comment]
> @Babwenbiber Did you use the seed from desktop wallet? If yes, you cannot use it and must need to create a new one in the mobile wallet. You can transfer your funds from Desktop wallet to Mobile wallet. Just make sure you're using >v2.6.2 desktop wallet to be able to send to mobile app.

Yes, that's exactly the case.
Intuitively, it makes no sence to me that I have to choose to either use the desktop version or the mobile version.
However, I think I will not be the only one being confused by that fact and some customers might event throw away the app right away after not seeing the funds from the desktop wallet. You might stress this point out in some documentation.

**Comment by thedoublejay** [comment]
Hi @Babwenbiber, yes we're preparing for this documentation. Sorry for the inconvenience.
