### ISSUE TITLE
`offline mode` - updated screen

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#800]
#### What would you like to be added:
Update offline mode screen.

- [x] No need for button as it's automatically connects
- [x] Light and dark mode
- [x] Translation

#### Why is this needed:
![image](https://user-images.githubusercontent.com/25013382/132440188-c0b520b0-337b-4d32-af90-4f73278fff15.png)

**Comment by fullstackninja864** [comment]
Here is the ss for given implementation
![IMG_6472](https://user-images.githubusercontent.com/53080940/132460978-14581cb8-8de1-4ced-ad1a-0d1473e9cee7.PNG)
![IMG_6470](https://user-images.githubusercontent.com/53080940/132460986-fbcc8cfb-8889-46e5-9e11-f7c68dd7f5e0.PNG)

**Comment by fullstackninja864** [comment]
@thedoublejay as we are removing Try again button, do we need to update the node here?

*There seems to be a problem with the connection. Check your network `and try again.`*

**Comment by thedoublejay** [comment]
@fullstackninja864 yes we are removing the button. The copy from your screenshot should be ok.
