### ISSUE TITLE
`about screen` - updated design

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#813]
#### What would you like to be added:

- [ ] Remove link from settings for community page
- [ ] Update link from About -. Participate with active community -> community screen

https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Light-Wallet?node-id=841%3A29184&viewport=241%2C48%2C0.7&scaling=scale-down&starting-point-node-id=841%3A28305&show-proto-sidebar=1

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: `About` contents updated layout

**Android:**

`Settings` >`About` > displays: 
- [ ] Social media: YouTube, Twitter, Reddit, GitHub
- [ ] Knowledge base
- [ ] Participate with active community
- [ ] DeFiChain Explorer
- [ ] View official website
- [ ] Privacy policy
- [ ] Licenses
- [ ] Whitepaper


**iOS:**


`Settings` >`About` > displays: 
- [ ] Social media: YouTube, Twitter, Reddit, GitHub
- [ ] Knowledge base
- [ ] Participate with active community
- [ ] DeFiChain Explorer
- [ ] View official website
- [ ] Privacy policy
- [ ] Licenses
- [ ] Whitepaper
