### ISSUE TITLE
`section title` - updated design

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#814]
#### What would you like to be added:
![image](https://user-images.githubusercontent.com/25013382/132607234-b43a94c4-fe92-4166-a849-452bc4cb9d3b.png)

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: Updated design for `Balances`

**Android:**

- [ ] Scroll down, check there's sufficient space for tokens 
- [ ] Check icon + dToken description, alignment, colour etc.
- [ ] Select `RECEIVE` > go `back`
- [ ] Select `RECEIVE` > back via `Balances` button
- [ ] Total `DFI` = UTXO + Token
- [ ] DFI: Select `convert` > go `back` / back via `Balances` button
- [ ] DFI: Select `up arrow` > go `back` / back via `Balances` button
- [ ] dBTC, dETH, dUSDT,...: Select `>` / Select other area apart from `>`

**iOS:**

- [ ] Scroll down, check there's sufficient space for tokens 
- [ ] Check icon + dToken description, alignment, colour etc.
- [ ] Select `RECEIVE` > go `back`
- [ ] Select `RECEIVE` > back via `Balances` button
- [ ] Total `DFI` = UTXO + Token
- [ ] DFI: Select `convert` > go `back` / back via `Balances` button
- [ ] DFI: Select `up arrow` > go `back` / back via `Balances` button
- [ ] dBTC, dETH, dUSDT,...: Select `>` / Select other area apart from `>`
