### ISSUE TITLE
`receive` - updated design

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#815]
#### What would you like to be added:
Don't implement the alert when clicking on copy address. Keep the current behavior now

![image](https://user-images.githubusercontent.com/25013382/132607352-ad55bb75-25be-4241-a5b9-405de3ef2256.png)

#### Why is this needed:
https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Light-Wallet?node-id=669%3A13469&viewport=241%2C48%2C0.7&scaling=scale-down&starting-point-node-id=642%3A17235&show-proto-sidebar=1

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: `RECEIVE` screen updated layout

**Android:**

`Balances` >`RECEIVE` > displays & redirects user to: 

- [ ] Updated description: "Use QR or Address..."
- [ ] QR code able to reflect user's address when scanned
- [ ] Able to receive token from scanning QR code
- [ ] Able to copy address
- [ ] Able to share address > ShareMe / Bluetooth / Chat ... options (depending on device's available applications)
- [ ] Able to receive token by scanning QR code with another device 

**iOS:**

`Balances` >`RECEIVE` > displays & redirects user to: 

- [ ] Updated description: "Use QR or Address..."
- [ ] QR code able to reflect user's address when scanned
- [ ] Able to receive token from scanning QR code
- [ ] Able to copy address
- [ ] Able to share address > AirDrop / Messages / Telegram ... options (depending on device's available applications)
- [ ] Able to receive token by scanning QR code with another device
