### ISSUE TITLE
`DEX` - guidelines page

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#816]
#### What would you like to be added:
Display only on initial install. Can be stored in local storage.

https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Light-Wallet?node-id=888%3A26039&viewport=241%2C48%2C0.7&scaling=scale-down&starting-point-node-id=888%3A26840&show-proto-sidebar=1
![image](https://user-images.githubusercontent.com/25013382/132607560-0b134290-8c90-48b5-839c-2787a595248c.png)

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: `Guide` for DEX is display **only** on 1st installation.

**Android:**

- [ ] `Create wallet` >`DEX` > displays `Guide`
- [ ] At `Guide` screen > select `x` / select `CLOSE`

**iOS:**

- [ ] `Create wallet` >`DEX` > displays `Guide`
- [ ] At `Guide` screen > select `x` / select `CLOSE`

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: `Guide` for DEX is display **only** on 1st installation.

**Android:**

- [x] `Update wallet` >`DEX` > displays `Guide`
- [x] Check spelling, missing punctuations, text alignment, etc.
- [x] At `Guide` screen > select `x` / select `CLOSE`

**iOS:**
- [x] `Update wallet` >`DEX` > displays `Guide`
- [x] Check spelling, missing punctuations, text alignment, etc.
- [x] At `Guide` screen > select `x` / select `CLOSE`
