### ISSUE TITLE
Transactions not showing in Transaction Screen

### ISSUE THREAD

**Issue by AndErazor** [DeFiCh/wallet#839]
#### What happened:
I created a new wallet with the App on IOS, transferred some DFI and some dUSDC and USDC-DFI LM Token to it. All transfers went smoothly but under transactions I only see the DFI transaction, both other transactions are missing.

#### What you expected to happen:
All transactions are shown under transactions

#### How to reproduce it (as minimally and precisely as possible):
Create a new wallet and transfer some tokens

**Comment by thedoublejay** [comment]
Hi @AndErazor, we're only supporting UTXO transactions currently. Other types of transactions (LM, Swap etc.) will be available on future releases.
