### ISSUE TITLE
`translations` - proper translations for transaction authorization

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#853]
#### What happened:
Labels are translated prior to calling them. So when language is updated via settings page, the old translations are persisted.
#### Anything else we need to know?:
![File](https://user-images.githubusercontent.com/25013382/133200733-475bc26f-bfba-478a-a355-4d98ce3d2494.jpg)
![File (1)](https://user-images.githubusercontent.com/25013382/133200739-16daa72b-22a1-49d2-958b-307eab7498b1.jpg)

**Comment by izzycsy** [comment]
Related issue: https://github.com/DeFiCh/wallet/issues/854

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: Translation should apply for button(s) & action(s)

**Android:**
Change language to German / Chinese > Send / Swap DFI > check:

- [ ] `CANCEL` 
- [ ] `Please enter passcode to securely sign your transaction` 
- [ ] `Signing...`

From #854 : 
In `Transaction` screen: 
- [ ] Check whole screen's translation

**iOS:**
Change language to German / Chinese > Send / Swap DFI > check:

- [ ] `CANCEL` 
- [ ] `Please enter passcode to securely sign your transaction` 
- [ ] `Signing...`

From #854 : 
In `Transaction` screen: 
- [ ] Check whole screen's translation

**Comment by thedoublejay** [comment]
@izzycsy @dwivedinalin need to check if this issue still persists. Otherwise, feel free to close it

**Comment by kyleleow** [comment]
This issue is not applicable anymore after we switched to the current bottom sheet modal design
