### ISSUE TITLE
`translation` - missing zh translation in recovery words faq

### ISSUE THREAD

**Issue by kyleleow** [DeFiCh/wallet#857]
#### What translation improvements would you like to be implemented:
- Add zh-hans and zh-hant translation for recovery words faq screen

#### Which component/screens does this concern?:
- Recovery Words Faq screen

**Comment by izzycsy** [comment]
`Acceptance Criteria`
Expected: Translation should apply for `FAQ — Recovery Words` screen 

**Android:**
Change language to German / Chinese > `FAQ` screen > `Recovery Words` > check:

- [ ] Check whole screen's translation
