### ISSUE TITLE
FC Update - Composite Swap

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#909]
#### What would you like to be added:

With Fort Canning `v2.0.0` update, Composite Swap will be released allowing for 1 jump composite swap. We need to implement that functionality on Light Wallet as a quick swap mechanism.

Being a quick swap feature, similar to how the crypto exchange has them to quickly swap their tokens. Hence the UX must be very straightforward. We can have this as a feature banner on top of the DEX page.

#### What is Composite Swap?
E.g. with 2 PoolPair `USDT - DFI` and `BTC - DFI`

You can do a composite swap from `USDT` to `BTC` via a composite swap of that 2 pair with 1 hop.

#### APIs?
We don't need additional APIs to be exposed as all available composite swappable tokens are PoolPair of all Left+Right tokens.

PR for Composite Swap Dftx - https://github.com/DeFiCh/jellyfish/pull/776/files

- [ ] Add logic for select conversion path for composite swap drafting

/area dex

**Comment by fuxingloh** [comment]
In the Fort Canning update, there will be a new DfTx called `CompositePoolSwap` for the new swap mechanism.

This will be a new DfTx and the old PoolSwap DfTx will continue to be supported but slated for deprecation.

**Comment by izzycsy** [comment]
Acceptance Criteria: Composite swap from `DST` to `DST`

Android: 
_Swap_
- [ ] dETH to dBTC
- [ ] dETH to dUSDT
- [ ] dETH to dUSDC

- [ ] dBTC to dETH
- [ ] dBTC to dUSDT
- [ ] dBTC to dUSDC

- [ ] dUSDT to dETH
- [ ] dUSDT to dBTC
- [ ] dUSDT to dUSDC

- [ ] dUSDC to dETH
- [ ] dUSDC to dBTC
- [ ] dUSDC to dUSDT

iOS: 
_Swap_
- [ ] dETH to dBTC
- [ ] dETH to dUSDT
- [ ] dETH to dUSDC

- [ ] dBTC to dETH
- [ ] dBTC to dUSDT
- [ ] dBTC to dUSDC

- [ ] dUSDT to dETH
- [ ] dUSDT to dBTC
- [ ] dUSDT to dUSDC

- [ ] dUSDC to dETH
- [ ] dUSDC to dBTC
- [ ] dUSDC to dUSDT

**Comment by izzycsy** [comment]
Acceptance Criteria: Composite swap from `DST` to `DST`

Android: 
_Swap_
- [ ] dETH to dBTC
- [ ] dETH to dUSDT

- [ ] dBTC to dETH
- [ ] dBTC to dUSDT

- [ ] dUSDT to dETH
- [ ] dUSDT to dBTC

- [ ] dUSDC to dUSDT

iOS: 
_Swap_
- [ ] dETH to dBTC
- [ ] dETH to dUSDT

- [ ] dBTC to dETH
- [ ] dBTC to dUSDT

- [ ] dUSDT to dETH
- [ ] dUSDT to dBTC

- [ ] dUSDC to dUSDT
