### ISSUE TITLE
Address Switching - Generating and using new Address in Light Wallet

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#910]
#### What would you like to be added:

Currently, on the Light Wallet, only `index:0` addresses are used. The internal implementation of `jellyfish-wallet` allows multi addresses to be used. This issue calls for implementing wallet management with multi addresses supported. 

1. Listing all the active addresses within the wallet.
2. Generating a new Address `n+1` and storing the max `index` to know how many addresses have been generated.
3. Discovering all addresses on the wallet via https://github.com/DeFiCh/jellyfish/blob/47c3dabe7995bbfe8e7812ea1dfd1e885a6355f7/packages/jellyfish-wallet/src/wallet.ts#L69-L77 and storing the max indexes.

Assumptions:
- We are not using Node-like address management where all addresses are pooled together with one balance, for simplicity reasons each address is an account within the wallet system that the user can switch to.
- We are following a Metamask like experience
- We are not going to store all addresses like a wallet.dat file, we just need to track where the max index is.

Max Index Length determines the maximum number of activated addresses allowed in the wallet. Accounts are considered active if the address contains any transaction activity. You can always generate an address (+1). You can't generate another address until you have activated the previous address. You active a previous address by using it. (contains any transaction activity)

- `Max Index Length = 1`, only 1 default address
- `Max Index Length = 2`, 2 addresses [Active, Active/In-Inactive]
- `Max Index Length = 3`, 3 addresses [Active, Active, Active/In-Inactive]

![image](https://user-images.githubusercontent.com/25013382/140669964-a33cc645-e09d-48ac-bab9-2158e6052583.png)

* Avatars of wallet are already implemented.

/area core wallet

**Comment by fullstackninja864** [comment]
@thedoublejay If user switch the address (suppose selected address at index 4) and then closed the app completely. then we will be saving his selection or will load 0th address by default when he revisit the app

**Comment by thedoublejay** [comment]
@fullstackninja864 yes, need to save selection

**Comment by thedoublejay** [comment]
@izzycsy Need some test cases for this as it will be released for 0.15.0. Some scenarios to be checked:

1. Generate new address if active
2. Refresh will retain selected address
3. Restoring will load addresses
4. Sending one will transfer to another
5. Current active should have active tab on display
6. Change address should update receive screen page
7. Creating a new wallet should not display addresses from old wallet
- On fresh create and on restart of app

**Comment by dwivedinalin** [comment]
**Android:**

- [ ]  Balances > Check whether address present > make a transaction > Check whether able to add a new address

- [ ]  Balances > Check whether address present > do not make any transaction > check whether unable to add a new
         address
- [ ]  Balances > Check whether address present > make a transaction > Check whether able to add a new address > make a 
        transaction from new address > Check whether able to add a new address 

**IOS:**

- [ ] Balances > Check whether address present > make a transaction > Check whether able to add a new address
- [ ] Balances > Check whether address present > do not make any transaction > check whether unable to add a new
        address 
- [ ] Balances > Check whether address present > make a transaction > Check whether able to add a new address > make a 
        transaction from new address > Check whether able to add a new address
