### ISSUE TITLE
`Privacy Lock` - Updates

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#911]
#### What would you like to be added:

- [x] Update label from Privacy Lock to include Tech (Face ID, etc.)
- [x] ~~Add an Alert to display mechanics of Privacy Lock~~ Add a label below privacy lock

**Comment by izzycsy** [comment]
Moving the test cases from #632 to this thread: 

Acceptance Criteria: Privacy Lock to pass all scenarios as stated. 

**Android**
1. - [x] Enable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Open app - Trigger Prompt
2. - [x] Disable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Open app - No Prompt

3. - [x] Enable Privacy Lock - Trigger Prompt - Pattern - Quit app - Open app - Trigger Prompt
4. - [x] Disable Privacy Lock - Trigger Prompt - Pattern - Quit App - Open app - No Prompt

5. - [x] Enable Privacy Lock - Trigger Prompt - Pin - Quit app - Open app - Trigger Prompt
6. - [x] Disable Privacy Lock - Trigger Prompt - Pin - Quit app - Open app - No Prompt

7. - [x] Enable Privacy Lock - Trigger Prompt - Fingerprint - Unlink Wallet - Restore Wallet - Privacy Lock should be enabled
8. - [x] Continue from 7 - Quit App - Open App - Trigger prompt

9. - [x] Enable Privacy Lock - Switch to another app - Go back immediately - No prompt
10. - [x] Enable Privacy Lock - Switch to another app - Wait 1 minute - Trigger prompt

11. - [ ] Enable Privacy Lock - Lock & unlock device - No prompt triggered
12. - [x] Disable Privacy Lock - Lock & unlock device - Trigger prompt

13. - [ ] Enable Privacy Lock - Lock device - Unlock device - Cancel prompt - Prompt should remain (try it 3 times)
14. - [ ] Continue from 12 - Cancel Prompt - App should remain open
15. - [ ] Enable Privacy Lock - Wait 1 minute - Cancel prompt - Minimise and open app again - Prompt should remain (try it 3 times)
16. - [x] Disable Privacy Lock - Wait 1 minute - No prompt

17. - [x] Enable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Change Fingerprint on device - Open app - Try with old fingerprint - Should fail - Try with new Fingerprint - Should pass 
18. - [x] Same with 16 but try with updated pattern / pin

19. - [x] Enable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Remove Fingerprint - Open app - Trigger prompt (pattern / pin)
20. - [x] Enable Privacy Lock - Trigger Prompt - Pattern / pin - Quit app - Remove pattern / pin - Open app - No prompt
21. - [x] Continue from 20 - Re-enable Fingerprint & pattern / pin - Open app - Trigger prompt
22. - [ ] From MainNet, activate Privacy Lock - Switch to Playground Network - Switch back to MainNet - Should trigger prompt 


**iOS**
1. - [ ] Enable Privacy Lock - Trigger Prompt - Touch ID - Quit app - Open app - Trigger prompt
2. - [ ] Disable Privacy Lock - Trigger Prompt - Touch ID  - Quit app - Open app- No prompt

3. - [x] Enable Privacy Lock - Trigger Prompt - Passcode - Quit app - Open app - Trigger prompt
4. - [x] Disable Privacy Lock - Trigger Prompt - Passcode  - Quit app - Open app - No prompt

5. - [ ] Enable Privacy Lock - Trigger Prompt - Face ID - Quit app - Open app - Trigger prompt
6. - [ ] Disable Privacy Lock - Trigger Prompt - Face ID - Quit app - Open app - No prompt

7. - [x] Enable Privacy Lock - Trigger Prompt - Touch ID / Pass code / Face ID - Unlink Wallet - Restore Wallet - Privacy Lock is enabled
8. - [x] Continue from 7 - Quit App - Open App - Trigger prompt

9. - [x] Enable Privacy Lock - Switch to another other app - Go back immediately - No prompt
10. - [x] Enable Privacy Lock - Switch to another app - Wait 1 minute - Trigger prompt

11. - [ ] Enable Privacy Lock - Lock & unlock device - Trigger Prompt
12. - [x] Disable Privacy Lock - Lock & unlock device - Trigger Prompt

13. - [ ] Enable Privacy Lock - Lock device - Unlock device - Cancel prompt - Prompt should remain (try it 3 times)
14. - [ ] Continue from 13 - Cancel Prompt - App should remain open
15. - [ ] Enable Privacy Lock - Wait 1 minute - Cancel prompt - Minimise and open app again - Prompt should remain (try it 3 times)
16. - [x] Disable Privacy Lock - Wait 1 minute - No prompt

17. - [ ] Enable Privacy Lock - Trigger Prompt - Face ID - Quit App - Try with different Face ID on Device - Should fail - Try with own Face ID - Should pass 
18. - [ ] Same with 17 but test with updated Touch ID / passcode

19. - [ ] Enable Privacy Lock - Trigger Prompt - Face ID / passcode - Quit App - Turn off Face ID - Open App - Trigger prompt (passcode)
20. - [x] Enable Privacy Lock - Trigger Prompt - Face ID / passcode - Quit App - Turn off Face ID and Passcode - Open app - No prompt
21. - [x] Continue from 20 - Re-enable Face ID / Touch ID / passcode - Open app - Trigger prompt
22. - [ ] From MainNet, activate Privacy Lock - Switch to Playground Network - Switch back to MainNet - Should trigger prompt

**Comment by izzycsy** [comment]
**Android**
Actual: 
14. Enable Privacy Lock - Lock device - Wait 1 minute - Unlock device - Cancel prompt - Prompt should remain (try it 3 times)
15. Continue from 14 - Cancel Prompt - App should remain open (from 4th time and beyond)

> After cancelling prompt, user remains in app with blank screen. When user close and opens app, prompt appears again. No way to access app if user forgets pin/pattern/fingerprint

**Comment by izzycsy** [comment]
**iPhone**
Actual
5. - [ ] Enable Privacy Lock - Trigger Prompt - Face ID - Quit app - Open app - Trigger prompt
6. - [ ] Disable Privacy Lock - Trigger Prompt - Face ID - Quit app - Open app - No prompt

**Comment by izzycsy** [comment]
- [ ] 10.  Enable Privacy Lock - Switch to another app - Wait 1 minute - Trigger prompt
- [ ] 13. Enable Privacy Lock - Lock device - Wait 1 minute - Unlock device - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt)
- [ ] 14. Continue from 13 - Cancel Prompt - App should remain open & prompt should remain (no matter number of attempts to cancel prompt)
- [ ] 15. Enable Privacy Lock - Minimise - Wait 1 minute - Open app again - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt)

> Prompt does not trigger after 1 minute, user able to access app so long as iPhone is unlocked

**Comment by izzycsy** [comment]
Uploading 210920 v0.10.6 - iOS -  Privacy Lock - 21 Does not trigger prompt when switching network.MP4…


**iPhone**
Actual: 

- [ ]  21. From MainNet, activate Privacy Lock - Switch to Playground Network - Switch back to MainNet - Should trigger prompt

**Comment by jtlntno-cake** [comment]
Here's an updated design to reflect the updates here. Idea is to clarify the function to the users in a succinct way. Also, we want to indicated which authentication method do we use whenever biometric auth is available. 


![image](https://user-images.githubusercontent.com/85162376/134104119-f2dffef2-4d0a-4550-b748-6ec422d60840.png) [Figma link](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/Mobile-Light-Wallet?node-id=841%3A28270)

cc: @thedoublejay @fuxingloh

**Comment by kyleleow** [comment]
@jtlntno-cake i believe this is for iOS only, do we need to breakdown for android devices too? Do you know the naming for android? 
- Secure with fingerprint?
- Secure with face recognition?


> Here's an updated design to reflect the updates here. Idea is to clarify the function to the users in a succinct way. Also, we want to indicated which authentication method do we use whenever biometric auth is available.
> 
> ![image](https://user-images.githubusercontent.com/85162376/134104119-f2dffef2-4d0a-4550-b748-6ec422d60840.png) [Figma link](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/Mobile-Light-Wallet?node-id=841%3A28270)
> 
> cc: @thedoublejay @fuxingloh @izzycsy

**Comment by thedoublejay** [comment]
@kyleleow yep you can use that for now

**Comment by kyleleow** [comment]
@thedoublejay based on current [expo sdk](https://docs.expo.dev/versions/latest/sdk/local-authentication/#localauthenticationgetenrolledlevelasync) we can't differentiate between PIN or pattern unlock, can i display the label with:
- "Secure with PIN or pattern" ?

**Comment by thedoublejay** [comment]
@kyleleow Just use secure with device lock

**Comment by thedoublejay** [comment]
@izzycsy We also need some tests cases for this to handle different labels (e.g, Secure with Face ID, Secure with Touch ID etc.)

**Comment by izzycsy** [comment]
Acceptance Criteria: Privacy Lock to pass all scenarios as stated. 

**Android**

- [x] 1. Enable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Open app - Trigger Prompt
- [x] 2. Disable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Open app - No Prompt


- [x] 3. Enable Privacy Lock - Trigger Prompt - Pattern - Quit app - Open app - Trigger Prompt
- [x] 4. Disable Privacy Lock - Trigger Prompt - Pattern - Quit App - Open app - No Prompt

- [x] 5. Enable Privacy Lock - Trigger Prompt - Pin - Quit app - Open app - Trigger Prompt
- [x] 6. Disable Privacy Lock - Trigger Prompt - Pin - Quit app - Open app - No Prompt

- [x] 7. Enable Privacy Lock - Trigger Prompt - Pin - Quit app - Change system settings to Pattern - Open app - Trigger Prompt - Able to access via Pattern
- [x] 8. Continue from 7 - Quit App - Open App - Trigger prompt

- [ ] 9. Enable Privacy Lock - Trigger Prompt - Fingerprint - Unlink Wallet - Restore Wallet - Privacy Lock should be enabled

- [x] 10. Enable Privacy Lock - Switch to another app - Go back immediately - No prompt
- [x] 11. Enable Privacy Lock - Switch to another app - Wait 1 minute - Trigger prompt

- [x] 12. Enable Privacy Lock - Lock & unlock device - No prompt triggered
- [x] 13. Disable Privacy Lock - Lock & unlock device - No prompt triggered

- [x] 14. Enable Privacy Lock - Lock device - Wait 1 minute - Unlock device - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt) 
- [ ] 15. Continue from 14 - Cancel Prompt - App should remain open & prompt should remain (no matter number of attempts to cancel prompt) 
- [ ] 16. Enable Privacy Lock - Minimise - Wait 1 minute - Open app again - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt)

- [x] 17. Enable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Change Fingerprint on device - Open app - Try with old fingerprint - Should fail - Try with new Fingerprint - Should pass 
- [x] 18. Same with 17 but try with updated pattern / pin

- [x] 19. Enable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Remove Fingerprint - Open app - Trigger prompt (pattern / pin)
- [x] 20. Enable Privacy Lock - Trigger Prompt - Pattern / pin - Quit app - Remove pattern / pin - Open app - No prompt
- [x] 21. Continue from 20 - Re-enable Fingerprint & pattern / pin - Open app - Trigger prompt
- [ ] 22. From MainNet, activate Privacy Lock - Switch to Playground Network - Switch back to MainNet - Should trigger prompt 


**iOS**

- [x] `Privacy lock` label updated to `Secure with —`

- [ ] 1. Enable `Secure with Touch ID` - Trigger Prompt - Touch ID - Quit app - Open app - Trigger prompt
- [ ] 2. Disable `Secure with Touch ID` - Trigger Prompt - Touch ID  - Quit app - Open app- No prompt

- [ ] 3. Enable `Secure with pincode` - Trigger Prompt - Pincode - Quit app - Open app - Trigger prompt
- [ ] 4. Disable `Secure with pincode` - Trigger Prompt - Pincode  - Quit app - Open app - No prompt

- [ ] 5. Enable `Secure with Face ID` - Trigger Prompt - Face ID - Quit app - Open app - Trigger prompt
- [x] 6. Disable `Secure with Face ID` - Trigger Prompt - Face ID - Quit app - Open app - No prompt

- [x] 7. Enable `Secure with —` - Trigger Prompt - Touch ID / Pincode / Face ID- Unlink Wallet - Restore Wallet - `Secure with —` remains enabled
- [ ] 8. Continue from 7 - Quit App - Open App - Trigger prompt

- [x] 9. Enable `Secure with —` - Switch to another other app - Go back immediately - No prompt
- [x] 10. Enable `Secure with —` - Switch to another app - Wait 1 minute - Trigger prompt

- [x] 11. Enable `Secure with —` - Lock & unlock device - No prompt triggered
- [x] 12. Disable `Secure with —` - Lock & unlock device - No prompt triggered

- [x] 13. Enable `Secure with —` - Lock device - Wait 1 minute - Unlock device - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt) 
- [x] 14. Continue from 13 - Cancel Prompt - App should remain open & prompt should remain (no matter number of attempts to cancel prompt) 
- [x] 15. Enable `Secure with —` - Minimise - Wait 1 minute - Open app again - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt)

- [x] 16. Enable `Secure with —` - Trigger Prompt - Face ID - Quit App - Try with different Face ID on Device - Should fail - Try with own Face ID - Should pass 
- [x] 17. Same with 16 but test with updated Touch ID / Pincode

- [x] 18. Enable `Secure with —` - Trigger Prompt - Face ID / Pincode - Quit App - In device's **Settings** >**Face ID & Passcode** > **Other Apps** > toggle off FaceID for DeFiChain - Open DeFiChain App - Trigger prompt (pincode)
- [x] 19. Enable `Secure with —` - Trigger Prompt - passcode - Quit App - In device, turn off passcode - Open DeFiChain App - `Secure with —` option should not be available
- [x] 20. Continue from 19 - Re-enable Face ID / Touch ID / pincode - Open app - Trigger prompt
- [ ] 21. From MainNet, activate `Secure with —` - Switch to Playground Network - Switch back to MainNet - Should trigger prompt

**Comment by izzycsy** [comment]
https://user-images.githubusercontent.com/65014479/135253456-e3d70c3a-6264-43ed-aa8c-a8e8aa662b9e.mov


**Android:** 
Expected:
- [ ] 13. `Enable Secure with —` - Lock device - Wait 1 minute - Unlock device - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt)
- [ ]  14. Continue from 13 - Cancel Prompt - App should remain open & prompt should remain (no matter number of attempts to cancel prompt)
- [ ]  15. `Enable Secure with —` - Minimise - Wait 1 minute - Open app again - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt)

> Actual: 
When prompt is cancelled, does not re-appear

**Comment by izzycsy** [comment]
**iOS:** 
Expected:
- [ ] 5. Enable Secure with Face ID - Trigger Prompt - Face ID - Quit app - Open app - Trigger prompt

> Reported in #971

**Comment by izzycsy** [comment]
https://user-images.githubusercontent.com/65014479/135253569-efe9aa0b-3ff7-4257-9451-778a99d81cc9.MP4


**Android:**
Expected:
- [ ] 22. From MainNet, activate `Privacy Lock` - Switch to Playground Network - Switch back to MainNet - Should trigger prompt
> Actual: 
Switched network, did not trigger prompt



**iOS:** 
Expected:
- [ ] 21. From MainNet, activate `Secure with —` - Switch to Playground Network - Switch back to MainNet - Should trigger prompt

> Actual: 
Switched network, did not trigger prompt

**Comment by izzycsy** [comment]
Acceptance Criteria: Privacy Lock to pass all scenarios as stated. 

**Android**

- [ ] 1. Enable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Open app - Trigger Prompt
- [ ] 2. Disable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Open app - No Prompt


- [ ] 3. Enable Privacy Lock - Trigger Prompt - Pattern - Quit app - Open app - Trigger Prompt
- [ ] 4. Disable Privacy Lock - Trigger Prompt - Pattern - Quit App - Open app - No Prompt

- [ ] 5. Enable Privacy Lock - Trigger Prompt - Pin - Quit app - Open app - Trigger Prompt
- [ ] 6. Disable Privacy Lock - Trigger Prompt - Pin - Quit app - Open app - No Prompt

- [ ] 7. Enable Privacy Lock - Trigger Prompt - Pin - Quit app - Change system settings to Pattern - Open app - Trigger Prompt - Able to access via Pattern
- [ ] 8. Continue from 7 - Quit App - Open App - Trigger prompt

- [ ] 9. Enable Privacy Lock - Trigger Prompt - Fingerprint - Unlink Wallet - Restore Wallet - Privacy Lock should be enabled

- [ ] 10. Enable Privacy Lock - Switch to another app - Go back immediately - No prompt
- [ ] 11. Enable Privacy Lock - Switch to another app - Wait 1 minute - Trigger prompt

- [ ] 12. Enable Privacy Lock - Lock & unlock device - No prompt triggered
- [ ] 13. Disable Privacy Lock - Lock & unlock device - No prompt triggered

- [ ] 14. Enable Privacy Lock - Lock device - Wait 1 minute - Unlock device - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt) 
- [ ] 15. Continue from 14 - Cancel Prompt - App should remain open & prompt should remain (no matter number of attempts to cancel prompt) 
- [ ] 16. Enable Privacy Lock - Minimise - Wait 1 minute - Open app again - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt)

- [ ] 17. Enable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Change Fingerprint on device - Open app - Try with old fingerprint - Should fail - Try with new Fingerprint - Should pass 
- [ ] 18. Same with 17 but try with updated pattern / pin

- [ ] 19. Enable Privacy Lock - Trigger Prompt - Fingerprint - Quit app - Remove Fingerprint - Open app - Trigger prompt (pattern / pin)
- [ ] 20. Enable Privacy Lock - Trigger Prompt - Pattern / pin - Quit app - Remove pattern / pin - Open app - No prompt
- [ ] 21. Continue from 20 - Re-enable Fingerprint & pattern / pin - Open app - Trigger prompt
- [ ] 22. From MainNet, activate Privacy Lock - Switch to Playground Network - Switch back to MainNet - Should trigger prompt 


**iOS**

- [ ] `Privacy lock` label updated to `Secure with —`

- [ ] 1. Enable `Secure with Touch ID` - Trigger Prompt - Touch ID - Quit app - Open app - Trigger prompt
- [ ] 2. Disable `Secure with Touch ID` - Trigger Prompt - Touch ID  - Quit app - Open app- No prompt

- [ ] 3. Enable `Secure with pincode` - Trigger Prompt - Pincode - Quit app - Open app - Trigger prompt
- [ ] 4. Disable `Secure with pincode` - Trigger Prompt - Pincode  - Quit app - Open app - No prompt

- [ ] 5. Enable `Secure with Face ID` - Trigger Prompt - Face ID - Quit app - Open app - Trigger prompt
- [ ] 6. Disable `Secure with Face ID` - Trigger Prompt - Face ID - Quit app - Open app - No prompt

- [ ] 7. Enable `Secure with —` - Trigger Prompt - Touch ID / Pincode / Face ID- Unlink Wallet - Restore Wallet - `Secure with —` remains enabled
- [ ] 8. Continue from 7 - Quit App - Open App - Trigger prompt

- [ ] 9. Enable `Secure with —` - Switch to another other app - Go back immediately - No prompt
- [ ] 10. Enable `Secure with —` - Switch to another app - Wait 1 minute - Trigger prompt

- [ ] 11. Enable `Secure with —` - Lock & unlock device - No prompt triggered
- [ ] 12. Disable `Secure with —` - Lock & unlock device - No prompt triggered

- [ ] 13. Enable `Secure with —` - Lock device - Wait 1 minute - Unlock device - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt) 
- [ ] 14. Continue from 13 - Cancel Prompt - App should remain open & prompt should remain (no matter number of attempts to cancel prompt) 
- [ ] 15. Enable `Secure with —` - Minimise - Wait 1 minute - Open app again - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt)

- [ ] 16. Enable `Secure with —` - Trigger Prompt - Face ID - Quit App - Try with different Face ID on Device - Should fail - Try with own Face ID - Should pass 
- [ ] 17. Same with 16 but test with updated Touch ID / Pincode

- [ ] 18. Enable `Secure with —` - Trigger Prompt - Face ID / Pincode - Quit App - In device's **Settings** >**Face ID & Passcode** > **Other Apps** > toggle off FaceID for DeFiChain - Open DeFiChain App - Trigger prompt (pincode)
- [ ] 19. Enable `Secure with —` - Trigger Prompt - passcode - Quit App - In device, turn off passcode - Open DeFiChain App - `Secure with —` option should not be available
- [ ] 20. Continue from 19 - Re-enable Face ID / Touch ID / pincode - Open app - Trigger prompt
- [ ] 21. From MainNet, activate `Secure with —` - Switch to Playground Network - Switch back to MainNet - Should trigger prompt

**Comment by izzycsy** [comment]
https://user-images.githubusercontent.com/65014479/133974739-3c1a22a4-bd56-4b65-8ba6-7f789ecf95bc.MP4

**Android**
Actual: 

- [ ] 22. From MainNet, activate Privacy Lock - Switch to Playground Network - Switch back to MainNet - Should trigger prompt

**iPhone**
Actual: 

- [ ]  21. From MainNet, activate Privacy Lock - Switch to Playground Network - Switch back to MainNet - Should trigger prompt

> Both Android & iPhone, does not trigger prompt after switching network

**Comment by izzycsy** [comment]
Uploading Does not re-trigger prompt.MOV…


**Android:** 
Expected:
- [ ] 14. Enable `Secure with biometric` - Lock device - Wait 1 minute - Unlock device - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt) 
- [ ] 15. Continue from 14 - Cancel Prompt - App should remain open & prompt should remain (no matter number of attempts to cancel prompt) 
- [ ] 16. Enable `Secure with biometric` - Minimise - Wait 1 minute - Open app again - Cancel prompt - Prompt should remain (no matter number of attempts to cancel prompt)

> Actual: 
When prompt is cancelled, does not re-appear
