### ISSUE TITLE
`estimated fee` - add to send and convert screen

### ISSUE THREAD

**Issue by kyleleow** [DeFiCh/wallet#913]
#### What would you like to be added:
- Add estimated fee info into send and convert screen only when amount input is filled
![image](https://user-images.githubusercontent.com/40191153/133975740-5e77ee73-a196-4880-9c7b-04402842f33e.png)

#### Why is this needed:
- To inform user of transaction fee

**Comment by izzycsy** [comment]
Refer to test case here: #946
