### ISSUE TITLE
`convert` - update UI and logic to display transaction amount and total balance

### ISSUE THREAD

**Issue by kyleleow** [DeFiCh/wallet#914]
#### What would you like to be added:
- Update UI and logic to display transaction amount and total balance based on new design
![image](https://user-images.githubusercontent.com/40191153/133975983-8c8ad134-c4bd-4857-b3e4-dfb858911169.png)
- Add horizontal rule UI behind the "toggle conversion mode button"

#### Why is this needed:
- To match the latest design v0.10.0

**Comment by izzycsy** [comment]
Acceptance Criteria: Transaction amount and total balance to be updated based on new design

Android: 
- [ ] Send > Convert to `DFI (Token)` > Input amount > `After conversion` should display + `You will have ____`> Balance should add up
- [ ] Send > Convert to `DFI (UTXO)` > Input amount > `After conversion` should display + `You will have ____`> Balance should add up

iOS:
- [ ] Send > Convert to `DFI (Token)` > Input amount > `After conversion` should display + `You will have ____`> Balance should add up
- [ ] Send > Convert to `DFI (UTXO)` > Input amount > `After conversion` should display + `You will have ____`> Balance should add up
