### ISSUE TITLE
Center align all button text to avoid breaking the UI

### ISSUE THREAD

**Issue by fullstackninja864** [DeFiCh/wallet#926]
#### Why is this needed:

Center align all button text to avoid breaking the UI (Checkout the pink button)
![image](https://user-images.githubusercontent.com/53080940/134513903-74d561cf-0b96-43d6-b924-29176837b345.png)

**Comment by izzycsy** [comment]
Acceptance Criteria: Center align all `pink` buttons 

Android:
- [ ] Settings > Switch network > Create wallet > Check `view 24 words` button

IOS: 
- [ ] Settings > Switch network > Create wallet > Check `view 24 words` button
