### ISSUE TITLE
`Pool Swap` - Updated input fields

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#929]
#### What would you like to be added:
https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Mobile-Light-Wallet?node-id=1461%3A31134&viewport=241%2C48%2C0.98&scaling=scale-down&starting-point-node-id=1470%3A54060&show-proto-sidebar=1
#### Why is this needed:
![image](https://user-images.githubusercontent.com/25013382/134601102-3969fce2-8397-4bef-b15e-e30fd735cbb4.png)

**Comment by kyleleow** [comment]
@thedoublejay should i update the bottom summary UI too? For example the slippage tolerance 
![image](https://user-images.githubusercontent.com/40191153/134610756-3e8837df-2c70-42cd-9f7f-b7eb84571963.png)

**Comment by thedoublejay** [comment]
> @thedoublejay should i update the bottom summary UI too? For example the slippage tolerance 
> ![image](https://user-images.githubusercontent.com/40191153/134610756-3e8837df-2c70-42cd-9f7f-b7eb84571963.png)
> 

You can do it on next iterations. Important part is the input fields so it's consistent with Send, Add LP etc.
