### ISSUE TITLE
`confirmation` - updated summary

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#942]
#### What would you like to be added:
https://www.figma.com/proto/SDIpZciuxJlUf4xf8yheiY/Mobile-Light-Wallet?node-id=809%3A21805&viewport=241%2C48%2C0.7&scaling=scale-down&starting-point-node-id=809%3A21869&show-proto-sidebar=1
![image](https://user-images.githubusercontent.com/25013382/135005619-2d1d2535-44db-4c16-a549-af6c7ffa925b.png)

**Comment by kyleleow** [comment]
Since we are still pending on #554 , i won't be adding the "Conversion required" for now

**Comment by kyleleow** [comment]
@jtlntno-cake Also pending UI for "Remove Liquidity" screen now

**Comment by izzycsy** [comment]
Test cases here: https://github.com/DeFiCh/wallet/issues/1021#issuecomment-946402952
