### ISSUE TITLE
`DEX` - help button to trigger guidelines

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#945]
#### What would you like to be added:
From DEX page, we would like to add a CTA to show DEX guidelines page. Currently, it's only displayed on initial install of app. This will allow users to view content in case they missed out.

/needs design
/assign @jtlntno-cake

**Comment by izzycsy** [comment]
Acceptance Criteria: In DEX screen, user able to access DEX guidelines page 

Android: 

- [ ] DEX > click `i` > Guideline should display

iOS: 
- [ ] DEX > click `i` > Guideline should display
