### ISSUE TITLE
`estimated fees` - faq

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#946]
#### What would you like to be added:
It should be added on all labels using Estimated fees:
![image](https://user-images.githubusercontent.com/25013382/135006562-1bf2e04b-588a-4d02-8966-0f341c6f61eb.png)

**Comment by izzycsy** [comment]
Acceptance Criteria: When user hovers over **Estimated fee `i`**, definition should display

Android: 

- [ ] Send > Send DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] Send > Send dBTC > `Continue` > Hover over **Estimated fee `i`**
- [ ] Send > Send dETH > `Continue` > Hover over **Estimated fee `i`**
- [ ] Send > Send dUSDT > `Continue` > Hover over **Estimated fee `i`**

- [ ] DEX > Add dBTC-DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] DEX > Add dETH-DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] DEX > Add dUSDT-DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] DEX > Remove dBTC-DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] DEX > Remove dETH-DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] DEX > Remove dUSDT-DFI > `Continue` > Hover over **Estimated fee `i`**

iOS: 

- [ ] Send > Send DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] Send > Send dBTC > `Continue` > Hover over **Estimated fee `i`**
- [ ] Send > Send dETH > `Continue` > Hover over **Estimated fee `i`**
- [ ] Send > Send dUSDT > `Continue` > Hover over **Estimated fee `i`**

- [ ] DEX > Add dBTC-DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] DEX > Add dETH-DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] DEX > Add dUSDT-DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] DEX > Remove dBTC-DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] DEX > Remove dETH-DFI > `Continue` > Hover over **Estimated fee `i`**
- [ ] DEX > Remove dUSDT-DFI > `Continue` > Hover over **Estimated fee `i`**

**Comment by thedoublejay** [comment]
@izzycsy It should be click, there's no hover state on mobile
