### ISSUE TITLE
`token info` - redirect

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#947]
#### What would you like to be added:
When viewing token details, we should be able to redirect to DeFiScan to show details of token. Example, Balances -> dBTC -> View Token Details -> DeFiScan Token Detail

https://defiscan.live/tokens/2

**Comment by fullstackninja864** [comment]
@thedoublejay Do we have any design for this?

**Comment by thedoublejay** [comment]
@fullstackninja864 Not yet. Maybe just get with @jtlntno-cake a simple icon and add it as a row on token detail screen. Take note, DFI (UTXO) and DFI (Token) must have same redirect

**Comment by izzycsy** [comment]
Acceptance Criteria: From the selected token screen, redirect user to the Token Details page on DeFiScan 

Android: 

- [ ] Select DFI (UTXO) > select `box w arrow` icon > DeFiScan DeFiChain page
- [ ] Select DFI (Token) > || 
- [ ] Select dETH > || 
- [ ] Select dBTC > || 
- [ ] Select dUSDT > ||
- [ ] Select dETH-DFI > ||  
- [ ] Select dBTC-DFI > ||  
- [ ] Select dUSDT-DFI > ||  
- [ ] Select dUSDC > ||  
- [ ] Select dUSDC-DFI > ||  

iOS: 
- [ ] Select DFI (UTXO) > select `box w arrow` icon > DeFiScan DeFiChain page
- [ ] Select DFI (Token) > || 
- [ ] Select dETH > || 
- [ ] Select dBTC > || 
- [ ] Select dUSDT > ||
- [ ] Select dETH-DFI > ||  
- [ ] Select dBTC-DFI > ||  
- [ ] Select dUSDT-DFI > ||  
- [ ] Select dUSDC > ||  
- [ ] Select dUSDC-DFI > ||
