### ISSUE TITLE
`passcode prompt` - updated design

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#963]
#### What would you like to be added:

- [ ] Updated main title (for Transactions, use Sign Transaction, for others (e.g, Passphrase) - use Enter Passcode)
- [ ] Success screen - to be shown for 2 seconds once a transaction has been signed successfully
- [ ] Keep the transaction preview

![image](https://user-images.githubusercontent.com/25013382/135206383-561fded0-2703-4818-b16b-2bc5af490219.png)

**Comment by jtlntno-cake** [comment]
Hey guys, please see attached for the updated copy. 
![image](https://user-images.githubusercontent.com/85162376/135981488-ef84299d-ac44-4e47-b16c-714e44d2235e.png)


The intent here is to reuse the signature component but contextualize for clarity of the user's journey. We have two types of journey,:

1. Signing Transactions – authorizing transactions to proceed, what we have currently
2. Access verification – verify access of users to restricted features for security. An updated copy is added for this.

Let me know if there's any clarification or questions
@thedoublejay @pierregee

**Comment by pierregee** [comment]
Thanks for the clear explanation! 💪  Will adjust the PR as accordingly!

**Comment by izzycsy** [comment]
Acceptance Criteria: Updated UI for `Sign to verify access` 

Android: 

- [ ] Send > sign with passcode > `success` screen displayed for 2 seconds > check that transaction preview remains
- [ ] Add LP > sign with passcode > `success` screen displayed for 2 seconds > check that transaction preview remains
- [ ] Remove LP > sign with passcode > `success` screen displayed for 2 seconds > check that transaction preview remains

iOS: 

- [ ] Send > sign with passcode > `success` screen displayed for 2 seconds > check that transaction preview remains
- [ ] Add LP > sign with passcode > `success` screen displayed for 2 seconds > check that transaction preview remains
- [ ] Remove LP > sign with passcode > `success` screen displayed for 2 seconds > check that transaction preview remains

**Comment by jtlntno-cake** [comment]
@kyleleow Yeah, it's important users are able to cancel and stay in control over their transactions. 

Do you have a screenshot to how it looks now with it being un-clickable? I was imaging the close button is not necessarily un-clickable across the transaction signing modal.

**Comment by kyleleow** [comment]
@jtlntno-cake it could be a grey out cross icon or a spinner like in GitHub, ![image](https://user-images.githubusercontent.com/40191153/136486303-7d7d49b0-e39b-439e-aca0-3195cf24fc3e.jpeg)
