### ISSUE TITLE
`privacy lock` - incorrect label for Android

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#965]
#### What happened:
On Settings page, "Secure with face recognition" is displayed even though it's not active on device. When you toggle it, it shows fingerprint.
#### Anything else we need to know?:
![20210929_132912](https://user-images.githubusercontent.com/25013382/135208855-f112b0f1-52c9-46b8-8fa4-9433f3c401c0.jpg)
![Screenshot_20210929-132837_DeFiChain Wallet](https://user-images.githubusercontent.com/25013382/135208858-c7b9d47b-860d-4bec-be40-b3a988011ced.jpg)

**Comment by kyleleow** [comment]
@thedoublejay 
The API provided by expo is only able to tell what types of authentications hardware supported, but not exactly the type that the user decided to use. 
E.g.: samsung galaxy s21 has both face recognition and fingerprint hardware, but user can choose to use fingerprint, but expo [API](https://docs.expo.dev/versions/latest/sdk/local-authentication/#localauthenticationsupportedauthenticationtypesasync) will not be able to return this info.

But this is only on Android devices, there isn't any device currently that support both Face ID and Touch ID hardware, so we are able to use the expo API to decide what label to use.

My suggestion:
- iOS: maintain what we have done
- android: replace face recognition, fingerprint, iris scan as "biometric authentication"

**Comment by thedoublejay** [comment]
> @thedoublejay The API provided by expo is only able to tell what types of authentications hardware supported, but not exactly the type that the user decided to use. E.g.: Samsung galaxy s21 has both face recognition and fingerprint hardware, but user can choose to use fingerprint, but expo [API](https://docs.expo.dev/versions/latest/sdk/local-authentication/#localauthenticationsupportedauthenticationtypesasync) will not be able to return this info.
> 
> But this is only on Android devices, there isn't any iOS device currently that support both Face ID and Touch ID hardware, so we are able to use the expo API to decide what label to use.
> 
> My suggestion:
> 
> * iOS: maintain what we have done
> * Android: replace "face recognition", "fingerprint", "iris scan" label with "biometric authentication"

I'm good with this. Let's proceed with this fix. Cc @izzycsy
