### ISSUE TITLE
`Privacy Lock` should always request for re-authentication when app is terminated 

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/wallet#971]
#### What happened:

On iOS `0.10.9` TestFlight build, when I force exit the app and reopen the app, it doesn't always ask me to re-authenticate regardless of the duration (Tested 5 times, 3 times prompt, 2 times didn't). There is probably a likely race condition within the hooks that created the bug in this section: https://github.com/DeFiCh/wallet/blob/main/mobile-app/app/screens/PrivacyLock.tsx

#### What you expected to happen:

We should force re-authentication regardless of duration when the app is force exited (memory reset should set to force regardless).

/triage accepted
/kind bug
/priority urgent-now
/area ui-ux settings

**Comment by izzycsy** [comment]
https://user-images.githubusercontent.com/65014479/135235854-a195d34d-d4f8-4111-8e6f-74bace34cb9a.mp4

iOS: 

- [ ] `Enable Secure with Face ID` - Quit App - Open App - Trigger prompt

**Comment by fuxingloh** [comment]
> Test #973 governance change.

iOS v0.10.9

**Comment by izzycsy** [comment]
Acceptance Criteria: Prompt should appear after quitting & relaunching app

- [ ]  5. Enable Secure with Face ID - Trigger Prompt - Face ID - Quit app - Open app - Trigger prompt
