### ISSUE TITLE
`summary` - prioritise RHS content to not overflow

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#975]
#### What UI/UX improvements would you like to be implemented: 

• Extend margin / grid of each row such that Price of DFI per dToken displays in 1 line only 

#### Why is this needed:
• Currently, inconsistent UI due to widow of dToken falling to the 2nd line. 

#### Which component/screens does this concern?:
• Add liquidity 
• Remove liquidity
• Swap

#### Anything else we need to know?:
![210929 v0 10 9 - iOS -  DEX - Add LP - widow1](https://user-images.githubusercontent.com/65014479/135238422-ce8e7f45-d538-471f-8cee-fac29b87d31e.PNG)

![210929 v0 10 9 - iOS -  DEX - Add LP - widow3](https://user-images.githubusercontent.com/65014479/135238450-aa3c4e56-bd58-4997-84cf-816c7cc45b9a.jpeg)

Expected: 
![210929 v0 10 9 - iOS -  DEX - Add LP - widow2](https://user-images.githubusercontent.com/65014479/135238566-c8792adf-37fd-43e0-bd99-c28f22c699ce.PNG)

**Comment by kyleleow** [comment]
@thedoublejay should I just fix this issue or update the entire the summary section? Since it has a different UI in prototype v0.10.0
![image](https://user-images.githubusercontent.com/40191153/135374785-3803c44b-baa4-4b85-8b1a-32ce664086d2.png)
