### ISSUE TITLE
`Android - About` - YouTube link inactive

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#976]
#### What happened:
• YouTube link inactive

#### What you expected to happen:
• Should open YouTube App / direct user to YouTube website via phone' browser

#### How to reproduce it (as minimally and precisely as possible):
About > select `YouTube`

#### Anything else we need to know?:

https://user-images.githubusercontent.com/65014479/135249023-6aaec730-8dec-4937-9ed3-ef2a55ff33e7.mp4

**Comment by thedoublejay** [comment]
@izzycsy it's the same as #745. This might be a system level issue. Can you verify if you have YouTube installed?

**Comment by thedoublejay** [comment]
https://user-images.githubusercontent.com/25013382/135253190-cbaf7f7e-dd02-4f64-a1af-6425342c4ca4.mp4

Doesn't work on Android 11

**Comment by izzycsy** [comment]
Acceptance Criteria: YouTube app / browser should open

Android: 
- [ ] About > select YouTube

iOS:
- [ ] About > select YouTube

**Comment by izzycsy** [comment]
Acceptance Criteria: YouTube app / browser should open

Android: 
- [x] About > select YouTube

iOS:
- [x] About > select YouTube

**Comment by thedoublejay** [comment]
This will be fixed with SDK 43. It's still not working on Expo side.

**Comment by izzycsy** [comment]
Acceptance Criteria: YouTube app / browser should open

Android: 
- [ ] About > select YouTube

> Actua: 
Refer to main comment

iOS:
- [ ] About > select YouTube
