### ISSUE TITLE
error boundaries for wallet

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#98]
#### What would you like to be added:
Create error boundaries to have handle errors better

**Comment by fuxingloh** [comment]
/triage accepted
/assign @thedoublejay 

Related to #41 should be implemented together?

**Comment by thedoublejay** [comment]
@fuxingloh  this one is just a fallback page in case there are errors on any page. But not necessarily implemented with #41 

First step is to have a fallback screen for errors. Once #41 is implemented, we can add the log everytime this ErrorBoundary is hit.
