### ISSUE TITLE
`Send – UI` - `x` and `qr-code` buttons misalign

### ISSUE THREAD

**Issue by izzycsy** [DeFiCh/wallet#991]
#### What UI/UX improvements would you like to be implemented: 
Actual: 
• In Send screen, after pasting an address to send, `x` and `qr-code` buttons becomes misaligned

Expected: 
• after pasting an address to send, `x` and `qr-code` buttons should remain in its original position

![210930 v0 10 11 - iOS -  Balances - Send - x and qr button misaligned2](https://user-images.githubusercontent.com/65014479/135453082-dd0e1370-cd46-4b70-8f9e-afe4ff0a2261.PNG)

#### Why is this needed: 
• Inconsistency in UI

#### Which component/screens does this concern?:
iOS & Android: 
• Send 

#### Anything else we need to know?:

![210930 v0 10 11 - iOS -  Balances - Send - x and qr button misaligned](https://user-images.githubusercontent.com/65014479/135452870-78673de9-f2ef-4423-a3b3-b454674ddf77.PNG)

**Comment by thedoublejay** [comment]
![Screenshot_20210930-204240_DeFiChain Wallet.jpg](https://user-images.githubusercontent.com/25013382/135457048-df5384c4-4fb5-4bc5-9f8f-b8fd04d8d1f2.jpg)

**Comment by izzycsy** [comment]
Acceptance Criteria: x and qr-code buttons should remain in its original position

Android: 

- [ ] Send > paste address > x and qr-code buttons should remain in its original position

iOS:

- [ ] Send > paste address > x and qr-code buttons should remain in its original position
